#!/usr/bin/env node
/*
 * Generate AI food photos for Foodiee recipes using the OpenAI Images API.
 *
 * Usage:
 *   OPENAI_API_KEY=sk-...  node scripts/generate-images.mjs viral     # just the 10 viral recipes (pilot)
 *   OPENAI_API_KEY=sk-...  node scripts/generate-images.mjs all       # every recipe
 *   OPENAI_API_KEY=sk-...  node scripts/generate-images.mjs id1,id2   # specific recipe ids
 *
 * Output: public/images/<id>.jpg  +  refreshes src/imageManifest.js
 *
 * Model: gpt-image-1 (JPEG output). Override with IMAGE_MODEL if needed.
 * Note: gpt-image-1 may require a one-time org verification on your OpenAI account.
 */
import { writeFile, mkdir, readdir } from 'node:fs/promises'
import { recipes } from '../src/recipes.js'

const API_KEY = process.env.OPENAI_API_KEY
const MODEL = process.env.IMAGE_MODEL || 'gpt-image-1'
const OUT_DIR = new URL('../public/images/', import.meta.url)
const MANIFEST = new URL('../src/imageManifest.js', import.meta.url)

if (!API_KEY) {
  console.error('✗ Set OPENAI_API_KEY (e.g. OPENAI_API_KEY=sk-... node scripts/generate-images.mjs viral)')
  process.exit(1)
}

const arg = (process.argv[2] || 'viral').trim()
let targets
if (arg === 'all') targets = recipes
else if (arg === 'viral') targets = recipes.filter((r) => r.tags.includes('viral'))
else {
  const ids = new Set(arg.split(',').map((s) => s.trim()))
  targets = recipes.filter((r) => ids.has(r.id))
}

if (!targets.length) {
  console.error(`✗ No recipes matched "${arg}".`)
  process.exit(1)
}

await mkdir(OUT_DIR, { recursive: true })
console.log(`Generating ${targets.length} image(s) with ${MODEL}…\n`)

const prompt = (r) =>
  `Professional overhead food photography of "${r.title}", ${r.cuisine} cuisine. ` +
  `Beautifully plated and garnished on a clean light neutral background, soft natural ` +
  `lighting, shallow depth of field, fresh and appetising, high detail, realistic. ` +
  `No text, no labels, no hands, no people.`

let ok = 0
let failed = 0
for (const r of targets) {
  try {
    const body = { model: MODEL, prompt: prompt(r), size: '1024x1024', n: 1 }
    if (MODEL === 'gpt-image-1') {
      body.output_format = 'jpeg'
      body.output_compression = 80
    } else {
      body.response_format = 'b64_json' // dall-e-3 etc.
    }

    const res = await fetch('https://api.openai.com/v1/images/generations', {
      method: 'POST',
      headers: { Authorization: `Bearer ${API_KEY}`, 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
    })
    const data = await res.json()
    if (!res.ok) {
      failed++
      console.error(`✗ ${r.id}: ${data.error?.message || res.status}`)
      continue
    }
    const b64 = data.data?.[0]?.b64_json
    if (!b64) {
      failed++
      console.error(`✗ ${r.id}: no image data returned`)
      continue
    }
    await writeFile(new URL(`${r.id}.jpg`, OUT_DIR), Buffer.from(b64, 'base64'))
    ok++
    console.log(`✓ ${r.id}`)
  } catch (err) {
    failed++
    console.error(`✗ ${r.id}: ${err.message}`)
  }
}

// Refresh the manifest from whatever image files now exist.
const files = await readdir(OUT_DIR)
const ids = files.filter((f) => f.endsWith('.jpg')).map((f) => f.replace(/\.jpg$/, '')).sort()
await writeFile(
  MANIFEST,
  `// Auto-generated by scripts/generate-images.mjs — recipe ids that have an image\n` +
    `// at public/images/<id>.jpg. Do not edit by hand; re-run the image script.\n` +
    `export const IMAGED = new Set(${JSON.stringify(ids, null, 2)})\n`,
)

console.log(`\nDone: ${ok} generated, ${failed} failed. ${ids.length} total image(s). Manifest updated.`)
