// Auto-generated by scripts/generate-images.mjs — maps recipe id -> image filename
// in public/images/. Do not edit by hand; re-run the image script.
export const IMAGES = {
  "airfryer-baked-feta-pasta": "airfryer-baked-feta-pasta.jpg",
  "airfryer-bang-bang-chicken": "airfryer-bang-bang-chicken.jpg",
  "airfryer-bang-bang-salmon": "airfryer-bang-bang-salmon.jpg",
  "airfryer-corn-ribs": "airfryer-corn-ribs.jpg",
  "airfryer-creme-brulee": "airfryer-creme-brulee.jpg",
  "airfryer-nutella-toast-pies": "airfryer-nutella-toast-pies.jpg",
  "airfryer-pasta-chips": "airfryer-pasta-chips.jpg",
  "airfryer-smashed-potatoes": "airfryer-smashed-potatoes.jpg",
  "airfryer-soy-chicken-thighs": "airfryer-soy-chicken-thighs.jpg",
  "steamed-soup-dumplings": "steamed-soup-dumplings.jpg"
}
