// Auto-generated by scripts/generate-images.mjs — lists recipe ids that have a
// real/AI image at public/images/<id>.jpg. Recipes not listed here fall back to
// the emoji-on-gradient hero. Do not edit by hand; re-run the image script.
export const IMAGED = new Set([])
