// Auto-generated by scripts/generate-images.mjs — maps recipe id -> image filename
// in public/images/. Recipes not listed here fall back to the emoji-on-gradient
// hero. Do not edit by hand; re-run the image script.
export const IMAGES = {}
