// Auto-generated by scripts/tag-ingredients.mjs — canonical ingredient tags
// for pantry matching. Do not edit by hand; re-run the script.

export const STAPLES = ["salt","water","oil","sugar","black pepper"]

export const PANTRY = {
  "Vegetables": [
    "asparagus",
    "aubergine",
    "bamboo shoot",
    "bok choy",
    "broccoli",
    "brussels sprout",
    "cabbage",
    "capsicum",
    "carrot",
    "cherry tomato",
    "colocasia leaf",
    "corn",
    "green bean",
    "mushroom",
    "potato",
    "spinach",
    "sweet potato",
    "zucchini"
  ],
  "Fruits": [
    "apple",
    "banana",
    "dried fruit",
    "lemon",
    "lime",
    "plantain"
  ],
  "Herbs & aromatics": [
    "basil",
    "chilli",
    "coriander",
    "curry leaf",
    "dill",
    "garlic",
    "ginger",
    "ginger garlic paste",
    "ginger green chilli paste",
    "kaffir lime leaf",
    "lemongrass",
    "onion",
    "parsley",
    "rosemary",
    "spring onion"
  ],
  "Dairy & eggs": [
    "butter",
    "buttermilk",
    "cheese",
    "coconut milk",
    "cream",
    "cream cheese",
    "egg",
    "feta",
    "milk",
    "mozzarella",
    "parmesan",
    "ricotta",
    "yogurt"
  ],
  "Paneer & proteins": [
    "chicken",
    "fish",
    "lamb",
    "paneer",
    "pork",
    "prawn",
    "salmon",
    "sausage",
    "tofu"
  ],
  "Flours & grains": [
    "besan",
    "bread",
    "cornflour",
    "flour",
    "oat",
    "pasta",
    "pita",
    "rice",
    "rice flour",
    "semolina",
    "tortilla"
  ],
  "Lentils & pulses": [
    "black bean",
    "chana dal",
    "chickpea",
    "edamame"
  ],
  "Spices & masalas": [
    "cardamom",
    "chaat masala",
    "chilli lime seasoning",
    "chilli powder",
    "cinnamon",
    "cumin",
    "garam masala",
    "garlic powder",
    "italian herb",
    "mustard seed",
    "paprika",
    "pepper",
    "tandoori masala",
    "turmeric"
  ],
  "Oils & fats": [
    "ghee",
    "olive oil",
    "sesame oil"
  ],
  "Condiments & sauces": [
    "balsamic vinegar",
    "buffalo sauce",
    "chocolate sauce",
    "coconut chutney",
    "dashi",
    "fish sauce",
    "gochujang",
    "hoisin sauce",
    "lemon juice",
    "marinara sauce",
    "mayonnaise",
    "nutella",
    "peanut butter",
    "peri-peri sauce",
    "red curry paste",
    "salsa",
    "soy sauce",
    "sriracha",
    "stock",
    "sweet chilli sauce",
    "tamarind",
    "tomato sauce"
  ],
  "Nuts & seeds": [
    "coconut",
    "nut",
    "sesame seed"
  ],
  "Sweeteners": [
    "brown sugar",
    "cinnamon sugar",
    "honey",
    "icing sugar",
    "maple syrup"
  ],
  "Baking & other": [
    "baking powder",
    "breadcrumb",
    "chocolate chip",
    "dark chocolate",
    "dough",
    "eno fruit salt",
    "idli batter",
    "pizza base",
    "puff pastry",
    "vanilla",
    "wrapper"
  ]
}

export const RECIPE_INGREDIENTS = {
  "soft-boiled-eggs": [
    {
      "raw": "Up to 6 eggs",
      "canon": "egg",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "Measuring cup of water (use the marking for your desired doneness)",
      "canon": "water",
      "category": "Baking & other",
      "staple": true
    },
    {
      "raw": "Pinch of salt and pepper, to serve",
      "canon": "salt",
      "category": "Spices & masalas",
      "staple": true
    }
  ],
  "airfryer-french-toast": [
    {
      "raw": "4 thick slices of bread, cut into 3 sticks each",
      "canon": "bread",
      "category": "Flours & grains",
      "staple": false
    },
    {
      "raw": "2 eggs",
      "canon": "egg",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "60 ml milk",
      "canon": "milk",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "1 tsp cinnamon",
      "canon": "cinnamon",
      "category": "Spices & masalas",
      "staple": false
    },
    {
      "raw": "1 tsp vanilla",
      "canon": "vanilla",
      "category": "Baking & other",
      "staple": false
    },
    {
      "raw": "Maple syrup, to serve",
      "canon": "maple syrup",
      "category": "Sweeteners",
      "staple": false
    }
  ],
  "steamed-idli": [
    {
      "raw": "2 cups fermented idli batter",
      "canon": "idli batter",
      "category": "Baking & other",
      "staple": false
    },
    {
      "raw": "Oil or ghee, to grease",
      "canon": "oil",
      "category": "Oils & fats",
      "staple": true
    },
    {
      "raw": "Coconut chutney and sambar, to serve",
      "canon": "coconut chutney",
      "category": "Condiments & sauces",
      "staple": false
    }
  ],
  "airfryer-hash-browns": [
    {
      "raw": "2 large potatoes, grated",
      "canon": "potato",
      "category": "Vegetables",
      "staple": false
    },
    {
      "raw": "1 tbsp cornflour",
      "canon": "cornflour",
      "category": "Flours & grains",
      "staple": false
    },
    {
      "raw": "½ tsp salt",
      "canon": "salt",
      "category": "Spices & masalas",
      "staple": true
    },
    {
      "raw": "¼ tsp black pepper",
      "canon": "black pepper",
      "category": "Spices & masalas",
      "staple": true
    },
    {
      "raw": "½ tsp paprika",
      "canon": "paprika",
      "category": "Spices & masalas",
      "staple": false
    },
    {
      "raw": "1 tbsp oil",
      "canon": "oil",
      "category": "Oils & fats",
      "staple": true
    }
  ],
  "steamed-veg-momos": [
    {
      "raw": "20 momo wrappers",
      "canon": "wrapper",
      "category": "Baking & other",
      "staple": false
    },
    {
      "raw": "2 cups finely shredded cabbage",
      "canon": "cabbage",
      "category": "Vegetables",
      "staple": false
    },
    {
      "raw": "1 carrot, grated",
      "canon": "carrot",
      "category": "Vegetables",
      "staple": false
    },
    {
      "raw": "2 spring onions, chopped",
      "canon": "spring onion",
      "category": "Herbs & aromatics",
      "staple": false
    },
    {
      "raw": "1 tbsp soy sauce",
      "canon": "soy sauce",
      "category": "Condiments & sauces",
      "staple": false
    },
    {
      "raw": "1 tsp grated ginger + garlic",
      "canon": "ginger",
      "category": "Herbs & aromatics",
      "staple": false
    },
    {
      "raw": "Salt and pepper",
      "canon": "salt",
      "category": "Spices & masalas",
      "staple": true
    }
  ],
  "airfryer-paneer-tikka": [
    {
      "raw": "250 g paneer, cubed",
      "canon": "paneer",
      "category": "Paneer & proteins",
      "staple": false
    },
    {
      "raw": "1 capsicum + 1 onion, in chunks",
      "canon": "capsicum",
      "category": "Vegetables",
      "staple": false
    },
    {
      "raw": "4 tbsp thick yogurt",
      "canon": "yogurt",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "1 tbsp ginger-garlic paste",
      "canon": "ginger garlic paste",
      "category": "Herbs & aromatics",
      "staple": false
    },
    {
      "raw": "1 tsp each: chilli powder, garam masala, cumin",
      "canon": "chilli powder",
      "category": "Spices & masalas",
      "staple": false
    },
    {
      "raw": "1 tbsp besan (gram flour)",
      "canon": "besan",
      "category": "Flours & grains",
      "staple": false
    },
    {
      "raw": "1 tbsp oil, salt",
      "canon": "oil",
      "category": "Oils & fats",
      "staple": true
    }
  ],
  "steamed-lemon-fish": [
    {
      "raw": "2 white fish fillets (basa, tilapia or cod)",
      "canon": "fish",
      "category": "Paneer & proteins",
      "staple": false
    },
    {
      "raw": "1 lemon, half sliced + half juiced",
      "canon": "lemon",
      "category": "Fruits",
      "staple": false
    },
    {
      "raw": "2 cloves garlic, minced",
      "canon": "garlic",
      "category": "Herbs & aromatics",
      "staple": false
    },
    {
      "raw": "A few sprigs of dill or parsley",
      "canon": "dill",
      "category": "Herbs & aromatics",
      "staple": false
    },
    {
      "raw": "1 tbsp olive oil, salt and pepper",
      "canon": "olive oil",
      "category": "Oils & fats",
      "staple": false
    }
  ],
  "airfryer-falafel": [
    {
      "raw": "1½ cups soaked (not cooked) chickpeas",
      "canon": "chickpea",
      "category": "Lentils & pulses",
      "staple": false
    },
    {
      "raw": "1 small onion + 3 garlic cloves",
      "canon": "onion",
      "category": "Herbs & aromatics",
      "staple": false
    },
    {
      "raw": "Handful of parsley and coriander",
      "canon": "parsley",
      "category": "Herbs & aromatics",
      "staple": false
    },
    {
      "raw": "1 tsp cumin, 1 tsp coriander powder",
      "canon": "cumin",
      "category": "Spices & masalas",
      "staple": false
    },
    {
      "raw": "2 tbsp besan, salt",
      "canon": "besan",
      "category": "Flours & grains",
      "staple": false
    },
    {
      "raw": "Oil spray",
      "canon": "oil",
      "category": "Oils & fats",
      "staple": true
    }
  ],
  "steamed-veg-rice-bowl": [
    {
      "raw": "1 cup rice + 1¼ cups water",
      "canon": "rice",
      "category": "Flours & grains",
      "staple": false
    },
    {
      "raw": "Broccoli, carrot and beans, chopped",
      "canon": "broccoli",
      "category": "Vegetables",
      "staple": false
    },
    {
      "raw": "1 tbsp soy sauce",
      "canon": "soy sauce",
      "category": "Condiments & sauces",
      "staple": false
    },
    {
      "raw": "1 tsp sesame oil",
      "canon": "sesame oil",
      "category": "Oils & fats",
      "staple": false
    },
    {
      "raw": "1 tsp toasted sesame seeds",
      "canon": "sesame seed",
      "category": "Nuts & seeds",
      "staple": false
    }
  ],
  "airfryer-stuffed-peppers": [
    {
      "raw": "4 bell peppers, tops cut and seeded",
      "canon": "capsicum",
      "category": "Vegetables",
      "staple": false
    },
    {
      "raw": "1 cup cooked rice or quinoa",
      "canon": "rice",
      "category": "Flours & grains",
      "staple": false
    },
    {
      "raw": "½ cup black beans or corn",
      "canon": "black bean",
      "category": "Lentils & pulses",
      "staple": false
    },
    {
      "raw": "½ cup grated cheese",
      "canon": "cheese",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "1 tsp cumin + 1 tsp paprika",
      "canon": "cumin",
      "category": "Spices & masalas",
      "staple": false
    },
    {
      "raw": "Salt, pepper, coriander",
      "canon": "salt",
      "category": "Spices & masalas",
      "staple": true
    }
  ],
  "airfryer-chicken-wings": [
    {
      "raw": "700 g chicken wings, patted dry",
      "canon": "chicken",
      "category": "Paneer & proteins",
      "staple": false
    },
    {
      "raw": "1 tbsp baking powder (for crispness)",
      "canon": "baking powder",
      "category": "Baking & other",
      "staple": false
    },
    {
      "raw": "1 tsp each: garlic powder, paprika, salt",
      "canon": "garlic powder",
      "category": "Spices & masalas",
      "staple": false
    },
    {
      "raw": "½ tsp black pepper",
      "canon": "black pepper",
      "category": "Spices & masalas",
      "staple": true
    },
    {
      "raw": "Buffalo or BBQ sauce, to toss",
      "canon": "buffalo sauce",
      "category": "Condiments & sauces",
      "staple": false
    }
  ],
  "airfryer-veg-spring-rolls": [
    {
      "raw": "12 spring roll wrappers",
      "canon": "wrapper",
      "category": "Baking & other",
      "staple": false
    },
    {
      "raw": "3 cups shredded cabbage, carrot, capsicum",
      "canon": "cabbage",
      "category": "Vegetables",
      "staple": false
    },
    {
      "raw": "1 tbsp soy sauce + 1 tsp vinegar",
      "canon": "soy sauce",
      "category": "Condiments & sauces",
      "staple": false
    },
    {
      "raw": "1 tsp ginger-garlic paste",
      "canon": "ginger garlic paste",
      "category": "Herbs & aromatics",
      "staple": false
    },
    {
      "raw": "Oil spray",
      "canon": "cooking oil",
      "category": "Oils & fats",
      "staple": true
    },
    {
      "raw": "Flour-water paste, to seal",
      "canon": "flour",
      "category": "Flours & grains",
      "staple": false
    }
  ],
  "steamed-dumpling-soup": [
    {
      "raw": "2 chicken breasts, thinly sliced (or tofu for veg)",
      "canon": "chicken",
      "category": "Paneer & proteins",
      "staple": false
    },
    {
      "raw": "1 tbsp soy sauce + 1 tsp honey",
      "canon": "soy sauce",
      "category": "Condiments & sauces",
      "staple": false
    },
    {
      "raw": "1 tsp grated ginger",
      "canon": "ginger",
      "category": "Herbs & aromatics",
      "staple": false
    },
    {
      "raw": "Bok choy or spinach",
      "canon": "bok choy",
      "category": "Vegetables",
      "staple": false
    },
    {
      "raw": "Spring onion, to garnish",
      "canon": "spring onion",
      "category": "Herbs & aromatics",
      "staple": false
    }
  ],
  "airfryer-roasted-veg": [
    {
      "raw": "4 cups mixed veg (zucchini, peppers, onion, mushroom, cherry tomato)",
      "canon": "zucchini",
      "category": "Vegetables",
      "staple": false
    },
    {
      "raw": "2 tbsp olive oil",
      "canon": "olive oil",
      "category": "Oils & fats",
      "staple": false
    },
    {
      "raw": "1 tsp Italian herbs",
      "canon": "italian herb",
      "category": "Spices & masalas",
      "staple": false
    },
    {
      "raw": "2 cloves garlic, minced",
      "canon": "garlic",
      "category": "Herbs & aromatics",
      "staple": false
    },
    {
      "raw": "Salt, pepper, chilli flakes",
      "canon": "salt",
      "category": "Spices & masalas",
      "staple": true
    }
  ],
  "airfryer-salmon": [
    {
      "raw": "2 salmon fillets",
      "canon": "salmon",
      "category": "Paneer & proteins",
      "staple": false
    },
    {
      "raw": "2 tbsp honey",
      "canon": "honey",
      "category": "Sweeteners",
      "staple": false
    },
    {
      "raw": "2 cloves garlic, minced",
      "canon": "garlic",
      "category": "Herbs & aromatics",
      "staple": false
    },
    {
      "raw": "1 tbsp soy sauce",
      "canon": "soy sauce",
      "category": "Condiments & sauces",
      "staple": false
    },
    {
      "raw": "1 tsp lemon juice",
      "canon": "lemon juice",
      "category": "Condiments & sauces",
      "staple": false
    },
    {
      "raw": "Salt and pepper",
      "canon": "salt",
      "category": "Spices & masalas",
      "staple": true
    }
  ],
  "steamed-corn-edamame": [
    {
      "raw": "1 cup sweetcorn",
      "canon": "corn",
      "category": "Vegetables",
      "staple": false
    },
    {
      "raw": "1 cup edamame (in pods or shelled)",
      "canon": "edamame",
      "category": "Lentils & pulses",
      "staple": false
    },
    {
      "raw": "1 tbsp butter or olive oil",
      "canon": "butter",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "Chilli-lime seasoning or chaat masala",
      "canon": "chilli lime seasoning",
      "category": "Spices & masalas",
      "staple": false
    },
    {
      "raw": "Flaky salt",
      "canon": "salt",
      "category": "Spices & masalas",
      "staple": true
    }
  ],
  "airfryer-tandoori-chicken": [
    {
      "raw": "6 bone-in chicken drumsticks or thighs, slashed",
      "canon": "chicken",
      "category": "Paneer & proteins",
      "staple": false
    },
    {
      "raw": "5 tbsp thick yogurt",
      "canon": "yogurt",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "1 tbsp ginger-garlic paste",
      "canon": "ginger garlic paste",
      "category": "Herbs & aromatics",
      "staple": false
    },
    {
      "raw": "1 tbsp tandoori masala + 1 tsp chilli powder",
      "canon": "tandoori masala",
      "category": "Spices & masalas",
      "staple": false
    },
    {
      "raw": "1 tsp garam masala, ½ tsp turmeric",
      "canon": "garam masala",
      "category": "Spices & masalas",
      "staple": false
    },
    {
      "raw": "1 tbsp lemon juice + 1 tbsp oil, salt",
      "canon": "lemon",
      "category": "Fruits",
      "staple": false
    }
  ],
  "airfryer-chicken-tenders": [
    {
      "raw": "500 g chicken breast, cut into strips",
      "canon": "chicken",
      "category": "Paneer & proteins",
      "staple": false
    },
    {
      "raw": "1 egg, beaten",
      "canon": "egg",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "1 cup breadcrumbs (panko works best)",
      "canon": "breadcrumb",
      "category": "Baking & other",
      "staple": false
    },
    {
      "raw": "½ cup flour",
      "canon": "flour",
      "category": "Flours & grains",
      "staple": false
    },
    {
      "raw": "1 tsp paprika + 1 tsp garlic powder, salt, pepper",
      "canon": "paprika",
      "category": "Spices & masalas",
      "staple": false
    },
    {
      "raw": "Oil spray",
      "canon": "oil",
      "category": "Oils & fats",
      "staple": true
    }
  ],
  "airfryer-chicken-shawarma": [
    {
      "raw": "600 g boneless chicken thighs",
      "canon": "chicken",
      "category": "Paneer & proteins",
      "staple": false
    },
    {
      "raw": "2 tbsp oil + 1 tbsp lemon juice",
      "canon": "oil",
      "category": "Oils & fats",
      "staple": true
    },
    {
      "raw": "1 tsp each: cumin, coriander, paprika, garlic powder",
      "canon": "cumin",
      "category": "Spices & masalas",
      "staple": false
    },
    {
      "raw": "½ tsp turmeric + ½ tsp cinnamon, salt",
      "canon": "turmeric",
      "category": "Spices & masalas",
      "staple": false
    },
    {
      "raw": "Pita, garlic sauce and salad, to serve",
      "canon": "pita",
      "category": "Flours & grains",
      "staple": false
    }
  ],
  "steamed-lemongrass-chicken": [
    {
      "raw": "2 boneless chicken breasts or 4 thighs",
      "canon": "chicken",
      "category": "Paneer & proteins",
      "staple": false
    },
    {
      "raw": "1 lemongrass stalk, bruised and chopped",
      "canon": "lemongrass",
      "category": "Herbs & aromatics",
      "staple": false
    },
    {
      "raw": "1 tbsp fish sauce + 1 tsp honey",
      "canon": "fish sauce",
      "category": "Condiments & sauces",
      "staple": false
    },
    {
      "raw": "1 tsp grated ginger + 2 garlic cloves",
      "canon": "ginger",
      "category": "Herbs & aromatics",
      "staple": false
    },
    {
      "raw": "Coriander and lime, to serve",
      "canon": "coriander",
      "category": "Herbs & aromatics",
      "staple": false
    }
  ],
  "airfryer-peri-peri-drumsticks": [
    {
      "raw": "8 chicken drumsticks",
      "canon": "chicken",
      "category": "Paneer & proteins",
      "staple": false
    },
    {
      "raw": "3 tbsp peri-peri sauce",
      "canon": "peri-peri sauce",
      "category": "Condiments & sauces",
      "staple": false
    },
    {
      "raw": "1 tbsp oil + 1 tbsp lemon juice",
      "canon": "oil",
      "category": "Oils & fats",
      "staple": true
    },
    {
      "raw": "1 tsp smoked paprika + 1 tsp garlic powder, salt",
      "canon": "paprika",
      "category": "Spices & masalas",
      "staple": false
    }
  ],
  "airfryer-lamb-chops": [
    {
      "raw": "6 lamb chops",
      "canon": "lamb",
      "category": "Paneer & proteins",
      "staple": false
    },
    {
      "raw": "2 tbsp olive oil",
      "canon": "olive oil",
      "category": "Oils & fats",
      "staple": false
    },
    {
      "raw": "3 garlic cloves, minced",
      "canon": "garlic",
      "category": "Herbs & aromatics",
      "staple": false
    },
    {
      "raw": "1 tbsp chopped rosemary + thyme",
      "canon": "rosemary",
      "category": "Herbs & aromatics",
      "staple": false
    },
    {
      "raw": "1 tsp lemon zest, salt and pepper",
      "canon": "lemon",
      "category": "Fruits",
      "staple": false
    }
  ],
  "airfryer-lamb-seekh-kebab": [
    {
      "raw": "500 g lamb mince",
      "canon": "lamb",
      "category": "Paneer & proteins",
      "staple": false
    },
    {
      "raw": "1 small onion + 2 green chillies, very finely chopped",
      "canon": "onion",
      "category": "Herbs & aromatics",
      "staple": false
    },
    {
      "raw": "1 tbsp ginger-garlic paste",
      "canon": "ginger garlic paste",
      "category": "Herbs & aromatics",
      "staple": false
    },
    {
      "raw": "1 tsp garam masala + 1 tsp cumin + ½ tsp chilli powder",
      "canon": "garam masala",
      "category": "Spices & masalas",
      "staple": false
    },
    {
      "raw": "Handful of chopped coriander and mint, salt",
      "canon": "coriander",
      "category": "Herbs & aromatics",
      "staple": false
    }
  ],
  "airfryer-lamb-koftas": [
    {
      "raw": "500 g lamb mince",
      "canon": "lamb",
      "category": "Paneer & proteins",
      "staple": false
    },
    {
      "raw": "1 grated onion (squeezed dry)",
      "canon": "onion",
      "category": "Herbs & aromatics",
      "staple": false
    },
    {
      "raw": "2 garlic cloves, minced",
      "canon": "garlic",
      "category": "Herbs & aromatics",
      "staple": false
    },
    {
      "raw": "1 tsp cumin + 1 tsp coriander + ½ tsp cinnamon",
      "canon": "cumin",
      "category": "Spices & masalas",
      "staple": false
    },
    {
      "raw": "Chopped parsley and mint, salt and pepper",
      "canon": "parsley",
      "category": "Herbs & aromatics",
      "staple": false
    }
  ],
  "airfryer-fish-fingers": [
    {
      "raw": "500 g firm white fish, cut into fingers",
      "canon": "fish",
      "category": "Paneer & proteins",
      "staple": false
    },
    {
      "raw": "1 egg, beaten",
      "canon": "egg",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "1 cup breadcrumbs (panko)",
      "canon": "breadcrumb",
      "category": "Baking & other",
      "staple": false
    },
    {
      "raw": "½ cup flour",
      "canon": "flour",
      "category": "Flours & grains",
      "staple": false
    },
    {
      "raw": "1 tsp paprika, salt, pepper",
      "canon": "paprika",
      "category": "Spices & masalas",
      "staple": false
    },
    {
      "raw": "Oil spray",
      "canon": "oil",
      "category": "Oils & fats",
      "staple": true
    }
  ],
  "airfryer-garlic-prawns": [
    {
      "raw": "300 g large prawns, peeled and deveined",
      "canon": "prawn",
      "category": "Paneer & proteins",
      "staple": false
    },
    {
      "raw": "2 tbsp melted butter",
      "canon": "butter",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "3 garlic cloves, minced",
      "canon": "garlic",
      "category": "Herbs & aromatics",
      "staple": false
    },
    {
      "raw": "1 tsp paprika + ¼ tsp chilli flakes",
      "canon": "paprika",
      "category": "Spices & masalas",
      "staple": false
    },
    {
      "raw": "Parsley, lemon, salt",
      "canon": "parsley",
      "category": "Herbs & aromatics",
      "staple": false
    }
  ],
  "steamed-ginger-soy-fish": [
    {
      "raw": "2 white fish fillets (sea bass, basa or tilapia)",
      "canon": "fish",
      "category": "Paneer & proteins",
      "staple": false
    },
    {
      "raw": "2 tbsp light soy sauce + 1 tsp sesame oil",
      "canon": "soy sauce",
      "category": "Condiments & sauces",
      "staple": false
    },
    {
      "raw": "1 thumb ginger, julienned",
      "canon": "ginger",
      "category": "Herbs & aromatics",
      "staple": false
    },
    {
      "raw": "2 spring onions, shredded",
      "canon": "spring onion",
      "category": "Herbs & aromatics",
      "staple": false
    },
    {
      "raw": "1 tsp sugar, pinch of white pepper",
      "canon": "sugar",
      "category": "Sweeteners",
      "staple": true
    }
  ],
  "airfryer-fish-tikka": [
    {
      "raw": "500 g firm fish (king fish, salmon or basa), cubed",
      "canon": "fish",
      "category": "Paneer & proteins",
      "staple": false
    },
    {
      "raw": "4 tbsp thick yogurt",
      "canon": "yogurt",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "1 tbsp ginger-garlic paste",
      "canon": "ginger garlic paste",
      "category": "Herbs & aromatics",
      "staple": false
    },
    {
      "raw": "1 tsp each: chilli powder, garam masala, cumin",
      "canon": "chilli powder",
      "category": "Spices & masalas",
      "staple": false
    },
    {
      "raw": "1 tbsp besan + 1 tbsp lemon juice, salt",
      "canon": "besan",
      "category": "Flours & grains",
      "staple": false
    }
  ],
  "airfryer-crispy-tofu": [
    {
      "raw": "400 g firm tofu, pressed and cubed",
      "canon": "tofu",
      "category": "Paneer & proteins",
      "staple": false
    },
    {
      "raw": "1 tbsp cornflour + 1 tbsp soy sauce",
      "canon": "cornflour",
      "category": "Flours & grains",
      "staple": false
    },
    {
      "raw": "1 tbsp oil",
      "canon": "oil",
      "category": "Oils & fats",
      "staple": true
    },
    {
      "raw": "2 tbsp sweet chilli sauce",
      "canon": "sweet chilli sauce",
      "category": "Condiments & sauces",
      "staple": false
    },
    {
      "raw": "1 tsp sriracha, sesame seeds, spring onion",
      "canon": "sriracha",
      "category": "Condiments & sauces",
      "staple": false
    }
  ],
  "airfryer-breakfast-sausages": [
    {
      "raw": "6 chicken or pork breakfast sausages",
      "canon": "sausage",
      "category": "Paneer & proteins",
      "staple": false
    },
    {
      "raw": "Optional: brush of oil",
      "canon": "oil",
      "category": "Oils & fats",
      "staple": true
    }
  ],
  "airfryer-veggie-frittata": [
    {
      "raw": "4 eggs",
      "canon": "egg",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "¼ cup milk",
      "canon": "milk",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "½ cup chopped peppers, onion and spinach",
      "canon": "pepper",
      "category": "Spices & masalas",
      "staple": false
    },
    {
      "raw": "¼ cup grated cheese",
      "canon": "cheese",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "Salt, pepper, chilli flakes",
      "canon": "salt",
      "category": "Spices & masalas",
      "staple": true
    }
  ],
  "steamed-egg-custard": [
    {
      "raw": "3 eggs",
      "canon": "egg",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "1.5 cups warm dashi or light stock",
      "canon": "dashi",
      "category": "Condiments & sauces",
      "staple": false
    },
    {
      "raw": "1 tsp soy sauce + ½ tsp mirin",
      "canon": "soy sauce",
      "category": "Condiments & sauces",
      "staple": false
    },
    {
      "raw": "A few prawns, mushroom slices or peas",
      "canon": "prawn",
      "category": "Paneer & proteins",
      "staple": false
    },
    {
      "raw": "Spring onion, to garnish",
      "canon": "spring onion",
      "category": "Herbs & aromatics",
      "staple": false
    }
  ],
  "airfryer-honey-garlic-pork-chops": [
    {
      "raw": "2 thick boneless pork chops",
      "canon": "pork",
      "category": "Paneer & proteins",
      "staple": false
    },
    {
      "raw": "2 tbsp honey + 2 tbsp soy sauce",
      "canon": "honey",
      "category": "Sweeteners",
      "staple": false
    },
    {
      "raw": "3 garlic cloves, minced",
      "canon": "garlic",
      "category": "Herbs & aromatics",
      "staple": false
    },
    {
      "raw": "1 tsp paprika + ½ tsp black pepper",
      "canon": "paprika",
      "category": "Spices & masalas",
      "staple": false
    },
    {
      "raw": "1 tbsp oil, salt",
      "canon": "oil",
      "category": "Oils & fats",
      "staple": true
    }
  ],
  "airfryer-crispy-pork-chops": [
    {
      "raw": "3 boneless pork chops, pounded slightly thin",
      "canon": "pork",
      "category": "Paneer & proteins",
      "staple": false
    },
    {
      "raw": "1 egg, beaten",
      "canon": "egg",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "1 cup breadcrumbs (panko) + 2 tbsp grated parmesan",
      "canon": "breadcrumb",
      "category": "Baking & other",
      "staple": false
    },
    {
      "raw": "½ cup flour",
      "canon": "flour",
      "category": "Flours & grains",
      "staple": false
    },
    {
      "raw": "1 tsp garlic powder + 1 tsp paprika, salt, pepper",
      "canon": "garlic powder",
      "category": "Spices & masalas",
      "staple": false
    },
    {
      "raw": "Oil spray",
      "canon": "oil",
      "category": "Oils & fats",
      "staple": true
    }
  ],
  "steamed-blackbean-pork-ribs": [
    {
      "raw": "500 g pork spare ribs, cut into bite-size pieces",
      "canon": "pork",
      "category": "Paneer & proteins",
      "staple": false
    },
    {
      "raw": "1.5 tbsp fermented black beans, rinsed and mashed",
      "canon": "black bean",
      "category": "Lentils & pulses",
      "staple": false
    },
    {
      "raw": "1 tbsp soy sauce + 1 tsp sugar + 1 tsp cornflour",
      "canon": "soy sauce",
      "category": "Condiments & sauces",
      "staple": false
    },
    {
      "raw": "2 garlic cloves + 1 tsp grated ginger",
      "canon": "garlic",
      "category": "Herbs & aromatics",
      "staple": false
    },
    {
      "raw": "1 tsp sesame oil, spring onion and chilli to garnish",
      "canon": "sesame oil",
      "category": "Oils & fats",
      "staple": false
    }
  ],
  "airfryer-coconut-prawns": [
    {
      "raw": "350 g large prawns, peeled with tails on",
      "canon": "prawn",
      "category": "Paneer & proteins",
      "staple": false
    },
    {
      "raw": "1 egg, beaten",
      "canon": "egg",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "½ cup flour + 1 tsp paprika, salt",
      "canon": "flour",
      "category": "Flours & grains",
      "staple": false
    },
    {
      "raw": "1 cup desiccated coconut + ½ cup panko",
      "canon": "coconut",
      "category": "Nuts & seeds",
      "staple": false
    },
    {
      "raw": "Oil spray, sweet chilli sauce to serve",
      "canon": "oil",
      "category": "Oils & fats",
      "staple": true
    }
  ],
  "airfryer-tandoori-prawns": [
    {
      "raw": "300 g large prawns, peeled and deveined",
      "canon": "prawn",
      "category": "Paneer & proteins",
      "staple": false
    },
    {
      "raw": "3 tbsp thick yogurt",
      "canon": "yogurt",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "1 tbsp ginger-garlic paste",
      "canon": "ginger garlic paste",
      "category": "Herbs & aromatics",
      "staple": false
    },
    {
      "raw": "1 tsp each: chilli powder, garam masala, cumin",
      "canon": "chilli powder",
      "category": "Spices & masalas",
      "staple": false
    },
    {
      "raw": "1 tsp besan + 1 tbsp lemon juice, salt",
      "canon": "besan",
      "category": "Flours & grains",
      "staple": false
    }
  ],
  "steamed-garlic-chilli-prawns": [
    {
      "raw": "300 g large prawns, peeled and butterflied",
      "canon": "prawn",
      "category": "Paneer & proteins",
      "staple": false
    },
    {
      "raw": "4 garlic cloves, minced",
      "canon": "garlic",
      "category": "Herbs & aromatics",
      "staple": false
    },
    {
      "raw": "1 red chilli, finely chopped",
      "canon": "chilli",
      "category": "Herbs & aromatics",
      "staple": false
    },
    {
      "raw": "1 tbsp soy sauce + 1 tsp sesame oil",
      "canon": "soy sauce",
      "category": "Condiments & sauces",
      "staple": false
    },
    {
      "raw": "Spring onion and coriander, to garnish",
      "canon": "spring onion",
      "category": "Herbs & aromatics",
      "staple": false
    }
  ],
  "steamed-khaman-dhokla": [
    {
      "raw": "1.5 cups besan (gram flour)",
      "canon": "besan",
      "category": "Flours & grains",
      "staple": false
    },
    {
      "raw": "1 tbsp semolina + 1 tsp sugar",
      "canon": "semolina",
      "category": "Flours & grains",
      "staple": false
    },
    {
      "raw": "1 tsp ginger-green chilli paste",
      "canon": "ginger green chilli paste",
      "category": "Herbs & aromatics",
      "staple": false
    },
    {
      "raw": "1 tsp eno fruit salt",
      "canon": "eno fruit salt",
      "category": "Baking & other",
      "staple": false
    },
    {
      "raw": "For tempering: mustard seeds, curry leaves, green chilli, 1 tsp sugar",
      "canon": "mustard seed",
      "category": "Spices & masalas",
      "staple": false
    },
    {
      "raw": "Salt, oil, coriander",
      "canon": "salt",
      "category": "Spices & masalas",
      "staple": true
    }
  ],
  "steamed-puttu": [
    {
      "raw": "2 cups roasted rice flour",
      "canon": "rice flour",
      "category": "Flours & grains",
      "staple": false
    },
    {
      "raw": "½ cup grated coconut",
      "canon": "coconut",
      "category": "Nuts & seeds",
      "staple": false
    },
    {
      "raw": "Salt and warm water",
      "canon": "salt",
      "category": "Spices & masalas",
      "staple": true
    },
    {
      "raw": "Banana and pappadam, to serve",
      "canon": "banana",
      "category": "Fruits",
      "staple": false
    }
  ],
  "steamed-gyeran-jjim": [
    {
      "raw": "4 eggs",
      "canon": "egg",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "¾ cup water or stock",
      "canon": "water",
      "category": "Baking & other",
      "staple": true
    },
    {
      "raw": "1 tsp sesame oil",
      "canon": "sesame oil",
      "category": "Oils & fats",
      "staple": false
    },
    {
      "raw": "1 chopped spring onion",
      "canon": "spring onion",
      "category": "Herbs & aromatics",
      "staple": false
    },
    {
      "raw": "Pinch of salt, toasted sesame seeds",
      "canon": "salt",
      "category": "Spices & masalas",
      "staple": true
    }
  ],
  "steamed-bao-buns": [
    {
      "raw": "8 ready bao bun wrappers (or homemade)",
      "canon": "wrapper",
      "category": "Baking & other",
      "staple": false
    },
    {
      "raw": "2 cups stir-fried mushrooms and cabbage",
      "canon": "mushroom",
      "category": "Vegetables",
      "staple": false
    },
    {
      "raw": "1 tbsp hoisin + 1 tsp soy sauce",
      "canon": "hoisin sauce",
      "category": "Condiments & sauces",
      "staple": false
    },
    {
      "raw": "Pickled carrot and cucumber",
      "canon": "carrot",
      "category": "Vegetables",
      "staple": false
    },
    {
      "raw": "Spring onion and crushed peanuts",
      "canon": "spring onion",
      "category": "Herbs & aromatics",
      "staple": false
    }
  ],
  "steamed-har-gow": [
    {
      "raw": "20 dumpling wrappers",
      "canon": "wrapper",
      "category": "Baking & other",
      "staple": false
    },
    {
      "raw": "300 g prawns, roughly chopped",
      "canon": "prawn",
      "category": "Paneer & proteins",
      "staple": false
    },
    {
      "raw": "2 tbsp chopped bamboo shoot or water chestnut",
      "canon": "bamboo shoot",
      "category": "Vegetables",
      "staple": false
    },
    {
      "raw": "1 tsp sesame oil + 1 tsp soy sauce",
      "canon": "sesame oil",
      "category": "Oils & fats",
      "staple": false
    },
    {
      "raw": "1 tsp grated ginger, pinch of sugar and salt",
      "canon": "ginger",
      "category": "Herbs & aromatics",
      "staple": false
    }
  ],
  "steamed-sticky-rice": [
    {
      "raw": "2 cups glutinous (sticky) rice, soaked 4 hours",
      "canon": "rice",
      "category": "Flours & grains",
      "staple": false
    },
    {
      "raw": "Water for the base",
      "canon": "water",
      "category": "Baking & other",
      "staple": true
    },
    {
      "raw": "Pinch of salt",
      "canon": "salt",
      "category": "Spices & masalas",
      "staple": true
    }
  ],
  "steamed-garlic-broccoli": [
    {
      "raw": "1 head broccoli, cut into florets",
      "canon": "broccoli",
      "category": "Vegetables",
      "staple": false
    },
    {
      "raw": "2 garlic cloves, minced",
      "canon": "garlic",
      "category": "Herbs & aromatics",
      "staple": false
    },
    {
      "raw": "1 tbsp olive oil or sesame oil",
      "canon": "olive oil",
      "category": "Oils & fats",
      "staple": false
    },
    {
      "raw": "1 tsp soy sauce or lemon juice",
      "canon": "soy sauce",
      "category": "Condiments & sauces",
      "staple": false
    },
    {
      "raw": "Salt, chilli flakes",
      "canon": "salt",
      "category": "Spices & masalas",
      "staple": true
    }
  ],
  "steamed-sweet-potato": [
    {
      "raw": "2 medium sweet potatoes, halved",
      "canon": "sweet potato",
      "category": "Vegetables",
      "staple": false
    },
    {
      "raw": "Flaky salt",
      "canon": "salt",
      "category": "Spices & masalas",
      "staple": true
    },
    {
      "raw": "Optional: butter or cinnamon",
      "canon": "butter",
      "category": "Dairy & eggs",
      "staple": false
    }
  ],
  "steamed-asparagus": [
    {
      "raw": "1 bunch asparagus, woody ends trimmed",
      "canon": "asparagus",
      "category": "Vegetables",
      "staple": false
    },
    {
      "raw": "1 tbsp olive oil",
      "canon": "olive oil",
      "category": "Oils & fats",
      "staple": false
    },
    {
      "raw": "1 tsp lemon zest + juice",
      "canon": "lemon",
      "category": "Fruits",
      "staple": false
    },
    {
      "raw": "Salt, black pepper, parmesan (optional)",
      "canon": "salt",
      "category": "Spices & masalas",
      "staple": true
    }
  ],
  "steamed-jasmine-rice": [
    {
      "raw": "1.5 cups jasmine rice, rinsed",
      "canon": "rice",
      "category": "Flours & grains",
      "staple": false
    },
    {
      "raw": "1.5 cups water",
      "canon": "water",
      "category": "Baking & other",
      "staple": true
    },
    {
      "raw": "Pinch of salt",
      "canon": "salt",
      "category": "Spices & masalas",
      "staple": true
    }
  ],
  "steamed-chocolate-pudding": [
    {
      "raw": "100 g butter, softened",
      "canon": "butter",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "100 g sugar",
      "canon": "sugar",
      "category": "Sweeteners",
      "staple": true
    },
    {
      "raw": "2 eggs",
      "canon": "egg",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "100 g flour + 2 tbsp cocoa",
      "canon": "flour",
      "category": "Flours & grains",
      "staple": false
    },
    {
      "raw": "1 tsp baking powder, splash of milk",
      "canon": "baking powder",
      "category": "Baking & other",
      "staple": false
    }
  ],
  "steamed-banana-cake": [
    {
      "raw": "2 ripe bananas, mashed",
      "canon": "banana",
      "category": "Fruits",
      "staple": false
    },
    {
      "raw": "120 g flour + 1 tsp baking powder",
      "canon": "flour",
      "category": "Flours & grains",
      "staple": false
    },
    {
      "raw": "60 g sugar",
      "canon": "sugar",
      "category": "Sweeteners",
      "staple": true
    },
    {
      "raw": "1 egg + 3 tbsp oil",
      "canon": "egg",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "½ tsp cinnamon",
      "canon": "cinnamon",
      "category": "Spices & masalas",
      "staple": false
    }
  ],
  "steamed-modak": [
    {
      "raw": "1 cup rice flour + 1 cup hot water",
      "canon": "rice flour",
      "category": "Flours & grains",
      "staple": false
    },
    {
      "raw": "For filling: 1 cup grated coconut + ½ cup jaggery",
      "canon": "coconut",
      "category": "Nuts & seeds",
      "staple": false
    },
    {
      "raw": "½ tsp cardamom",
      "canon": "cardamom",
      "category": "Spices & masalas",
      "staple": false
    },
    {
      "raw": "Ghee, pinch of salt",
      "canon": "ghee",
      "category": "Oils & fats",
      "staple": false
    }
  ],
  "airfryer-churros": [
    {
      "raw": "1 cup water + 2 tbsp butter",
      "canon": "water",
      "category": "Baking & other",
      "staple": true
    },
    {
      "raw": "1 cup flour",
      "canon": "flour",
      "category": "Flours & grains",
      "staple": false
    },
    {
      "raw": "1 egg",
      "canon": "egg",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "Cinnamon sugar, to coat",
      "canon": "cinnamon sugar",
      "category": "Sweeteners",
      "staple": false
    },
    {
      "raw": "Chocolate sauce, to serve",
      "canon": "chocolate sauce",
      "category": "Condiments & sauces",
      "staple": false
    }
  ],
  "airfryer-brownies": [
    {
      "raw": "100 g dark chocolate + 80 g butter, melted",
      "canon": "dark chocolate",
      "category": "Baking & other",
      "staple": false
    },
    {
      "raw": "120 g sugar",
      "canon": "sugar",
      "category": "Sweeteners",
      "staple": true
    },
    {
      "raw": "2 eggs",
      "canon": "egg",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "70 g flour + 2 tbsp cocoa",
      "canon": "flour",
      "category": "Flours & grains",
      "staple": false
    },
    {
      "raw": "Pinch of salt, handful of chocolate chips",
      "canon": "salt",
      "category": "Spices & masalas",
      "staple": true
    }
  ],
  "airfryer-choc-chip-cookies": [
    {
      "raw": "100 g butter, softened",
      "canon": "butter",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "80 g brown sugar + 40 g white sugar",
      "canon": "brown sugar",
      "category": "Sweeteners",
      "staple": false
    },
    {
      "raw": "1 egg",
      "canon": "egg",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "180 g flour + ½ tsp baking soda",
      "canon": "flour",
      "category": "Flours & grains",
      "staple": false
    },
    {
      "raw": "100 g chocolate chips",
      "canon": "chocolate chip",
      "category": "Baking & other",
      "staple": false
    }
  ],
  "airfryer-apple-hand-pies": [
    {
      "raw": "1 sheet puff or shortcrust pastry",
      "canon": "puff pastry",
      "category": "Baking & other",
      "staple": false
    },
    {
      "raw": "2 apples, diced",
      "canon": "apple",
      "category": "Fruits",
      "staple": false
    },
    {
      "raw": "2 tbsp sugar + 1 tsp cinnamon",
      "canon": "sugar",
      "category": "Sweeteners",
      "staple": true
    },
    {
      "raw": "1 tsp cornflour",
      "canon": "cornflour",
      "category": "Flours & grains",
      "staple": false
    },
    {
      "raw": "1 egg, beaten (to glaze)",
      "canon": "egg",
      "category": "Dairy & eggs",
      "staple": false
    }
  ],
  "airfryer-cinnamon-doughnuts": [
    {
      "raw": "1 can refrigerated biscuit dough (or homemade)",
      "canon": "dough",
      "category": "Baking & other",
      "staple": false
    },
    {
      "raw": "2 tbsp melted butter",
      "canon": "butter",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "½ cup sugar + 1 tbsp cinnamon",
      "canon": "sugar",
      "category": "Sweeteners",
      "staple": true
    }
  ],
  "steamed-thai-custard": [
    {
      "raw": "3 eggs",
      "canon": "egg",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "¾ cup coconut milk",
      "canon": "coconut milk",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "½ cup palm sugar or brown sugar",
      "canon": "sugar",
      "category": "Sweeteners",
      "staple": true
    },
    {
      "raw": "Pinch of salt",
      "canon": "salt",
      "category": "Spices & masalas",
      "staple": true
    },
    {
      "raw": "Steamed sticky rice, to serve",
      "canon": "rice",
      "category": "Flours & grains",
      "staple": false
    }
  ],
  "airfryer-french-fries": [
    {
      "raw": "3 large potatoes, cut into fries",
      "canon": "potato",
      "category": "Vegetables",
      "staple": false
    },
    {
      "raw": "1 tbsp oil",
      "canon": "oil",
      "category": "Oils & fats",
      "staple": true
    },
    {
      "raw": "1 tsp salt",
      "canon": "salt",
      "category": "Spices & masalas",
      "staple": true
    },
    {
      "raw": "½ tsp paprika or garlic powder",
      "canon": "paprika",
      "category": "Spices & masalas",
      "staple": false
    }
  ],
  "airfryer-onion-rings": [
    {
      "raw": "2 large onions, sliced into rings",
      "canon": "onion",
      "category": "Herbs & aromatics",
      "staple": false
    },
    {
      "raw": "½ cup flour",
      "canon": "flour",
      "category": "Flours & grains",
      "staple": false
    },
    {
      "raw": "1 egg, beaten",
      "canon": "egg",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "1 cup breadcrumbs (panko)",
      "canon": "breadcrumb",
      "category": "Baking & other",
      "staple": false
    },
    {
      "raw": "1 tsp paprika, salt, oil spray",
      "canon": "paprika",
      "category": "Spices & masalas",
      "staple": false
    }
  ],
  "airfryer-mozzarella-sticks": [
    {
      "raw": "8 mozzarella string cheese sticks",
      "canon": "mozzarella",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "½ cup flour",
      "canon": "flour",
      "category": "Flours & grains",
      "staple": false
    },
    {
      "raw": "1 egg, beaten",
      "canon": "egg",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "1 cup breadcrumbs + 1 tsp Italian herbs",
      "canon": "breadcrumb",
      "category": "Baking & other",
      "staple": false
    },
    {
      "raw": "Marinara sauce, to serve",
      "canon": "marinara sauce",
      "category": "Condiments & sauces",
      "staple": false
    }
  ],
  "airfryer-popcorn-chicken": [
    {
      "raw": "500 g chicken, cut into bite-size pieces",
      "canon": "chicken",
      "category": "Paneer & proteins",
      "staple": false
    },
    {
      "raw": "½ cup buttermilk",
      "canon": "buttermilk",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "1 cup seasoned flour",
      "canon": "flour",
      "category": "Flours & grains",
      "staple": false
    },
    {
      "raw": "1 tsp paprika + 1 tsp garlic powder",
      "canon": "paprika",
      "category": "Spices & masalas",
      "staple": false
    },
    {
      "raw": "Oil spray, salt",
      "canon": "oil",
      "category": "Oils & fats",
      "staple": true
    }
  ],
  "airfryer-masala-wedges": [
    {
      "raw": "3 potatoes, cut into wedges",
      "canon": "potato",
      "category": "Vegetables",
      "staple": false
    },
    {
      "raw": "1 tbsp oil",
      "canon": "oil",
      "category": "Oils & fats",
      "staple": true
    },
    {
      "raw": "1 tsp chilli powder + 1 tsp chaat masala",
      "canon": "chilli powder",
      "category": "Spices & masalas",
      "staple": false
    },
    {
      "raw": "½ tsp turmeric + ½ tsp cumin",
      "canon": "turmeric",
      "category": "Spices & masalas",
      "staple": false
    },
    {
      "raw": "Salt, coriander",
      "canon": "salt",
      "category": "Spices & masalas",
      "staple": true
    }
  ],
  "airfryer-roasted-chickpeas": [
    {
      "raw": "1 can chickpeas, drained and well dried",
      "canon": "chickpea",
      "category": "Lentils & pulses",
      "staple": false
    },
    {
      "raw": "1 tbsp olive oil",
      "canon": "oil",
      "category": "Oils & fats",
      "staple": true
    },
    {
      "raw": "1 tsp smoked paprika + ½ tsp cumin",
      "canon": "paprika",
      "category": "Spices & masalas",
      "staple": false
    },
    {
      "raw": "Salt, pinch of chilli",
      "canon": "salt",
      "category": "Spices & masalas",
      "staple": true
    }
  ],
  "airfryer-tortilla-chips": [
    {
      "raw": "6 corn tortillas, cut into triangles",
      "canon": "tortilla",
      "category": "Flours & grains",
      "staple": false
    },
    {
      "raw": "1 tbsp oil",
      "canon": "oil",
      "category": "Oils & fats",
      "staple": true
    },
    {
      "raw": "Salt + a squeeze of lime",
      "canon": "salt",
      "category": "Spices & masalas",
      "staple": true
    }
  ],
  "airfryer-plantain-chips": [
    {
      "raw": "2 raw green plantains, thinly sliced",
      "canon": "plantain",
      "category": "Fruits",
      "staple": false
    },
    {
      "raw": "1 tbsp oil",
      "canon": "oil",
      "category": "Oils & fats",
      "staple": true
    },
    {
      "raw": "Salt + a pinch of chilli or pepper",
      "canon": "salt",
      "category": "Spices & masalas",
      "staple": true
    }
  ],
  "airfryer-garlic-bread": [
    {
      "raw": "½ baguette, halved lengthwise",
      "canon": "bread",
      "category": "Flours & grains",
      "staple": false
    },
    {
      "raw": "3 tbsp soft butter",
      "canon": "butter",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "3 garlic cloves, minced",
      "canon": "garlic",
      "category": "Herbs & aromatics",
      "staple": false
    },
    {
      "raw": "Chopped parsley + pinch of salt",
      "canon": "parsley",
      "category": "Herbs & aromatics",
      "staple": false
    },
    {
      "raw": "Grated cheese (optional)",
      "canon": "cheese",
      "category": "Dairy & eggs",
      "staple": false
    }
  ],
  "airfryer-brussels-sprouts": [
    {
      "raw": "400 g Brussels sprouts, halved",
      "canon": "brussels sprout",
      "category": "Vegetables",
      "staple": false
    },
    {
      "raw": "1 tbsp olive oil",
      "canon": "olive oil",
      "category": "Oils & fats",
      "staple": false
    },
    {
      "raw": "1 tsp balsamic + 1 tsp honey",
      "canon": "balsamic vinegar",
      "category": "Condiments & sauces",
      "staple": false
    },
    {
      "raw": "Salt, pepper, chilli flakes",
      "canon": "salt",
      "category": "Spices & masalas",
      "staple": true
    }
  ],
  "airfryer-sweet-potato-fries": [
    {
      "raw": "2 sweet potatoes, cut into fries",
      "canon": "sweet potato",
      "category": "Vegetables",
      "staple": false
    },
    {
      "raw": "1 tbsp oil + 1 tbsp cornflour",
      "canon": "oil",
      "category": "Oils & fats",
      "staple": true
    },
    {
      "raw": "1 tsp paprika",
      "canon": "paprika",
      "category": "Spices & masalas",
      "staple": false
    },
    {
      "raw": "Salt, pepper",
      "canon": "salt",
      "category": "Spices & masalas",
      "staple": true
    }
  ],
  "airfryer-margherita-pizza": [
    {
      "raw": "1 small pizza base or flatbread",
      "canon": "pizza base",
      "category": "Baking & other",
      "staple": false
    },
    {
      "raw": "3 tbsp tomato sauce",
      "canon": "tomato sauce",
      "category": "Condiments & sauces",
      "staple": false
    },
    {
      "raw": "½ cup mozzarella",
      "canon": "mozzarella",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "Fresh basil",
      "canon": "basil",
      "category": "Herbs & aromatics",
      "staple": false
    },
    {
      "raw": "1 tsp olive oil, pinch of oregano",
      "canon": "olive oil",
      "category": "Oils & fats",
      "staple": false
    }
  ],
  "airfryer-arancini": [
    {
      "raw": "2 cups cold cooked risotto or rice",
      "canon": "rice",
      "category": "Flours & grains",
      "staple": false
    },
    {
      "raw": "½ cup mozzarella cubes",
      "canon": "mozzarella",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "½ cup flour, 1 egg, 1 cup breadcrumbs",
      "canon": "flour",
      "category": "Flours & grains",
      "staple": false
    },
    {
      "raw": "2 tbsp parmesan",
      "canon": "parmesan",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "Oil spray, salt",
      "canon": "oil",
      "category": "Oils & fats",
      "staple": true
    }
  ],
  "airfryer-eggplant-parmesan": [
    {
      "raw": "1 large aubergine, sliced into rounds",
      "canon": "aubergine",
      "category": "Vegetables",
      "staple": false
    },
    {
      "raw": "½ cup flour, 1 egg, 1 cup herby breadcrumbs",
      "canon": "flour",
      "category": "Flours & grains",
      "staple": false
    },
    {
      "raw": "1 cup marinara",
      "canon": "marinara sauce",
      "category": "Condiments & sauces",
      "staple": false
    },
    {
      "raw": "1 cup mozzarella + parmesan",
      "canon": "mozzarella",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "Salt, basil",
      "canon": "salt",
      "category": "Spices & masalas",
      "staple": true
    }
  ],
  "airfryer-spinach-calzone": [
    {
      "raw": "1 ball pizza dough",
      "canon": "dough",
      "category": "Baking & other",
      "staple": false
    },
    {
      "raw": "1 cup chopped spinach",
      "canon": "spinach",
      "category": "Vegetables",
      "staple": false
    },
    {
      "raw": "½ cup ricotta + ½ cup mozzarella",
      "canon": "ricotta",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "2 tbsp marinara",
      "canon": "marinara sauce",
      "category": "Condiments & sauces",
      "staple": false
    },
    {
      "raw": "1 egg (to glaze), salt, pepper",
      "canon": "egg",
      "category": "Dairy & eggs",
      "staple": false
    }
  ],
  "airfryer-korean-fried-chicken": [
    {
      "raw": "700 g chicken wings or boneless thighs",
      "canon": "chicken",
      "category": "Paneer & proteins",
      "staple": false
    },
    {
      "raw": "3 tbsp cornflour",
      "canon": "cornflour",
      "category": "Flours & grains",
      "staple": false
    },
    {
      "raw": "For sauce: 2 tbsp gochujang, 2 tbsp honey, 1 tbsp soy, 2 garlic cloves",
      "canon": "gochujang",
      "category": "Condiments & sauces",
      "staple": false
    },
    {
      "raw": "1 tsp sesame oil",
      "canon": "sesame oil",
      "category": "Oils & fats",
      "staple": false
    },
    {
      "raw": "Sesame seeds, spring onion",
      "canon": "sesame seed",
      "category": "Nuts & seeds",
      "staple": false
    }
  ],
  "airfryer-gochujang-tofu": [
    {
      "raw": "400 g firm tofu, pressed and cubed",
      "canon": "tofu",
      "category": "Paneer & proteins",
      "staple": false
    },
    {
      "raw": "1 tbsp cornflour + 1 tbsp oil",
      "canon": "cornflour",
      "category": "Flours & grains",
      "staple": false
    },
    {
      "raw": "For sauce: 1.5 tbsp gochujang, 1 tbsp maple syrup, 1 tsp soy, 1 garlic clove",
      "canon": "gochujang",
      "category": "Condiments & sauces",
      "staple": false
    },
    {
      "raw": "Sesame seeds, spring onion",
      "canon": "sesame seed",
      "category": "Nuts & seeds",
      "staple": false
    }
  ],
  "airfryer-chicken-taquitos": [
    {
      "raw": "2 cups shredded cooked chicken",
      "canon": "chicken",
      "category": "Paneer & proteins",
      "staple": false
    },
    {
      "raw": "½ cup cream cheese + ½ cup grated cheese",
      "canon": "cream cheese",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "1 tsp cumin + 1 tsp paprika",
      "canon": "cumin",
      "category": "Spices & masalas",
      "staple": false
    },
    {
      "raw": "10 small tortillas",
      "canon": "tortilla",
      "category": "Flours & grains",
      "staple": false
    },
    {
      "raw": "Oil spray, salt",
      "canon": "oil",
      "category": "Oils & fats",
      "staple": true
    }
  ],
  "airfryer-cheese-quesadilla": [
    {
      "raw": "2 tortillas",
      "canon": "tortilla",
      "category": "Flours & grains",
      "staple": false
    },
    {
      "raw": "1 cup grated cheese",
      "canon": "cheese",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "¼ cup corn and beans",
      "canon": "corn",
      "category": "Vegetables",
      "staple": false
    },
    {
      "raw": "Pinch of cumin and chilli",
      "canon": "cumin",
      "category": "Spices & masalas",
      "staple": false
    },
    {
      "raw": "Salsa, to serve",
      "canon": "salsa",
      "category": "Condiments & sauces",
      "staple": false
    }
  ],
  "airfryer-elote": [
    {
      "raw": "2 corn cobs",
      "canon": "corn",
      "category": "Vegetables",
      "staple": false
    },
    {
      "raw": "2 tbsp mayo + 1 tbsp sour cream",
      "canon": "mayonnaise",
      "category": "Condiments & sauces",
      "staple": false
    },
    {
      "raw": "¼ cup crumbled feta or cotija",
      "canon": "feta",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "1 tsp chilli powder + lime",
      "canon": "chilli powder",
      "category": "Spices & masalas",
      "staple": false
    },
    {
      "raw": "Coriander",
      "canon": "coriander",
      "category": "Herbs & aromatics",
      "staple": false
    }
  ],
  "airfryer-thai-fish-cakes": [
    {
      "raw": "400 g white fish, minced",
      "canon": "fish",
      "category": "Paneer & proteins",
      "staple": false
    },
    {
      "raw": "1 tbsp red curry paste",
      "canon": "red curry paste",
      "category": "Condiments & sauces",
      "staple": false
    },
    {
      "raw": "1 tsp fish sauce",
      "canon": "fish sauce",
      "category": "Condiments & sauces",
      "staple": false
    },
    {
      "raw": "2 green beans, finely sliced",
      "canon": "green bean",
      "category": "Vegetables",
      "staple": false
    },
    {
      "raw": "Kaffir lime leaf, oil spray",
      "canon": "kaffir lime leaf",
      "category": "Herbs & aromatics",
      "staple": false
    }
  ],
  "airfryer-chicken-satay": [
    {
      "raw": "500 g chicken thigh strips",
      "canon": "chicken",
      "category": "Paneer & proteins",
      "staple": false
    },
    {
      "raw": "½ cup coconut milk + 1 tbsp curry powder",
      "canon": "coconut milk",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "1 tbsp soy + 1 tsp turmeric",
      "canon": "soy sauce",
      "category": "Condiments & sauces",
      "staple": false
    },
    {
      "raw": "For sauce: peanut butter, soy, lime, chilli",
      "canon": "peanut butter",
      "category": "Condiments & sauces",
      "staple": false
    },
    {
      "raw": "Skewers",
      "canon": "skewer",
      "category": "Baking & other",
      "staple": true
    }
  ],
  "airfryer-tandoori-aloo": [
    {
      "raw": "4 baby potatoes, parboiled and halved",
      "canon": "potato",
      "category": "Vegetables",
      "staple": false
    },
    {
      "raw": "3 tbsp thick yogurt",
      "canon": "yogurt",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "1 tbsp tandoori masala + 1 tsp chilli powder",
      "canon": "tandoori masala",
      "category": "Spices & masalas",
      "staple": false
    },
    {
      "raw": "1 tsp ginger-garlic paste",
      "canon": "ginger garlic paste",
      "category": "Herbs & aromatics",
      "staple": false
    },
    {
      "raw": "1 tbsp besan, oil, salt",
      "canon": "besan",
      "category": "Flours & grains",
      "staple": false
    }
  ],
  "airfryer-masala-vada": [
    {
      "raw": "1 cup chana dal, soaked 2 hours",
      "canon": "chana dal",
      "category": "Lentils & pulses",
      "staple": false
    },
    {
      "raw": "1 onion + 2 green chillies, chopped",
      "canon": "onion",
      "category": "Herbs & aromatics",
      "staple": false
    },
    {
      "raw": "Curry leaves, fennel seeds",
      "canon": "curry leaf",
      "category": "Herbs & aromatics",
      "staple": false
    },
    {
      "raw": "Ginger, salt, coriander",
      "canon": "ginger",
      "category": "Herbs & aromatics",
      "staple": false
    },
    {
      "raw": "Oil spray",
      "canon": "oil",
      "category": "Oils & fats",
      "staple": true
    }
  ],
  "steamed-patra": [
    {
      "raw": "8 colocasia (arbi) leaves",
      "canon": "colocasia leaf",
      "category": "Vegetables",
      "staple": false
    },
    {
      "raw": "1.5 cups besan",
      "canon": "besan",
      "category": "Flours & grains",
      "staple": false
    },
    {
      "raw": "2 tbsp tamarind + 1 tbsp jaggery",
      "canon": "tamarind",
      "category": "Condiments & sauces",
      "staple": false
    },
    {
      "raw": "1 tsp each chilli, turmeric, coriander powder",
      "canon": "chilli powder",
      "category": "Spices & masalas",
      "staple": false
    },
    {
      "raw": "For tempering: mustard and sesame seeds",
      "canon": "mustard seed",
      "category": "Spices & masalas",
      "staple": false
    }
  ],
  "airfryer-stuffed-mirchi": [
    {
      "raw": "6 large mild chillies (bhavnagri), slit",
      "canon": "chilli",
      "category": "Herbs & aromatics",
      "staple": false
    },
    {
      "raw": "1 cup mashed spiced potato",
      "canon": "potato",
      "category": "Vegetables",
      "staple": false
    },
    {
      "raw": "1 tsp chaat masala + ½ tsp amchur",
      "canon": "chaat masala",
      "category": "Spices & masalas",
      "staple": false
    },
    {
      "raw": "2 tbsp besan + oil spray",
      "canon": "besan",
      "category": "Flours & grains",
      "staple": false
    },
    {
      "raw": "Salt",
      "canon": "salt",
      "category": "Spices & masalas",
      "staple": true
    }
  ],
  "airfryer-egg-muffins": [
    {
      "raw": "4 eggs",
      "canon": "egg",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "¼ cup chopped peppers, spinach, onion",
      "canon": "pepper",
      "category": "Spices & masalas",
      "staple": false
    },
    {
      "raw": "¼ cup grated cheese",
      "canon": "cheese",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "Salt, pepper",
      "canon": "salt",
      "category": "Spices & masalas",
      "staple": true
    },
    {
      "raw": "Silicone muffin cups",
      "canon": "silicone muffin cup",
      "category": "Baking & other",
      "staple": true
    }
  ],
  "airfryer-granola": [
    {
      "raw": "2 cups rolled oats",
      "canon": "oat",
      "category": "Flours & grains",
      "staple": false
    },
    {
      "raw": "½ cup mixed nuts and seeds",
      "canon": "nut",
      "category": "Nuts & seeds",
      "staple": false
    },
    {
      "raw": "3 tbsp maple syrup + 2 tbsp oil",
      "canon": "maple syrup",
      "category": "Sweeteners",
      "staple": false
    },
    {
      "raw": "1 tsp cinnamon, pinch of salt",
      "canon": "cinnamon",
      "category": "Spices & masalas",
      "staple": false
    },
    {
      "raw": "Dried fruit, to finish",
      "canon": "dried fruit",
      "category": "Fruits",
      "staple": false
    }
  ],
  "airfryer-breakfast-potatoes": [
    {
      "raw": "3 potatoes, diced",
      "canon": "potato",
      "category": "Vegetables",
      "staple": false
    },
    {
      "raw": "1 tbsp oil",
      "canon": "oil",
      "category": "Oils & fats",
      "staple": true
    },
    {
      "raw": "1 tsp paprika + ½ tsp garlic powder",
      "canon": "paprika",
      "category": "Spices & masalas",
      "staple": false
    },
    {
      "raw": "½ onion, diced",
      "canon": "onion",
      "category": "Herbs & aromatics",
      "staple": false
    },
    {
      "raw": "Salt, pepper",
      "canon": "salt",
      "category": "Spices & masalas",
      "staple": true
    }
  ],
  "airfryer-banana-bread": [
    {
      "raw": "3 ripe bananas, mashed",
      "canon": "banana",
      "category": "Fruits",
      "staple": false
    },
    {
      "raw": "150 g flour + 1 tsp baking soda",
      "canon": "flour",
      "category": "Flours & grains",
      "staple": false
    },
    {
      "raw": "80 g sugar",
      "canon": "sugar",
      "category": "Sweeteners",
      "staple": true
    },
    {
      "raw": "1 egg + 4 tbsp oil",
      "canon": "egg",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "½ tsp cinnamon, pinch of salt",
      "canon": "cinnamon",
      "category": "Spices & masalas",
      "staple": false
    }
  ],
  "steamed-chicken-congee": [
    {
      "raw": "½ cup rice",
      "canon": "rice",
      "category": "Flours & grains",
      "staple": false
    },
    {
      "raw": "4 cups water or stock",
      "canon": "water",
      "category": "Baking & other",
      "staple": true
    },
    {
      "raw": "1 chicken breast",
      "canon": "chicken",
      "category": "Paneer & proteins",
      "staple": false
    },
    {
      "raw": "1 tsp grated ginger",
      "canon": "ginger",
      "category": "Herbs & aromatics",
      "staple": false
    },
    {
      "raw": "Spring onion, soy sauce, white pepper",
      "canon": "spring onion",
      "category": "Herbs & aromatics",
      "staple": false
    }
  ],
  "airfryer-bang-bang-salmon": [
    {
      "raw": "400 g salmon, cut into cubes",
      "canon": "salmon",
      "category": "Paneer & proteins",
      "staple": false
    },
    {
      "raw": "1 tbsp oil + 1 tsp paprika, salt, pepper",
      "canon": "oil",
      "category": "Oils & fats",
      "staple": true
    },
    {
      "raw": "For bang bang sauce: 3 tbsp mayo",
      "canon": "mayonnaise",
      "category": "Condiments & sauces",
      "staple": false
    },
    {
      "raw": "2 tbsp sweet chilli sauce",
      "canon": "sweet chilli sauce",
      "category": "Condiments & sauces",
      "staple": false
    },
    {
      "raw": "1 tsp sriracha + 1 tsp honey",
      "canon": "sriracha",
      "category": "Condiments & sauces",
      "staple": false
    }
  ],
  "airfryer-bang-bang-chicken": [
    {
      "raw": "500 g chicken breast, cubed",
      "canon": "chicken",
      "category": "Paneer & proteins",
      "staple": false
    },
    {
      "raw": "½ cup cornflour + 1 egg",
      "canon": "cornflour",
      "category": "Flours & grains",
      "staple": false
    },
    {
      "raw": "1 tsp garlic powder + paprika, salt",
      "canon": "garlic powder",
      "category": "Spices & masalas",
      "staple": false
    },
    {
      "raw": "For sauce: 4 tbsp mayo + 3 tbsp sweet chilli",
      "canon": "mayonnaise",
      "category": "Condiments & sauces",
      "staple": false
    },
    {
      "raw": "1–2 tsp sriracha, oil spray",
      "canon": "sriracha",
      "category": "Condiments & sauces",
      "staple": false
    }
  ],
  "airfryer-pasta-chips": [
    {
      "raw": "2 cups cooked penne or bowtie pasta",
      "canon": "pasta",
      "category": "Flours & grains",
      "staple": false
    },
    {
      "raw": "1 tbsp olive oil",
      "canon": "olive oil",
      "category": "Oils & fats",
      "staple": false
    },
    {
      "raw": "3 tbsp grated parmesan",
      "canon": "parmesan",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "1 tsp Italian herbs + 1 tsp garlic powder",
      "canon": "italian herb",
      "category": "Spices & masalas",
      "staple": false
    },
    {
      "raw": "Salt, marinara to dip",
      "canon": "salt",
      "category": "Spices & masalas",
      "staple": true
    }
  ],
  "airfryer-corn-ribs": [
    {
      "raw": "2 corn cobs, quartered lengthwise into \"ribs\"",
      "canon": "corn",
      "category": "Vegetables",
      "staple": false
    },
    {
      "raw": "1 tbsp melted butter or oil",
      "canon": "butter",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "1 tsp paprika + ½ tsp garlic powder",
      "canon": "paprika",
      "category": "Spices & masalas",
      "staple": false
    },
    {
      "raw": "Salt, chilli flakes",
      "canon": "salt",
      "category": "Spices & masalas",
      "staple": true
    },
    {
      "raw": "Lime and coriander, to finish",
      "canon": "lime",
      "category": "Fruits",
      "staple": false
    }
  ],
  "airfryer-baked-feta-pasta": [
    {
      "raw": "1 block feta",
      "canon": "feta",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "2 cups cherry tomatoes",
      "canon": "cherry tomato",
      "category": "Vegetables",
      "staple": false
    },
    {
      "raw": "2 tbsp olive oil + 2 garlic cloves",
      "canon": "olive oil",
      "category": "Oils & fats",
      "staple": false
    },
    {
      "raw": "Salt, pepper, chilli flakes, basil",
      "canon": "salt",
      "category": "Spices & masalas",
      "staple": true
    },
    {
      "raw": "250 g pasta, cooked",
      "canon": "pasta",
      "category": "Flours & grains",
      "staple": false
    }
  ],
  "airfryer-creme-brulee": [
    {
      "raw": "4 egg yolks",
      "canon": "egg",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "1 cup cream",
      "canon": "cream",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "3 tbsp sugar + 1 tsp vanilla",
      "canon": "sugar",
      "category": "Sweeteners",
      "staple": true
    },
    {
      "raw": "Extra sugar, to caramelise",
      "canon": "sugar",
      "category": "Sweeteners",
      "staple": true
    }
  ],
  "airfryer-nutella-toast-pies": [
    {
      "raw": "4 slices soft bread",
      "canon": "bread",
      "category": "Flours & grains",
      "staple": false
    },
    {
      "raw": "4 tbsp Nutella",
      "canon": "nutella",
      "category": "Condiments & sauces",
      "staple": false
    },
    {
      "raw": "1 tbsp melted butter",
      "canon": "butter",
      "category": "Dairy & eggs",
      "staple": false
    },
    {
      "raw": "Icing sugar, to dust",
      "canon": "icing sugar",
      "category": "Sweeteners",
      "staple": false
    }
  ],
  "airfryer-soy-chicken-thighs": [
    {
      "raw": "6 bone-in chicken thighs",
      "canon": "chicken",
      "category": "Paneer & proteins",
      "staple": false
    },
    {
      "raw": "3 tbsp soy sauce + 1 tbsp dark soy",
      "canon": "soy sauce",
      "category": "Condiments & sauces",
      "staple": false
    },
    {
      "raw": "3 garlic cloves + 1 tsp five-spice",
      "canon": "garlic",
      "category": "Herbs & aromatics",
      "staple": false
    },
    {
      "raw": "1 tbsp sugar + ½ tsp white pepper",
      "canon": "sugar",
      "category": "Sweeteners",
      "staple": true
    },
    {
      "raw": "Spring onion",
      "canon": "spring onion",
      "category": "Herbs & aromatics",
      "staple": false
    }
  ],
  "airfryer-smashed-potatoes": [
    {
      "raw": "8 baby potatoes",
      "canon": "potato",
      "category": "Vegetables",
      "staple": false
    },
    {
      "raw": "2 tbsp olive oil",
      "canon": "olive oil",
      "category": "Oils & fats",
      "staple": false
    },
    {
      "raw": "2 garlic cloves, minced",
      "canon": "garlic",
      "category": "Herbs & aromatics",
      "staple": false
    },
    {
      "raw": "Rosemary or herbs, salt, pepper",
      "canon": "rosemary",
      "category": "Herbs & aromatics",
      "staple": false
    },
    {
      "raw": "Grated parmesan (optional)",
      "canon": "parmesan",
      "category": "Dairy & eggs",
      "staple": false
    }
  ],
  "steamed-soup-dumplings": [
    {
      "raw": "24 dumpling wrappers",
      "canon": "wrapper",
      "category": "Baking & other",
      "staple": false
    },
    {
      "raw": "300 g pork mince",
      "canon": "pork",
      "category": "Paneer & proteins",
      "staple": false
    },
    {
      "raw": "1 cup set jellied stock, diced (the \"soup\")",
      "canon": "stock",
      "category": "Condiments & sauces",
      "staple": false
    },
    {
      "raw": "1 tbsp soy + 1 tsp sesame oil + 1 tsp ginger",
      "canon": "soy sauce",
      "category": "Condiments & sauces",
      "staple": false
    },
    {
      "raw": "Spring onion, black vinegar to dip",
      "canon": "spring onion",
      "category": "Herbs & aromatics",
      "staple": false
    }
  ]
}
