// Foodiee recipe data
// -------------------
// Every recipe here is designed for ONE of the two appliances we own:
//   - "airfryer"  -> Philips Airfryer (RapidAir, dial model). Temps in °C.
//   - "steamer"   -> Wipro Multi Cooker / Egg Boiler (multi-tier steamer). Times in minutes.
//
// Each recipe is tagged with one or more meals: 'breakfast' | 'lunch' | 'dinner'.
// Times are total (prep + cook) in minutes. Difficulty: 'Easy' | 'Medium'.

export const APPLIANCES = {
  airfryer: { label: 'Air Fryer', emoji: '🌀', full: 'Philips Airfryer' },
  steamer: { label: 'Steamer / Egg Boiler', emoji: '♨️', full: 'Wipro Multi Cooker' },
}

export const MEALS = {
  breakfast: { label: 'Breakfast', emoji: '🌅' },
  lunch: { label: 'Lunch', emoji: '☀️' },
  dinner: { label: 'Dinner', emoji: '🌙' },
}

export const recipes = [
  // ---------------------------- BREAKFAST ----------------------------
  {
    id: 'soft-boiled-eggs',
    title: 'Perfect Soft-Boiled Eggs',
    emoji: '🥚',
    color: '#ffd166',
    meals: ['breakfast'],
    appliance: 'steamer',
    cuisine: 'Global',
    time: 15,
    difficulty: 'Easy',
    servings: '2–6 eggs',
    setting: 'Steam ~12 min for soft, ~15 min for hard',
    ingredients: [
      'Up to 6 eggs',
      'Measuring cup of water (use the marking for your desired doneness)',
      'Pinch of salt and pepper, to serve',
    ],
    steps: [
      'Add water to the base using the measuring cup — less water for soft, more for hard-boiled.',
      'Pierce the wider end of each egg with the pin on the measuring cup to stop cracking.',
      'Place eggs in the egg tray, pointed side down. Cover with the lid.',
      'Switch on; the cooker beeps and shuts off when the water has fully evaporated.',
      'Plunge eggs into cold water for 1 minute, then peel. Season and serve.',
    ],
    tags: ['high-protein', 'meal-prep', 'vegetarian'],
  },
  {
    id: 'airfryer-french-toast',
    title: 'Air Fryer French Toast Sticks',
    emoji: '🍞',
    color: '#f4a261',
    meals: ['breakfast'],
    appliance: 'airfryer',
    cuisine: 'American',
    time: 15,
    difficulty: 'Easy',
    servings: '2',
    setting: '180°C · 8–10 min',
    ingredients: [
      '4 thick slices of bread, cut into 3 sticks each',
      '2 eggs',
      '60 ml milk',
      '1 tsp cinnamon',
      '1 tsp vanilla',
      'Maple syrup, to serve',
    ],
    steps: [
      'Whisk eggs, milk, cinnamon and vanilla in a shallow bowl.',
      'Dip each bread stick briefly on all sides — do not soak.',
      'Preheat the air fryer to 180°C for 2 minutes.',
      'Arrange sticks in a single layer (cook in batches if needed). Air fry 8–10 min, flipping halfway, until golden.',
      'Dust with extra cinnamon and serve with maple syrup.',
    ],
    tags: ['kid-friendly', 'vegetarian', 'quick'],
  },
  {
    id: 'steamed-idli',
    title: 'Steamed Idli',
    emoji: '⚪',
    color: '#e9edc9',
    meals: ['breakfast'],
    appliance: 'steamer',
    cuisine: 'Indian',
    time: 20,
    difficulty: 'Easy',
    servings: '2–3',
    setting: 'Steam 10–12 min',
    ingredients: [
      '2 cups fermented idli batter',
      'Oil or ghee, to grease',
      'Coconut chutney and sambar, to serve',
    ],
    steps: [
      'Lightly grease the steamer tray cups (use an idli plate if it fits, or small silicone moulds).',
      'Pour batter into each mould, filling about ¾ full.',
      'Add water to the base, place the tray, cover and steam 10–12 minutes.',
      'Check with a toothpick — it should come out clean. Rest 2 minutes before unmoulding.',
      'Serve hot with coconut chutney and sambar.',
    ],
    tags: ['vegetarian', 'vegan', 'light'],
  },
  {
    id: 'airfryer-hash-browns',
    title: 'Crispy Air Fryer Hash Browns',
    emoji: '🥔',
    color: '#e9c46a',
    meals: ['breakfast'],
    appliance: 'airfryer',
    cuisine: 'American',
    time: 25,
    difficulty: 'Medium',
    servings: '2',
    setting: '190°C · 14–16 min',
    ingredients: [
      '2 large potatoes, grated',
      '1 tbsp cornflour',
      '½ tsp salt',
      '¼ tsp black pepper',
      '½ tsp paprika',
      '1 tbsp oil',
    ],
    steps: [
      'Squeeze the grated potato in a cloth to remove as much water as possible.',
      'Mix with cornflour, salt, pepper, paprika and oil. Press into flat patties.',
      'Preheat air fryer to 190°C. Lightly brush the basket.',
      'Air fry patties 14–16 min, flipping once, until deep golden and crisp.',
      'Season with extra salt and serve immediately.',
    ],
    tags: ['vegetarian', 'crispy', 'vegan'],
  },
  {
    id: 'steamed-veg-momos',
    title: 'Steamed Vegetable Momos',
    emoji: '🥟',
    color: '#cdb4db',
    meals: ['breakfast', 'lunch'],
    appliance: 'steamer',
    cuisine: 'Tibetan / Nepali',
    time: 35,
    difficulty: 'Medium',
    servings: '3',
    setting: 'Steam 12–14 min',
    ingredients: [
      '20 momo wrappers',
      '2 cups finely shredded cabbage',
      '1 carrot, grated',
      '2 spring onions, chopped',
      '1 tbsp soy sauce',
      '1 tsp grated ginger + garlic',
      'Salt and pepper',
    ],
    steps: [
      'Stir-fry the vegetables with ginger-garlic, soy sauce, salt and pepper for 2 minutes; cool.',
      'Place a spoon of filling in each wrapper and pleat to seal.',
      'Lightly oil the steamer tray so momos don’t stick.',
      'Add water to the base and steam 12–14 minutes until the wrappers turn glossy.',
      'Serve hot with spicy tomato-garlic chutney.',
    ],
    tags: ['vegetarian', 'vegan', 'street-food'],
  },

  // ---------------------------- LUNCH ----------------------------
  {
    id: 'airfryer-paneer-tikka',
    title: 'Air Fryer Paneer Tikka',
    emoji: '🧆',
    color: '#e76f51',
    meals: ['lunch', 'dinner'],
    appliance: 'airfryer',
    cuisine: 'Indian',
    time: 35,
    difficulty: 'Easy',
    servings: '3',
    setting: '200°C · 10–12 min',
    ingredients: [
      '250 g paneer, cubed',
      '1 capsicum + 1 onion, in chunks',
      '4 tbsp thick yogurt',
      '1 tbsp ginger-garlic paste',
      '1 tsp each: chilli powder, garam masala, cumin',
      '1 tbsp besan (gram flour)',
      '1 tbsp oil, salt',
    ],
    steps: [
      'Whisk yogurt with all spices, besan, oil and salt into a thick marinade.',
      'Fold in paneer and vegetables; marinate at least 20 minutes.',
      'Preheat air fryer to 200°C. Thread onto skewers or lay flat in the basket.',
      'Air fry 10–12 min, turning once, until charred at the edges.',
      'Finish with lemon juice and chaat masala.',
    ],
    tags: ['vegetarian', 'high-protein', 'party'],
  },
  {
    id: 'steamed-lemon-fish',
    title: 'Steamed Lemon-Herb Fish',
    emoji: '🐟',
    color: '#a8dadc',
    meals: ['lunch', 'dinner'],
    appliance: 'steamer',
    cuisine: 'Mediterranean',
    time: 25,
    difficulty: 'Easy',
    servings: '2',
    setting: 'Steam 12–15 min',
    ingredients: [
      '2 white fish fillets (basa, tilapia or cod)',
      '1 lemon, half sliced + half juiced',
      '2 cloves garlic, minced',
      'A few sprigs of dill or parsley',
      '1 tbsp olive oil, salt and pepper',
    ],
    steps: [
      'Pat the fish dry and season both sides with salt, pepper and garlic.',
      'Lay lemon slices on the steamer tray and place the fish on top so it doesn’t stick.',
      'Drizzle with olive oil and scatter the herbs.',
      'Add water to the base and steam 12–15 minutes, until the fish flakes easily.',
      'Finish with a squeeze of fresh lemon juice.',
    ],
    tags: ['high-protein', 'low-carb', 'light', 'pescatarian'],
  },
  {
    id: 'airfryer-falafel',
    title: 'Air Fryer Falafel',
    emoji: '🧇',
    color: '#90a955',
    meals: ['lunch'],
    appliance: 'airfryer',
    cuisine: 'Middle Eastern',
    time: 30,
    difficulty: 'Medium',
    servings: '3',
    setting: '190°C · 14–16 min',
    ingredients: [
      '1½ cups soaked (not cooked) chickpeas',
      '1 small onion + 3 garlic cloves',
      'Handful of parsley and coriander',
      '1 tsp cumin, 1 tsp coriander powder',
      '2 tbsp besan, salt',
      'Oil spray',
    ],
    steps: [
      'Blitz everything except the oil into a coarse paste — do not over-blend.',
      'Rest 15 minutes, then shape into small patties.',
      'Preheat air fryer to 190°C and spray patties with oil.',
      'Air fry 14–16 min, flipping once, until golden and crisp.',
      'Tuck into pita with hummus, salad and tahini.',
    ],
    tags: ['vegan', 'vegetarian', 'high-protein'],
  },
  {
    id: 'steamed-veg-rice-bowl',
    title: 'Steamed Veg & Rice Bowl',
    emoji: '🍚',
    color: '#bde0fe',
    meals: ['lunch', 'dinner'],
    appliance: 'steamer',
    cuisine: 'Asian',
    time: 30,
    difficulty: 'Easy',
    servings: '2',
    setting: 'Steam rice ~25 min · veg last 10 min',
    ingredients: [
      '1 cup rice + 1¼ cups water',
      'Broccoli, carrot and beans, chopped',
      '1 tbsp soy sauce',
      '1 tsp sesame oil',
      '1 tsp toasted sesame seeds',
    ],
    steps: [
      'Add rice and water to the base bowl of the multi cooker.',
      'Steam for about 15 minutes, then add the vegetables to the upper tray.',
      'Continue steaming 10 minutes until the rice is fluffy and veg is tender-crisp.',
      'Toss the vegetables with soy sauce and sesame oil.',
      'Spoon rice into bowls, top with veg and sprinkle sesame seeds.',
    ],
    tags: ['vegan', 'vegetarian', 'meal-prep', 'one-pot'],
  },
  {
    id: 'airfryer-stuffed-peppers',
    title: 'Air Fryer Stuffed Peppers',
    emoji: '🫑',
    color: '#80b918',
    meals: ['lunch', 'dinner'],
    appliance: 'airfryer',
    cuisine: 'Tex-Mex',
    time: 35,
    difficulty: 'Medium',
    servings: '2',
    setting: '180°C · 15–18 min',
    ingredients: [
      '4 bell peppers, tops cut and seeded',
      '1 cup cooked rice or quinoa',
      '½ cup black beans or corn',
      '½ cup grated cheese',
      '1 tsp cumin + 1 tsp paprika',
      'Salt, pepper, coriander',
    ],
    steps: [
      'Mix rice, beans, half the cheese and the spices for the filling.',
      'Stuff the peppers and top with the remaining cheese.',
      'Preheat air fryer to 180°C.',
      'Air fry 15–18 min until the peppers are tender and the cheese is bubbling.',
      'Garnish with coriander and a dollop of yogurt or sour cream.',
    ],
    tags: ['vegetarian', 'gluten-free', 'comfort'],
  },

  // ---------------------------- DINNER ----------------------------
  {
    id: 'airfryer-chicken-wings',
    title: 'Crispy Air Fryer Chicken Wings',
    emoji: '🍗',
    color: '#bc6c25',
    meals: ['dinner'],
    appliance: 'airfryer',
    cuisine: 'American',
    time: 35,
    difficulty: 'Easy',
    servings: '3',
    setting: '200°C · 18–22 min',
    ingredients: [
      '700 g chicken wings, patted dry',
      '1 tbsp baking powder (for crispness)',
      '1 tsp each: garlic powder, paprika, salt',
      '½ tsp black pepper',
      'Buffalo or BBQ sauce, to toss',
    ],
    steps: [
      'Toss wings with baking powder, garlic powder, paprika, salt and pepper.',
      'Preheat air fryer to 200°C.',
      'Arrange in a single layer and air fry 18–22 min, flipping every 7–8 minutes.',
      'Cook until deep golden and the skin is crackly.',
      'Toss in your sauce of choice and serve with a cooling dip.',
    ],
    tags: ['high-protein', 'crispy', 'party'],
  },
  {
    id: 'airfryer-veg-spring-rolls',
    title: 'Air Fryer Vegetable Spring Rolls',
    emoji: '🥢',
    color: '#fb8500',
    meals: ['dinner'],
    appliance: 'airfryer',
    cuisine: 'Chinese',
    time: 30,
    difficulty: 'Medium',
    servings: '3',
    setting: '190°C · 10–12 min',
    ingredients: [
      '12 spring roll wrappers',
      '3 cups shredded cabbage, carrot, capsicum',
      '1 tbsp soy sauce + 1 tsp vinegar',
      '1 tsp ginger-garlic paste',
      'Oil spray',
      'Flour-water paste, to seal',
    ],
    steps: [
      'Stir-fry the vegetables with ginger-garlic, soy and vinegar for 2 minutes; cool.',
      'Roll the filling tightly in wrappers, sealing edges with flour paste.',
      'Preheat air fryer to 190°C and spray rolls all over with oil.',
      'Air fry 10–12 min, turning once, until crisp and golden.',
      'Serve with sweet chilli or schezwan sauce.',
    ],
    tags: ['vegetarian', 'vegan', 'crispy', 'party'],
  },
  {
    id: 'steamed-dumpling-soup',
    title: 'Steamed Chicken & Veg Parcels',
    emoji: '🍱',
    color: '#ffb4a2',
    meals: ['dinner'],
    appliance: 'steamer',
    cuisine: 'Asian',
    time: 30,
    difficulty: 'Easy',
    servings: '2',
    setting: 'Steam 18–20 min',
    ingredients: [
      '2 chicken breasts, thinly sliced (or tofu for veg)',
      '1 tbsp soy sauce + 1 tsp honey',
      '1 tsp grated ginger',
      'Bok choy or spinach',
      'Spring onion, to garnish',
    ],
    steps: [
      'Marinate the chicken in soy, honey and ginger for 10 minutes.',
      'Lay the chicken on the steamer tray with the greens alongside.',
      'Add water to the base and steam 18–20 minutes until cooked through.',
      'Check the chicken is no longer pink at the thickest part.',
      'Garnish with spring onion and serve over rice or noodles.',
    ],
    tags: ['high-protein', 'low-carb', 'light'],
  },
  {
    id: 'airfryer-roasted-veg',
    title: 'Air Fryer Roasted Vegetables',
    emoji: '🥦',
    color: '#588157',
    meals: ['dinner', 'lunch'],
    appliance: 'airfryer',
    cuisine: 'Mediterranean',
    time: 25,
    difficulty: 'Easy',
    servings: '3',
    setting: '200°C · 12–15 min',
    ingredients: [
      '4 cups mixed veg (zucchini, peppers, onion, mushroom, cherry tomato)',
      '2 tbsp olive oil',
      '1 tsp Italian herbs',
      '2 cloves garlic, minced',
      'Salt, pepper, chilli flakes',
    ],
    steps: [
      'Toss all the vegetables with oil, herbs, garlic, salt and pepper.',
      'Preheat air fryer to 200°C.',
      'Air fry 12–15 min, shaking the basket halfway, until caramelised at the edges.',
      'Finish with chilli flakes and a squeeze of lemon.',
      'Serve as a side, over couscous, or stuffed into wraps.',
    ],
    tags: ['vegan', 'vegetarian', 'gluten-free', 'side'],
  },
  {
    id: 'airfryer-salmon',
    title: 'Air Fryer Honey-Garlic Salmon',
    emoji: '🍣',
    color: '#ef798a',
    meals: ['dinner'],
    appliance: 'airfryer',
    cuisine: 'Global',
    time: 20,
    difficulty: 'Easy',
    servings: '2',
    setting: '190°C · 8–10 min',
    ingredients: [
      '2 salmon fillets',
      '2 tbsp honey',
      '2 cloves garlic, minced',
      '1 tbsp soy sauce',
      '1 tsp lemon juice',
      'Salt and pepper',
    ],
    steps: [
      'Whisk honey, garlic, soy sauce and lemon juice into a glaze.',
      'Season the salmon and brush generously with the glaze.',
      'Preheat air fryer to 190°C and line the basket with a small piece of foil.',
      'Air fry 8–10 min, until the salmon flakes and the top is caramelised.',
      'Spoon over any extra glaze and serve with greens or rice.',
    ],
    tags: ['high-protein', 'pescatarian', 'quick', 'low-carb'],
  },
  {
    id: 'steamed-corn-edamame',
    title: 'Steamed Corn & Edamame Snack Bowl',
    emoji: '🌽',
    color: '#ffd60a',
    meals: ['dinner', 'lunch'],
    appliance: 'steamer',
    cuisine: 'Global',
    time: 15,
    difficulty: 'Easy',
    servings: '2',
    setting: 'Steam 10–12 min',
    ingredients: [
      '1 cup sweetcorn',
      '1 cup edamame (in pods or shelled)',
      '1 tbsp butter or olive oil',
      'Chilli-lime seasoning or chaat masala',
      'Flaky salt',
    ],
    steps: [
      'Add the corn and edamame to the steamer tray.',
      'Add water to the base and steam 10–12 minutes until tender.',
      'Toss the warm veg with butter or olive oil.',
      'Sprinkle with chilli-lime seasoning and flaky salt.',
      'Serve as a light dinner side or evening snack.',
    ],
    tags: ['vegetarian', 'vegan', 'quick', 'snack'],
  },

  // ---------------------------- CHICKEN ----------------------------
  {
    id: 'airfryer-tandoori-chicken',
    title: 'Air Fryer Tandoori Chicken',
    emoji: '🍗',
    color: '#d62828',
    meals: ['lunch', 'dinner'],
    appliance: 'airfryer',
    cuisine: 'Indian',
    time: 40,
    difficulty: 'Medium',
    servings: '3',
    setting: '200°C · 18–22 min',
    ingredients: [
      '6 bone-in chicken drumsticks or thighs, slashed',
      '5 tbsp thick yogurt',
      '1 tbsp ginger-garlic paste',
      '1 tbsp tandoori masala + 1 tsp chilli powder',
      '1 tsp garam masala, ½ tsp turmeric',
      '1 tbsp lemon juice + 1 tbsp oil, salt',
    ],
    steps: [
      'Whisk yogurt with all the spices, ginger-garlic, lemon juice, oil and salt.',
      'Coat the chicken, pushing marinade into the slashes; rest at least 30 minutes.',
      'Preheat air fryer to 200°C.',
      'Air fry 18–22 min, turning halfway, until charred and the juices run clear (74°C internal).',
      'Rest 3 minutes, then finish with lemon and sliced onion.',
    ],
    tags: ['high-protein', 'low-carb', 'party'],
  },
  {
    id: 'airfryer-chicken-tenders',
    title: 'Crispy Air Fryer Chicken Tenders',
    emoji: '🍤',
    color: '#e9a23b',
    meals: ['lunch', 'dinner'],
    appliance: 'airfryer',
    cuisine: 'American',
    time: 30,
    difficulty: 'Easy',
    servings: '3',
    setting: '200°C · 12–14 min',
    ingredients: [
      '500 g chicken breast, cut into strips',
      '1 egg, beaten',
      '1 cup breadcrumbs (panko works best)',
      '½ cup flour',
      '1 tsp paprika + 1 tsp garlic powder, salt, pepper',
      'Oil spray',
    ],
    steps: [
      'Set up three bowls: seasoned flour, beaten egg, and breadcrumbs.',
      'Coat each strip in flour, then egg, then breadcrumbs, pressing to stick.',
      'Preheat air fryer to 200°C and spray the tenders all over with oil.',
      'Air fry 12–14 min, flipping once, until golden and cooked through.',
      'Serve with honey-mustard or ketchup.',
    ],
    tags: ['high-protein', 'kid-friendly', 'crispy'],
  },
  {
    id: 'airfryer-chicken-shawarma',
    title: 'Air Fryer Chicken Shawarma',
    emoji: '🌯',
    color: '#c1843d',
    meals: ['lunch', 'dinner'],
    appliance: 'airfryer',
    cuisine: 'Middle Eastern',
    time: 35,
    difficulty: 'Easy',
    servings: '3',
    setting: '200°C · 14–16 min',
    ingredients: [
      '600 g boneless chicken thighs',
      '2 tbsp oil + 1 tbsp lemon juice',
      '1 tsp each: cumin, coriander, paprika, garlic powder',
      '½ tsp turmeric + ½ tsp cinnamon, salt',
      'Pita, garlic sauce and salad, to serve',
    ],
    steps: [
      'Mix oil, lemon and all the spices, then coat the chicken; marinate 20 minutes.',
      'Preheat air fryer to 200°C.',
      'Lay the thighs flat and air fry 14–16 min, turning once, until charred at the edges.',
      'Rest, then slice thinly across the grain.',
      'Pile into warm pita with garlic sauce, pickles and salad.',
    ],
    tags: ['high-protein', 'meal-prep'],
  },
  {
    id: 'steamed-lemongrass-chicken',
    title: 'Steamed Lemongrass Chicken',
    emoji: '🍋',
    color: '#a3b18a',
    meals: ['dinner', 'lunch'],
    appliance: 'steamer',
    cuisine: 'Thai',
    time: 35,
    difficulty: 'Easy',
    servings: '2',
    setting: 'Steam 20–22 min',
    ingredients: [
      '2 boneless chicken breasts or 4 thighs',
      '1 lemongrass stalk, bruised and chopped',
      '1 tbsp fish sauce + 1 tsp honey',
      '1 tsp grated ginger + 2 garlic cloves',
      'Coriander and lime, to serve',
    ],
    steps: [
      'Marinate the chicken in lemongrass, fish sauce, honey, ginger and garlic for 15 minutes.',
      'Lay the chicken on the steamer tray, spooning over the marinade.',
      'Add water to the base and steam 20–22 minutes until fully cooked (74°C internal).',
      'Check the thickest part is no longer pink.',
      'Garnish with coriander and a squeeze of lime; serve over rice.',
    ],
    tags: ['high-protein', 'low-carb', 'light'],
  },
  {
    id: 'airfryer-peri-peri-drumsticks',
    title: 'Air Fryer Peri-Peri Drumsticks',
    emoji: '🔥',
    color: '#bf0603',
    meals: ['dinner'],
    appliance: 'airfryer',
    cuisine: 'Portuguese',
    time: 40,
    difficulty: 'Easy',
    servings: '3',
    setting: '200°C · 20–24 min',
    ingredients: [
      '8 chicken drumsticks',
      '3 tbsp peri-peri sauce',
      '1 tbsp oil + 1 tbsp lemon juice',
      '1 tsp smoked paprika + 1 tsp garlic powder, salt',
    ],
    steps: [
      'Coat the drumsticks in peri-peri sauce, oil, lemon, paprika, garlic and salt.',
      'Marinate at least 30 minutes (overnight is better).',
      'Preheat air fryer to 200°C.',
      'Air fry 20–24 min, turning every 7–8 minutes, until charred and cooked through.',
      'Brush with extra sauce and serve with lemon wedges.',
    ],
    tags: ['high-protein', 'spicy', 'party'],
  },

  // ---------------------------- LAMB ----------------------------
  {
    id: 'airfryer-lamb-chops',
    title: 'Air Fryer Herb Lamb Chops',
    emoji: '🍖',
    color: '#9d4e15',
    meals: ['dinner'],
    appliance: 'airfryer',
    cuisine: 'Mediterranean',
    time: 30,
    difficulty: 'Medium',
    servings: '2',
    setting: '200°C · 10–12 min',
    ingredients: [
      '6 lamb chops',
      '2 tbsp olive oil',
      '3 garlic cloves, minced',
      '1 tbsp chopped rosemary + thyme',
      '1 tsp lemon zest, salt and pepper',
    ],
    steps: [
      'Rub the chops with oil, garlic, herbs, lemon zest, salt and pepper; rest 20 minutes.',
      'Preheat air fryer to 200°C.',
      'Air fry 10–12 min, flipping once — about 10 min for medium, 12 for well done.',
      'Rest the chops 5 minutes before serving so the juices settle.',
      'Serve with mint sauce and roasted vegetables.',
    ],
    tags: ['high-protein', 'low-carb'],
  },
  {
    id: 'airfryer-lamb-seekh-kebab',
    title: 'Air Fryer Lamb Seekh Kebab',
    emoji: '🥩',
    color: '#7f4f24',
    meals: ['lunch', 'dinner'],
    appliance: 'airfryer',
    cuisine: 'Indian',
    time: 35,
    difficulty: 'Medium',
    servings: '3',
    setting: '200°C · 12–14 min',
    ingredients: [
      '500 g lamb mince',
      '1 small onion + 2 green chillies, very finely chopped',
      '1 tbsp ginger-garlic paste',
      '1 tsp garam masala + 1 tsp cumin + ½ tsp chilli powder',
      'Handful of chopped coriander and mint, salt',
    ],
    steps: [
      'Mix everything well and knead for a minute so the mince binds; chill 15 minutes.',
      'Shape into sausages around skewers, or as logs straight in the basket.',
      'Preheat air fryer to 200°C.',
      'Air fry 12–14 min, turning once, until browned and cooked through.',
      'Serve with mint chutney, onion rings and lemon.',
    ],
    tags: ['high-protein', 'low-carb', 'party'],
  },
  {
    id: 'airfryer-lamb-koftas',
    title: 'Air Fryer Lamb Koftas',
    emoji: '🧆',
    color: '#a47148',
    meals: ['dinner'],
    appliance: 'airfryer',
    cuisine: 'Middle Eastern',
    time: 30,
    difficulty: 'Easy',
    servings: '3',
    setting: '190°C · 12–15 min',
    ingredients: [
      '500 g lamb mince',
      '1 grated onion (squeezed dry)',
      '2 garlic cloves, minced',
      '1 tsp cumin + 1 tsp coriander + ½ tsp cinnamon',
      'Chopped parsley and mint, salt and pepper',
    ],
    steps: [
      'Combine all the ingredients and mix until sticky; shape into oval koftas.',
      'Preheat air fryer to 190°C.',
      'Air fry 12–15 min, turning once, until browned and cooked through.',
      'Rest a couple of minutes.',
      'Serve with flatbread, tzatziki and a tomato-cucumber salad.',
    ],
    tags: ['high-protein', 'meal-prep'],
  },

  // ---------------------------- FISH & SEAFOOD ----------------------------
  {
    id: 'airfryer-fish-fingers',
    title: 'Air Fryer Crispy Fish Fingers',
    emoji: '🐠',
    color: '#48cae4',
    meals: ['lunch', 'dinner'],
    appliance: 'airfryer',
    cuisine: 'British',
    time: 25,
    difficulty: 'Easy',
    servings: '3',
    setting: '200°C · 10–12 min',
    ingredients: [
      '500 g firm white fish, cut into fingers',
      '1 egg, beaten',
      '1 cup breadcrumbs (panko)',
      '½ cup flour',
      '1 tsp paprika, salt, pepper',
      'Oil spray',
    ],
    steps: [
      'Pat the fish dry. Set up seasoned flour, beaten egg and breadcrumbs.',
      'Coat each finger in flour, then egg, then breadcrumbs.',
      'Preheat air fryer to 200°C and spray the fingers with oil.',
      'Air fry 10–12 min, flipping once, until crisp and golden.',
      'Serve with tartare sauce and lemon.',
    ],
    tags: ['pescatarian', 'kid-friendly', 'crispy'],
  },
  {
    id: 'airfryer-garlic-prawns',
    title: 'Air Fryer Garlic Butter Prawns',
    emoji: '🦐',
    color: '#f4845f',
    meals: ['lunch', 'dinner'],
    appliance: 'airfryer',
    cuisine: 'Global',
    time: 15,
    difficulty: 'Easy',
    servings: '2',
    setting: '190°C · 6–8 min',
    ingredients: [
      '300 g large prawns, peeled and deveined',
      '2 tbsp melted butter',
      '3 garlic cloves, minced',
      '1 tsp paprika + ¼ tsp chilli flakes',
      'Parsley, lemon, salt',
    ],
    steps: [
      'Toss the prawns with butter, garlic, paprika, chilli flakes and salt.',
      'Preheat air fryer to 190°C.',
      'Air fry 6–8 min, shaking once, until pink and opaque — do not overcook.',
      'Toss with parsley and a squeeze of lemon.',
      'Serve over pasta, rice, or with crusty bread.',
    ],
    tags: ['pescatarian', 'high-protein', 'low-carb', 'quick'],
  },
  {
    id: 'steamed-ginger-soy-fish',
    title: 'Steamed Ginger-Soy Fish',
    emoji: '🐟',
    color: '#73c2be',
    meals: ['lunch', 'dinner'],
    appliance: 'steamer',
    cuisine: 'Chinese',
    time: 25,
    difficulty: 'Easy',
    servings: '2',
    setting: 'Steam 12–15 min',
    ingredients: [
      '2 white fish fillets (sea bass, basa or tilapia)',
      '2 tbsp light soy sauce + 1 tsp sesame oil',
      '1 thumb ginger, julienned',
      '2 spring onions, shredded',
      '1 tsp sugar, pinch of white pepper',
    ],
    steps: [
      'Lay the fish on the steamer tray and scatter over half the ginger.',
      'Add water to the base and steam 12–15 minutes until it flakes easily.',
      'Mix soy, sesame oil, sugar and pepper for the sauce.',
      'Top the steamed fish with fresh ginger and spring onions, then pour over the warm sauce.',
      'Serve immediately with steamed rice.',
    ],
    tags: ['pescatarian', 'high-protein', 'low-carb', 'light'],
  },
  {
    id: 'airfryer-fish-tikka',
    title: 'Air Fryer Fish Tikka',
    emoji: '🎣',
    color: '#e07a5f',
    meals: ['lunch', 'dinner'],
    appliance: 'airfryer',
    cuisine: 'Indian',
    time: 30,
    difficulty: 'Easy',
    servings: '3',
    setting: '200°C · 10–12 min',
    ingredients: [
      '500 g firm fish (king fish, salmon or basa), cubed',
      '4 tbsp thick yogurt',
      '1 tbsp ginger-garlic paste',
      '1 tsp each: chilli powder, garam masala, cumin',
      '1 tbsp besan + 1 tbsp lemon juice, salt',
    ],
    steps: [
      'Whisk yogurt with the spices, besan, ginger-garlic, lemon and salt.',
      'Gently coat the fish and marinate 15–20 minutes (no longer, or it gets mushy).',
      'Preheat air fryer to 200°C and lay the fish out in a single layer.',
      'Air fry 10–12 min, turning once carefully, until charred at the edges.',
      'Finish with chaat masala and lemon.',
    ],
    tags: ['pescatarian', 'high-protein', 'low-carb'],
  },

  // ---------------------------- MORE COMBINATIONS ----------------------------
  {
    id: 'airfryer-crispy-tofu',
    title: 'Air Fryer Crispy Chilli Tofu',
    emoji: '🧊',
    color: '#dda15e',
    meals: ['lunch', 'dinner'],
    appliance: 'airfryer',
    cuisine: 'Asian',
    time: 30,
    difficulty: 'Easy',
    servings: '2',
    setting: '200°C · 14–16 min',
    ingredients: [
      '400 g firm tofu, pressed and cubed',
      '1 tbsp cornflour + 1 tbsp soy sauce',
      '1 tbsp oil',
      '2 tbsp sweet chilli sauce',
      '1 tsp sriracha, sesame seeds, spring onion',
    ],
    steps: [
      'Toss the tofu with soy sauce, oil and cornflour until evenly coated.',
      'Preheat air fryer to 200°C.',
      'Air fry 14–16 min, shaking twice, until golden and crisp on all sides.',
      'Toss the hot tofu with sweet chilli and sriracha.',
      'Top with sesame seeds and spring onion; serve over rice.',
    ],
    tags: ['vegan', 'vegetarian', 'high-protein', 'crispy'],
  },
  {
    id: 'airfryer-breakfast-sausages',
    title: 'Air Fryer Breakfast Sausages',
    emoji: '🌭',
    color: '#b5651d',
    meals: ['breakfast'],
    appliance: 'airfryer',
    cuisine: 'American',
    time: 15,
    difficulty: 'Easy',
    servings: '3',
    setting: '180°C · 10–12 min',
    ingredients: [
      '6 chicken or pork breakfast sausages',
      'Optional: brush of oil',
    ],
    steps: [
      'Preheat air fryer to 180°C.',
      'Arrange the sausages in a single layer with a little space between them.',
      'Air fry 10–12 min, turning halfway, until browned and cooked through.',
      'Check the thickest sausage is no longer pink inside.',
      'Serve with eggs, toast and grilled tomatoes.',
    ],
    tags: ['high-protein', 'quick', 'kid-friendly'],
  },
  {
    id: 'airfryer-veggie-frittata',
    title: 'Air Fryer Veggie Frittata',
    emoji: '🍳',
    color: '#ffca3a',
    meals: ['breakfast', 'lunch'],
    appliance: 'airfryer',
    cuisine: 'Italian',
    time: 25,
    difficulty: 'Easy',
    servings: '2',
    setting: '160°C · 12–15 min',
    ingredients: [
      '4 eggs',
      '¼ cup milk',
      '½ cup chopped peppers, onion and spinach',
      '¼ cup grated cheese',
      'Salt, pepper, chilli flakes',
    ],
    steps: [
      'Whisk eggs with milk, salt and pepper, then stir in the veg and half the cheese.',
      'Pour into a greased oven-safe dish that fits the basket; top with remaining cheese.',
      'Preheat air fryer to 160°C.',
      'Air fry 12–15 min until just set in the middle.',
      'Cool 2 minutes, slice and serve.',
    ],
    tags: ['vegetarian', 'high-protein', 'low-carb'],
  },
  {
    id: 'steamed-egg-custard',
    title: 'Steamed Savoury Egg Custard',
    emoji: '🥣',
    color: '#fefae0',
    meals: ['breakfast'],
    appliance: 'steamer',
    cuisine: 'Japanese',
    time: 25,
    difficulty: 'Medium',
    servings: '2',
    setting: 'Steam 12–15 min',
    ingredients: [
      '3 eggs',
      '1.5 cups warm dashi or light stock',
      '1 tsp soy sauce + ½ tsp mirin',
      'A few prawns, mushroom slices or peas',
      'Spring onion, to garnish',
    ],
    steps: [
      'Gently whisk the eggs (avoid foam) and stir in the warm stock, soy and mirin.',
      'Strain into 2 heatproof cups and drop in the prawns or vegetables.',
      'Cover each cup loosely with foil and place in the steamer tray.',
      'Steam 12–15 minutes on a gentle setting until just set and silky.',
      'Garnish with spring onion and serve warm.',
    ],
    tags: ['high-protein', 'light', 'low-carb'],
  },

  // ---------------------------- PORK ----------------------------
  {
    id: 'airfryer-honey-garlic-pork-chops',
    title: 'Air Fryer Honey-Garlic Pork Chops',
    emoji: '🥩',
    color: '#bc8a5f',
    meals: ['dinner'],
    appliance: 'airfryer',
    cuisine: 'American',
    time: 30,
    difficulty: 'Easy',
    servings: '2',
    setting: '200°C · 12–14 min',
    ingredients: [
      '2 thick boneless pork chops',
      '2 tbsp honey + 2 tbsp soy sauce',
      '3 garlic cloves, minced',
      '1 tsp paprika + ½ tsp black pepper',
      '1 tbsp oil, salt',
    ],
    steps: [
      'Pat the chops dry and rub with oil, paprika, salt and pepper.',
      'Whisk honey, soy and garlic into a glaze and brush over both sides.',
      'Preheat air fryer to 200°C.',
      'Air fry 12–14 min, flipping and re-glazing halfway, until cooked through (63°C internal, then rest).',
      'Rest 5 minutes — the juices redistribute and stay tender — then serve.',
    ],
    tags: ['high-protein', 'low-carb'],
  },
  {
    id: 'airfryer-crispy-pork-chops',
    title: 'Air Fryer Crispy Breaded Pork Chops',
    emoji: '🍖',
    color: '#c9a66b',
    meals: ['lunch', 'dinner'],
    appliance: 'airfryer',
    cuisine: 'American',
    time: 30,
    difficulty: 'Medium',
    servings: '3',
    setting: '200°C · 12–15 min',
    ingredients: [
      '3 boneless pork chops, pounded slightly thin',
      '1 egg, beaten',
      '1 cup breadcrumbs (panko) + 2 tbsp grated parmesan',
      '½ cup flour',
      '1 tsp garlic powder + 1 tsp paprika, salt, pepper',
      'Oil spray',
    ],
    steps: [
      'Set up seasoned flour, beaten egg, and breadcrumbs mixed with parmesan.',
      'Coat each chop in flour, then egg, then the crumb mix, pressing to stick.',
      'Preheat air fryer to 200°C and spray the chops all over with oil.',
      'Air fry 12–15 min, flipping once, until crisp and cooked through (63°C internal).',
      'Rest briefly, then serve with lemon wedges and a crisp salad.',
    ],
    tags: ['high-protein', 'crispy'],
  },
  {
    id: 'steamed-blackbean-pork-ribs',
    title: 'Steamed Black Bean Pork Ribs',
    emoji: '🍱',
    color: '#9c6644',
    meals: ['lunch', 'dinner'],
    appliance: 'steamer',
    cuisine: 'Chinese',
    time: 45,
    difficulty: 'Medium',
    servings: '3',
    setting: 'Steam 30–35 min',
    ingredients: [
      '500 g pork spare ribs, cut into bite-size pieces',
      '1.5 tbsp fermented black beans, rinsed and mashed',
      '1 tbsp soy sauce + 1 tsp sugar + 1 tsp cornflour',
      '2 garlic cloves + 1 tsp grated ginger',
      '1 tsp sesame oil, spring onion and chilli to garnish',
    ],
    steps: [
      'Marinate the ribs with black beans, soy, sugar, cornflour, garlic, ginger and sesame oil for 20 minutes.',
      'Spread the ribs in a heatproof dish that fits the steamer tray.',
      'Add water to the base and steam 30–35 minutes until tender, topping up water if needed.',
      'Check the meat pulls away easily from the bone.',
      'Garnish with spring onion and fresh chilli; serve with steamed rice.',
    ],
    tags: ['high-protein', 'dim-sum'],
  },

  // ---------------------------- PRAWNS ----------------------------
  {
    id: 'airfryer-coconut-prawns',
    title: 'Air Fryer Coconut Prawns',
    emoji: '🍤',
    color: '#f6bd60',
    meals: ['lunch', 'dinner'],
    appliance: 'airfryer',
    cuisine: 'Global',
    time: 25,
    difficulty: 'Medium',
    servings: '3',
    setting: '200°C · 8–10 min',
    ingredients: [
      '350 g large prawns, peeled with tails on',
      '1 egg, beaten',
      '½ cup flour + 1 tsp paprika, salt',
      '1 cup desiccated coconut + ½ cup panko',
      'Oil spray, sweet chilli sauce to serve',
    ],
    steps: [
      'Pat the prawns dry. Set up seasoned flour, beaten egg, and coconut mixed with panko.',
      'Coat each prawn in flour, then egg, then press into the coconut mix.',
      'Preheat air fryer to 200°C and spray the prawns with oil.',
      'Air fry 8–10 min, flipping once, until golden and the coconut is toasted — do not overcook.',
      'Serve hot with sweet chilli dipping sauce.',
    ],
    tags: ['pescatarian', 'crispy', 'party'],
  },
  {
    id: 'airfryer-tandoori-prawns',
    title: 'Air Fryer Tandoori Prawns',
    emoji: '🦐',
    color: '#e5564f',
    meals: ['lunch', 'dinner'],
    appliance: 'airfryer',
    cuisine: 'Indian',
    time: 25,
    difficulty: 'Easy',
    servings: '2',
    setting: '200°C · 7–9 min',
    ingredients: [
      '300 g large prawns, peeled and deveined',
      '3 tbsp thick yogurt',
      '1 tbsp ginger-garlic paste',
      '1 tsp each: chilli powder, garam masala, cumin',
      '1 tsp besan + 1 tbsp lemon juice, salt',
    ],
    steps: [
      'Whisk yogurt with the spices, besan, ginger-garlic, lemon and salt.',
      'Coat the prawns and marinate 15 minutes (no longer — prawns turn rubbery).',
      'Preheat air fryer to 200°C and lay the prawns in a single layer.',
      'Air fry 7–9 min, turning once, until pink, opaque and charred at the edges.',
      'Finish with chaat masala and lemon.',
    ],
    tags: ['pescatarian', 'high-protein', 'low-carb', 'spicy'],
  },
  {
    id: 'steamed-garlic-chilli-prawns',
    title: 'Steamed Garlic-Chilli Prawns',
    emoji: '🦐',
    color: '#ef6351',
    meals: ['lunch', 'dinner'],
    appliance: 'steamer',
    cuisine: 'Asian',
    time: 20,
    difficulty: 'Easy',
    servings: '2',
    setting: 'Steam 8–10 min',
    ingredients: [
      '300 g large prawns, peeled and butterflied',
      '4 garlic cloves, minced',
      '1 red chilli, finely chopped',
      '1 tbsp soy sauce + 1 tsp sesame oil',
      'Spring onion and coriander, to garnish',
    ],
    steps: [
      'Arrange the prawns in a heatproof dish and scatter over the garlic and chilli.',
      'Spoon over the soy sauce and sesame oil.',
      'Add water to the base and steam 8–10 minutes until pink and just opaque.',
      'Avoid over-steaming, or the prawns toughen.',
      'Garnish with spring onion and coriander; serve over rice or noodles.',
    ],
    tags: ['pescatarian', 'high-protein', 'low-carb', 'light', 'quick'],
  },
]

// Build the unique, sorted list of tags for the filter UI.
export const ALL_TAGS = Array.from(
  new Set(recipes.flatMap((r) => r.tags)),
).sort()
