// Foodiee recipe data
// -------------------
// Every recipe here is designed for ONE of the two appliances we own:
//   - "airfryer"  -> Philips Airfryer (RapidAir, dial model). Temps in °C.
//   - "steamer"   -> Wipro Multi Cooker / Egg Boiler (multi-tier steamer). Times in minutes.
//
// Each recipe is tagged with one or more meals: 'breakfast' | 'lunch' | 'dinner'.
// Times are total (prep + cook) in minutes. Difficulty: 'Easy' | 'Medium'.

// Six curated "hero" appliances. The first two are Foodiee's brand front-door
// (the built-in 98 recipes); the rest unlock when you import recipes from reels.
// Each maps to an affiliate product in affiliate.js.
export const APPLIANCES = {
  airfryer: { label: 'Air Fryer', emoji: '🌀', full: 'Philips Airfryer' },
  steamer: { label: 'Steamer / Egg Boiler', emoji: '♨️', full: 'Wipro Multi Cooker' },
  mixer: { label: 'Mixer-Grinder', emoji: '🥤', full: 'Mixer-Grinder / Blender' },
  oven: { label: 'OTG / Oven', emoji: '🔥', full: 'OTG / Oven' },
  cooktop: { label: 'Cooktop', emoji: '🍳', full: 'Induction Cooktop' },
  pressurecooker: { label: 'Pressure Cooker', emoji: '🍲', full: 'Pressure Cooker' },
}

export const MEALS = {
  breakfast: { label: 'Breakfast', emoji: '🌅' },
  lunch: { label: 'Lunch', emoji: '☀️' },
  dinner: { label: 'Dinner', emoji: '🌙' },
  snack: { label: 'Snack', emoji: '🍿' },
  dessert: { label: 'Dessert', emoji: '🍰' },
}

export const recipes = [
  // ---------------------------- BREAKFAST ----------------------------
  {
    id: 'soft-boiled-eggs',
    title: 'Perfect Soft-Boiled Eggs',
    emoji: '🥚',
    color: '#ffd166',
    meals: ['breakfast'],
    appliance: 'steamer',
    cuisine: 'Global',
    time: 15,
    difficulty: 'Easy',
    servings: '2–6 eggs',
    setting: 'Steam ~12 min for soft, ~15 min for hard',
    ingredients: [
      'Up to 6 eggs',
      'Measuring cup of water (use the marking for your desired doneness)',
      'Pinch of salt and pepper, to serve',
    ],
    steps: [
      'Add water to the base using the measuring cup — less water for soft, more for hard-boiled.',
      'Pierce the wider end of each egg with the pin on the measuring cup to stop cracking.',
      'Place eggs in the egg tray, pointed side down. Cover with the lid.',
      'Switch on; the cooker beeps and shuts off when the water has fully evaporated.',
      'Plunge eggs into cold water for 1 minute, then peel. Season and serve.',
    ],
    tags: ['high-protein', 'meal-prep', 'vegetarian'],
  },
  {
    id: 'airfryer-french-toast',
    title: 'Air Fryer French Toast Sticks',
    emoji: '🍞',
    color: '#f4a261',
    meals: ['breakfast'],
    appliance: 'airfryer',
    cuisine: 'American',
    time: 15,
    difficulty: 'Easy',
    servings: '2',
    setting: '180°C · 8–10 min',
    ingredients: [
      '4 thick slices of bread, cut into 3 sticks each',
      '2 eggs',
      '60 ml milk',
      '1 tsp cinnamon',
      '1 tsp vanilla',
      'Maple syrup, to serve',
    ],
    steps: [
      'Whisk eggs, milk, cinnamon and vanilla in a shallow bowl.',
      'Dip each bread stick briefly on all sides — do not soak.',
      'Preheat the air fryer to 180°C for 2 minutes.',
      'Arrange sticks in a single layer (cook in batches if needed). Air fry 8–10 min, flipping halfway, until golden.',
      'Dust with extra cinnamon and serve with maple syrup.',
    ],
    tags: ['kid-friendly', 'vegetarian', 'quick'],
  },
  {
    id: 'steamed-idli',
    title: 'Steamed Idli',
    emoji: '⚪',
    color: '#e9edc9',
    meals: ['breakfast'],
    appliance: 'steamer',
    cuisine: 'Indian',
    time: 20,
    difficulty: 'Easy',
    servings: '2–3',
    setting: 'Steam 10–12 min',
    ingredients: [
      '2 cups fermented idli batter',
      'Oil or ghee, to grease',
      'Coconut chutney and sambar, to serve',
    ],
    steps: [
      'Lightly grease the steamer tray cups (use an idli plate if it fits, or small silicone moulds).',
      'Pour batter into each mould, filling about ¾ full.',
      'Add water to the base, place the tray, cover and steam 10–12 minutes.',
      'Check with a toothpick — it should come out clean. Rest 2 minutes before unmoulding.',
      'Serve hot with coconut chutney and sambar.',
    ],
    tags: ['vegetarian', 'vegan', 'light'],
  },
  {
    id: 'airfryer-hash-browns',
    title: 'Crispy Air Fryer Hash Browns',
    emoji: '🥔',
    color: '#e9c46a',
    meals: ['breakfast'],
    appliance: 'airfryer',
    cuisine: 'American',
    time: 25,
    difficulty: 'Medium',
    servings: '2',
    setting: '190°C · 14–16 min',
    ingredients: [
      '2 large potatoes, grated',
      '1 tbsp cornflour',
      '½ tsp salt',
      '¼ tsp black pepper',
      '½ tsp paprika',
      '1 tbsp oil',
    ],
    steps: [
      'Squeeze the grated potato in a cloth to remove as much water as possible.',
      'Mix with cornflour, salt, pepper, paprika and oil. Press into flat patties.',
      'Preheat air fryer to 190°C. Lightly brush the basket.',
      'Air fry patties 14–16 min, flipping once, until deep golden and crisp.',
      'Season with extra salt and serve immediately.',
    ],
    tags: ['vegetarian', 'crispy', 'vegan'],
  },
  {
    id: 'steamed-veg-momos',
    title: 'Steamed Vegetable Momos',
    emoji: '🥟',
    color: '#cdb4db',
    meals: ['breakfast', 'lunch'],
    appliance: 'steamer',
    cuisine: 'Tibetan / Nepali',
    time: 35,
    difficulty: 'Medium',
    servings: '3',
    setting: 'Steam 12–14 min',
    ingredients: [
      '20 momo wrappers',
      '2 cups finely shredded cabbage',
      '1 carrot, grated',
      '2 spring onions, chopped',
      '1 tbsp soy sauce',
      '1 tsp grated ginger + garlic',
      'Salt and pepper',
    ],
    steps: [
      'Stir-fry the vegetables with ginger-garlic, soy sauce, salt and pepper for 2 minutes; cool.',
      'Place a spoon of filling in each wrapper and pleat to seal.',
      'Lightly oil the steamer tray so momos don’t stick.',
      'Add water to the base and steam 12–14 minutes until the wrappers turn glossy.',
      'Serve hot with spicy tomato-garlic chutney.',
    ],
    tags: ['vegetarian', 'vegan', 'street-food'],
  },

  // ---------------------------- LUNCH ----------------------------
  {
    id: 'airfryer-paneer-tikka',
    title: 'Air Fryer Paneer Tikka',
    emoji: '🧆',
    color: '#e76f51',
    meals: ['lunch', 'dinner'],
    appliance: 'airfryer',
    cuisine: 'Indian',
    time: 35,
    difficulty: 'Easy',
    servings: '3',
    setting: '200°C · 10–12 min',
    ingredients: [
      '250 g paneer, cubed',
      '1 capsicum + 1 onion, in chunks',
      '4 tbsp thick yogurt',
      '1 tbsp ginger-garlic paste',
      '1 tsp each: chilli powder, garam masala, cumin',
      '1 tbsp besan (gram flour)',
      '1 tbsp oil, salt',
    ],
    steps: [
      'Whisk yogurt with all spices, besan, oil and salt into a thick marinade.',
      'Fold in paneer and vegetables; marinate at least 20 minutes.',
      'Preheat air fryer to 200°C. Thread onto skewers or lay flat in the basket.',
      'Air fry 10–12 min, turning once, until charred at the edges.',
      'Finish with lemon juice and chaat masala.',
    ],
    tags: ['vegetarian', 'high-protein', 'party'],
  },
  {
    id: 'steamed-lemon-fish',
    title: 'Steamed Lemon-Herb Fish',
    emoji: '🐟',
    color: '#a8dadc',
    meals: ['lunch', 'dinner'],
    appliance: 'steamer',
    cuisine: 'Mediterranean',
    time: 25,
    difficulty: 'Easy',
    servings: '2',
    setting: 'Steam 12–15 min',
    ingredients: [
      '2 white fish fillets (basa, tilapia or cod)',
      '1 lemon, half sliced + half juiced',
      '2 cloves garlic, minced',
      'A few sprigs of dill or parsley',
      '1 tbsp olive oil, salt and pepper',
    ],
    steps: [
      'Pat the fish dry and season both sides with salt, pepper and garlic.',
      'Lay lemon slices on the steamer tray and place the fish on top so it doesn’t stick.',
      'Drizzle with olive oil and scatter the herbs.',
      'Add water to the base and steam 12–15 minutes, until the fish flakes easily.',
      'Finish with a squeeze of fresh lemon juice.',
    ],
    tags: ['high-protein', 'low-carb', 'light', 'pescatarian'],
  },
  {
    id: 'airfryer-falafel',
    title: 'Air Fryer Falafel',
    emoji: '🧇',
    color: '#90a955',
    meals: ['lunch'],
    appliance: 'airfryer',
    cuisine: 'Middle Eastern',
    time: 30,
    difficulty: 'Medium',
    servings: '3',
    setting: '190°C · 14–16 min',
    ingredients: [
      '1½ cups soaked (not cooked) chickpeas',
      '1 small onion + 3 garlic cloves',
      'Handful of parsley and coriander',
      '1 tsp cumin, 1 tsp coriander powder',
      '2 tbsp besan, salt',
      'Oil spray',
    ],
    steps: [
      'Blitz everything except the oil into a coarse paste — do not over-blend.',
      'Rest 15 minutes, then shape into small patties.',
      'Preheat air fryer to 190°C and spray patties with oil.',
      'Air fry 14–16 min, flipping once, until golden and crisp.',
      'Tuck into pita with hummus, salad and tahini.',
    ],
    tags: ['vegan', 'vegetarian', 'high-protein'],
  },
  {
    id: 'steamed-veg-rice-bowl',
    title: 'Steamed Veg & Rice Bowl',
    emoji: '🍚',
    color: '#bde0fe',
    meals: ['lunch', 'dinner'],
    appliance: 'steamer',
    cuisine: 'Asian',
    time: 30,
    difficulty: 'Easy',
    servings: '2',
    setting: 'Steam rice ~25 min · veg last 10 min',
    ingredients: [
      '1 cup rice + 1¼ cups water',
      'Broccoli, carrot and beans, chopped',
      '1 tbsp soy sauce',
      '1 tsp sesame oil',
      '1 tsp toasted sesame seeds',
    ],
    steps: [
      'Add rice and water to the base bowl of the multi cooker.',
      'Steam for about 15 minutes, then add the vegetables to the upper tray.',
      'Continue steaming 10 minutes until the rice is fluffy and veg is tender-crisp.',
      'Toss the vegetables with soy sauce and sesame oil.',
      'Spoon rice into bowls, top with veg and sprinkle sesame seeds.',
    ],
    tags: ['vegan', 'vegetarian', 'meal-prep', 'one-pot'],
  },
  {
    id: 'airfryer-stuffed-peppers',
    title: 'Air Fryer Stuffed Peppers',
    emoji: '🫑',
    color: '#80b918',
    meals: ['lunch', 'dinner'],
    appliance: 'airfryer',
    cuisine: 'Tex-Mex',
    time: 35,
    difficulty: 'Medium',
    servings: '2',
    setting: '180°C · 15–18 min',
    ingredients: [
      '4 bell peppers, tops cut and seeded',
      '1 cup cooked rice or quinoa',
      '½ cup black beans or corn',
      '½ cup grated cheese',
      '1 tsp cumin + 1 tsp paprika',
      'Salt, pepper, coriander',
    ],
    steps: [
      'Mix rice, beans, half the cheese and the spices for the filling.',
      'Stuff the peppers and top with the remaining cheese.',
      'Preheat air fryer to 180°C.',
      'Air fry 15–18 min until the peppers are tender and the cheese is bubbling.',
      'Garnish with coriander and a dollop of yogurt or sour cream.',
    ],
    tags: ['vegetarian', 'gluten-free', 'comfort'],
  },

  // ---------------------------- DINNER ----------------------------
  {
    id: 'airfryer-chicken-wings',
    title: 'Crispy Air Fryer Chicken Wings',
    emoji: '🍗',
    color: '#bc6c25',
    meals: ['dinner'],
    appliance: 'airfryer',
    cuisine: 'American',
    time: 35,
    difficulty: 'Easy',
    servings: '3',
    setting: '200°C · 18–22 min',
    ingredients: [
      '700 g chicken wings, patted dry',
      '1 tbsp baking powder (for crispness)',
      '1 tsp each: garlic powder, paprika, salt',
      '½ tsp black pepper',
      'Buffalo or BBQ sauce, to toss',
    ],
    steps: [
      'Toss wings with baking powder, garlic powder, paprika, salt and pepper.',
      'Preheat air fryer to 200°C.',
      'Arrange in a single layer and air fry 18–22 min, flipping every 7–8 minutes.',
      'Cook until deep golden and the skin is crackly.',
      'Toss in your sauce of choice and serve with a cooling dip.',
    ],
    tags: ['high-protein', 'crispy', 'party'],
  },
  {
    id: 'airfryer-veg-spring-rolls',
    title: 'Air Fryer Vegetable Spring Rolls',
    emoji: '🥢',
    color: '#fb8500',
    meals: ['dinner'],
    appliance: 'airfryer',
    cuisine: 'Chinese',
    time: 30,
    difficulty: 'Medium',
    servings: '3',
    setting: '190°C · 10–12 min',
    ingredients: [
      '12 spring roll wrappers',
      '3 cups shredded cabbage, carrot, capsicum',
      '1 tbsp soy sauce + 1 tsp vinegar',
      '1 tsp ginger-garlic paste',
      'Oil spray',
      'Flour-water paste, to seal',
    ],
    steps: [
      'Stir-fry the vegetables with ginger-garlic, soy and vinegar for 2 minutes; cool.',
      'Roll the filling tightly in wrappers, sealing edges with flour paste.',
      'Preheat air fryer to 190°C and spray rolls all over with oil.',
      'Air fry 10–12 min, turning once, until crisp and golden.',
      'Serve with sweet chilli or schezwan sauce.',
    ],
    tags: ['vegetarian', 'vegan', 'crispy', 'party'],
  },
  {
    id: 'steamed-dumpling-soup',
    title: 'Steamed Chicken & Veg Parcels',
    emoji: '🍱',
    color: '#ffb4a2',
    meals: ['dinner'],
    appliance: 'steamer',
    cuisine: 'Asian',
    time: 30,
    difficulty: 'Easy',
    servings: '2',
    setting: 'Steam 18–20 min',
    ingredients: [
      '2 chicken breasts, thinly sliced (or tofu for veg)',
      '1 tbsp soy sauce + 1 tsp honey',
      '1 tsp grated ginger',
      'Bok choy or spinach',
      'Spring onion, to garnish',
    ],
    steps: [
      'Marinate the chicken in soy, honey and ginger for 10 minutes.',
      'Lay the chicken on the steamer tray with the greens alongside.',
      'Add water to the base and steam 18–20 minutes until cooked through.',
      'Check the chicken is no longer pink at the thickest part.',
      'Garnish with spring onion and serve over rice or noodles.',
    ],
    tags: ['high-protein', 'low-carb', 'light'],
  },
  {
    id: 'airfryer-roasted-veg',
    title: 'Air Fryer Roasted Vegetables',
    emoji: '🥦',
    color: '#588157',
    meals: ['dinner', 'lunch'],
    appliance: 'airfryer',
    cuisine: 'Mediterranean',
    time: 25,
    difficulty: 'Easy',
    servings: '3',
    setting: '200°C · 12–15 min',
    ingredients: [
      '4 cups mixed veg (zucchini, peppers, onion, mushroom, cherry tomato)',
      '2 tbsp olive oil',
      '1 tsp Italian herbs',
      '2 cloves garlic, minced',
      'Salt, pepper, chilli flakes',
    ],
    steps: [
      'Toss all the vegetables with oil, herbs, garlic, salt and pepper.',
      'Preheat air fryer to 200°C.',
      'Air fry 12–15 min, shaking the basket halfway, until caramelised at the edges.',
      'Finish with chilli flakes and a squeeze of lemon.',
      'Serve as a side, over couscous, or stuffed into wraps.',
    ],
    tags: ['vegan', 'vegetarian', 'gluten-free', 'side'],
  },
  {
    id: 'airfryer-salmon',
    title: 'Air Fryer Honey-Garlic Salmon',
    emoji: '🍣',
    color: '#ef798a',
    meals: ['dinner'],
    appliance: 'airfryer',
    cuisine: 'Global',
    time: 20,
    difficulty: 'Easy',
    servings: '2',
    setting: '190°C · 8–10 min',
    ingredients: [
      '2 salmon fillets',
      '2 tbsp honey',
      '2 cloves garlic, minced',
      '1 tbsp soy sauce',
      '1 tsp lemon juice',
      'Salt and pepper',
    ],
    steps: [
      'Whisk honey, garlic, soy sauce and lemon juice into a glaze.',
      'Season the salmon and brush generously with the glaze.',
      'Preheat air fryer to 190°C and line the basket with a small piece of foil.',
      'Air fry 8–10 min, until the salmon flakes and the top is caramelised.',
      'Spoon over any extra glaze and serve with greens or rice.',
    ],
    tags: ['high-protein', 'pescatarian', 'quick', 'low-carb'],
  },
  {
    id: 'steamed-corn-edamame',
    title: 'Steamed Corn & Edamame Snack Bowl',
    emoji: '🌽',
    color: '#ffd60a',
    meals: ['dinner', 'lunch'],
    appliance: 'steamer',
    cuisine: 'Global',
    time: 15,
    difficulty: 'Easy',
    servings: '2',
    setting: 'Steam 10–12 min',
    ingredients: [
      '1 cup sweetcorn',
      '1 cup edamame (in pods or shelled)',
      '1 tbsp butter or olive oil',
      'Chilli-lime seasoning or chaat masala',
      'Flaky salt',
    ],
    steps: [
      'Add the corn and edamame to the steamer tray.',
      'Add water to the base and steam 10–12 minutes until tender.',
      'Toss the warm veg with butter or olive oil.',
      'Sprinkle with chilli-lime seasoning and flaky salt.',
      'Serve as a light dinner side or evening snack.',
    ],
    tags: ['vegetarian', 'vegan', 'quick', 'snack'],
  },

  // ---------------------------- CHICKEN ----------------------------
  {
    id: 'airfryer-tandoori-chicken',
    title: 'Air Fryer Tandoori Chicken',
    emoji: '🍗',
    color: '#d62828',
    meals: ['lunch', 'dinner'],
    appliance: 'airfryer',
    cuisine: 'Indian',
    time: 40,
    difficulty: 'Medium',
    servings: '3',
    setting: '200°C · 18–22 min',
    ingredients: [
      '6 bone-in chicken drumsticks or thighs, slashed',
      '5 tbsp thick yogurt',
      '1 tbsp ginger-garlic paste',
      '1 tbsp tandoori masala + 1 tsp chilli powder',
      '1 tsp garam masala, ½ tsp turmeric',
      '1 tbsp lemon juice + 1 tbsp oil, salt',
    ],
    steps: [
      'Whisk yogurt with all the spices, ginger-garlic, lemon juice, oil and salt.',
      'Coat the chicken, pushing marinade into the slashes; rest at least 30 minutes.',
      'Preheat air fryer to 200°C.',
      'Air fry 18–22 min, turning halfway, until charred and the juices run clear (74°C internal).',
      'Rest 3 minutes, then finish with lemon and sliced onion.',
    ],
    tags: ['high-protein', 'low-carb', 'party'],
  },
  {
    id: 'airfryer-chicken-tenders',
    title: 'Crispy Air Fryer Chicken Tenders',
    emoji: '🍤',
    color: '#e9a23b',
    meals: ['lunch', 'dinner'],
    appliance: 'airfryer',
    cuisine: 'American',
    time: 30,
    difficulty: 'Easy',
    servings: '3',
    setting: '200°C · 12–14 min',
    ingredients: [
      '500 g chicken breast, cut into strips',
      '1 egg, beaten',
      '1 cup breadcrumbs (panko works best)',
      '½ cup flour',
      '1 tsp paprika + 1 tsp garlic powder, salt, pepper',
      'Oil spray',
    ],
    steps: [
      'Set up three bowls: seasoned flour, beaten egg, and breadcrumbs.',
      'Coat each strip in flour, then egg, then breadcrumbs, pressing to stick.',
      'Preheat air fryer to 200°C and spray the tenders all over with oil.',
      'Air fry 12–14 min, flipping once, until golden and cooked through.',
      'Serve with honey-mustard or ketchup.',
    ],
    tags: ['high-protein', 'kid-friendly', 'crispy'],
  },
  {
    id: 'airfryer-chicken-shawarma',
    title: 'Air Fryer Chicken Shawarma',
    emoji: '🌯',
    color: '#c1843d',
    meals: ['lunch', 'dinner'],
    appliance: 'airfryer',
    cuisine: 'Middle Eastern',
    time: 35,
    difficulty: 'Easy',
    servings: '3',
    setting: '200°C · 14–16 min',
    ingredients: [
      '600 g boneless chicken thighs',
      '2 tbsp oil + 1 tbsp lemon juice',
      '1 tsp each: cumin, coriander, paprika, garlic powder',
      '½ tsp turmeric + ½ tsp cinnamon, salt',
      'Pita, garlic sauce and salad, to serve',
    ],
    steps: [
      'Mix oil, lemon and all the spices, then coat the chicken; marinate 20 minutes.',
      'Preheat air fryer to 200°C.',
      'Lay the thighs flat and air fry 14–16 min, turning once, until charred at the edges.',
      'Rest, then slice thinly across the grain.',
      'Pile into warm pita with garlic sauce, pickles and salad.',
    ],
    tags: ['high-protein', 'meal-prep'],
  },
  {
    id: 'steamed-lemongrass-chicken',
    title: 'Steamed Lemongrass Chicken',
    emoji: '🍋',
    color: '#a3b18a',
    meals: ['dinner', 'lunch'],
    appliance: 'steamer',
    cuisine: 'Thai',
    time: 35,
    difficulty: 'Easy',
    servings: '2',
    setting: 'Steam 20–22 min',
    ingredients: [
      '2 boneless chicken breasts or 4 thighs',
      '1 lemongrass stalk, bruised and chopped',
      '1 tbsp fish sauce + 1 tsp honey',
      '1 tsp grated ginger + 2 garlic cloves',
      'Coriander and lime, to serve',
    ],
    steps: [
      'Marinate the chicken in lemongrass, fish sauce, honey, ginger and garlic for 15 minutes.',
      'Lay the chicken on the steamer tray, spooning over the marinade.',
      'Add water to the base and steam 20–22 minutes until fully cooked (74°C internal).',
      'Check the thickest part is no longer pink.',
      'Garnish with coriander and a squeeze of lime; serve over rice.',
    ],
    tags: ['high-protein', 'low-carb', 'light'],
  },
  {
    id: 'airfryer-peri-peri-drumsticks',
    title: 'Air Fryer Peri-Peri Drumsticks',
    emoji: '🔥',
    color: '#bf0603',
    meals: ['dinner'],
    appliance: 'airfryer',
    cuisine: 'Portuguese',
    time: 40,
    difficulty: 'Easy',
    servings: '3',
    setting: '200°C · 20–24 min',
    ingredients: [
      '8 chicken drumsticks',
      '3 tbsp peri-peri sauce',
      '1 tbsp oil + 1 tbsp lemon juice',
      '1 tsp smoked paprika + 1 tsp garlic powder, salt',
    ],
    steps: [
      'Coat the drumsticks in peri-peri sauce, oil, lemon, paprika, garlic and salt.',
      'Marinate at least 30 minutes (overnight is better).',
      'Preheat air fryer to 200°C.',
      'Air fry 20–24 min, turning every 7–8 minutes, until charred and cooked through.',
      'Brush with extra sauce and serve with lemon wedges.',
    ],
    tags: ['high-protein', 'spicy', 'party'],
  },

  // ---------------------------- LAMB ----------------------------
  {
    id: 'airfryer-lamb-chops',
    title: 'Air Fryer Herb Lamb Chops',
    emoji: '🍖',
    color: '#9d4e15',
    meals: ['dinner'],
    appliance: 'airfryer',
    cuisine: 'Mediterranean',
    time: 30,
    difficulty: 'Medium',
    servings: '2',
    setting: '200°C · 10–12 min',
    ingredients: [
      '6 lamb chops',
      '2 tbsp olive oil',
      '3 garlic cloves, minced',
      '1 tbsp chopped rosemary + thyme',
      '1 tsp lemon zest, salt and pepper',
    ],
    steps: [
      'Rub the chops with oil, garlic, herbs, lemon zest, salt and pepper; rest 20 minutes.',
      'Preheat air fryer to 200°C.',
      'Air fry 10–12 min, flipping once — about 10 min for medium, 12 for well done.',
      'Rest the chops 5 minutes before serving so the juices settle.',
      'Serve with mint sauce and roasted vegetables.',
    ],
    tags: ['high-protein', 'low-carb'],
  },
  {
    id: 'airfryer-lamb-seekh-kebab',
    title: 'Air Fryer Lamb Seekh Kebab',
    emoji: '🥩',
    color: '#7f4f24',
    meals: ['lunch', 'dinner'],
    appliance: 'airfryer',
    cuisine: 'Indian',
    time: 35,
    difficulty: 'Medium',
    servings: '3',
    setting: '200°C · 12–14 min',
    ingredients: [
      '500 g lamb mince',
      '1 small onion + 2 green chillies, very finely chopped',
      '1 tbsp ginger-garlic paste',
      '1 tsp garam masala + 1 tsp cumin + ½ tsp chilli powder',
      'Handful of chopped coriander and mint, salt',
    ],
    steps: [
      'Mix everything well and knead for a minute so the mince binds; chill 15 minutes.',
      'Shape into sausages around skewers, or as logs straight in the basket.',
      'Preheat air fryer to 200°C.',
      'Air fry 12–14 min, turning once, until browned and cooked through.',
      'Serve with mint chutney, onion rings and lemon.',
    ],
    tags: ['high-protein', 'low-carb', 'party'],
  },
  {
    id: 'airfryer-lamb-koftas',
    title: 'Air Fryer Lamb Koftas',
    emoji: '🧆',
    color: '#a47148',
    meals: ['dinner'],
    appliance: 'airfryer',
    cuisine: 'Middle Eastern',
    time: 30,
    difficulty: 'Easy',
    servings: '3',
    setting: '190°C · 12–15 min',
    ingredients: [
      '500 g lamb mince',
      '1 grated onion (squeezed dry)',
      '2 garlic cloves, minced',
      '1 tsp cumin + 1 tsp coriander + ½ tsp cinnamon',
      'Chopped parsley and mint, salt and pepper',
    ],
    steps: [
      'Combine all the ingredients and mix until sticky; shape into oval koftas.',
      'Preheat air fryer to 190°C.',
      'Air fry 12–15 min, turning once, until browned and cooked through.',
      'Rest a couple of minutes.',
      'Serve with flatbread, tzatziki and a tomato-cucumber salad.',
    ],
    tags: ['high-protein', 'meal-prep'],
  },

  // ---------------------------- FISH & SEAFOOD ----------------------------
  {
    id: 'airfryer-fish-fingers',
    title: 'Air Fryer Crispy Fish Fingers',
    emoji: '🐠',
    color: '#48cae4',
    meals: ['lunch', 'dinner'],
    appliance: 'airfryer',
    cuisine: 'British',
    time: 25,
    difficulty: 'Easy',
    servings: '3',
    setting: '200°C · 10–12 min',
    ingredients: [
      '500 g firm white fish, cut into fingers',
      '1 egg, beaten',
      '1 cup breadcrumbs (panko)',
      '½ cup flour',
      '1 tsp paprika, salt, pepper',
      'Oil spray',
    ],
    steps: [
      'Pat the fish dry. Set up seasoned flour, beaten egg and breadcrumbs.',
      'Coat each finger in flour, then egg, then breadcrumbs.',
      'Preheat air fryer to 200°C and spray the fingers with oil.',
      'Air fry 10–12 min, flipping once, until crisp and golden.',
      'Serve with tartare sauce and lemon.',
    ],
    tags: ['pescatarian', 'kid-friendly', 'crispy'],
  },
  {
    id: 'airfryer-garlic-prawns',
    title: 'Air Fryer Garlic Butter Prawns',
    emoji: '🦐',
    color: '#f4845f',
    meals: ['lunch', 'dinner'],
    appliance: 'airfryer',
    cuisine: 'Global',
    time: 15,
    difficulty: 'Easy',
    servings: '2',
    setting: '190°C · 6–8 min',
    ingredients: [
      '300 g large prawns, peeled and deveined',
      '2 tbsp melted butter',
      '3 garlic cloves, minced',
      '1 tsp paprika + ¼ tsp chilli flakes',
      'Parsley, lemon, salt',
    ],
    steps: [
      'Toss the prawns with butter, garlic, paprika, chilli flakes and salt.',
      'Preheat air fryer to 190°C.',
      'Air fry 6–8 min, shaking once, until pink and opaque — do not overcook.',
      'Toss with parsley and a squeeze of lemon.',
      'Serve over pasta, rice, or with crusty bread.',
    ],
    tags: ['pescatarian', 'high-protein', 'low-carb', 'quick'],
  },
  {
    id: 'steamed-ginger-soy-fish',
    title: 'Steamed Ginger-Soy Fish',
    emoji: '🐟',
    color: '#73c2be',
    meals: ['lunch', 'dinner'],
    appliance: 'steamer',
    cuisine: 'Chinese',
    time: 25,
    difficulty: 'Easy',
    servings: '2',
    setting: 'Steam 12–15 min',
    ingredients: [
      '2 white fish fillets (sea bass, basa or tilapia)',
      '2 tbsp light soy sauce + 1 tsp sesame oil',
      '1 thumb ginger, julienned',
      '2 spring onions, shredded',
      '1 tsp sugar, pinch of white pepper',
    ],
    steps: [
      'Lay the fish on the steamer tray and scatter over half the ginger.',
      'Add water to the base and steam 12–15 minutes until it flakes easily.',
      'Mix soy, sesame oil, sugar and pepper for the sauce.',
      'Top the steamed fish with fresh ginger and spring onions, then pour over the warm sauce.',
      'Serve immediately with steamed rice.',
    ],
    tags: ['pescatarian', 'high-protein', 'low-carb', 'light'],
  },
  {
    id: 'airfryer-fish-tikka',
    title: 'Air Fryer Fish Tikka',
    emoji: '🎣',
    color: '#e07a5f',
    meals: ['lunch', 'dinner'],
    appliance: 'airfryer',
    cuisine: 'Indian',
    time: 30,
    difficulty: 'Easy',
    servings: '3',
    setting: '200°C · 10–12 min',
    ingredients: [
      '500 g firm fish (king fish, salmon or basa), cubed',
      '4 tbsp thick yogurt',
      '1 tbsp ginger-garlic paste',
      '1 tsp each: chilli powder, garam masala, cumin',
      '1 tbsp besan + 1 tbsp lemon juice, salt',
    ],
    steps: [
      'Whisk yogurt with the spices, besan, ginger-garlic, lemon and salt.',
      'Gently coat the fish and marinate 15–20 minutes (no longer, or it gets mushy).',
      'Preheat air fryer to 200°C and lay the fish out in a single layer.',
      'Air fry 10–12 min, turning once carefully, until charred at the edges.',
      'Finish with chaat masala and lemon.',
    ],
    tags: ['pescatarian', 'high-protein', 'low-carb'],
  },

  // ---------------------------- MORE COMBINATIONS ----------------------------
  {
    id: 'airfryer-crispy-tofu',
    title: 'Air Fryer Crispy Chilli Tofu',
    emoji: '🧊',
    color: '#dda15e',
    meals: ['lunch', 'dinner'],
    appliance: 'airfryer',
    cuisine: 'Asian',
    time: 30,
    difficulty: 'Easy',
    servings: '2',
    setting: '200°C · 14–16 min',
    ingredients: [
      '400 g firm tofu, pressed and cubed',
      '1 tbsp cornflour + 1 tbsp soy sauce',
      '1 tbsp oil',
      '2 tbsp sweet chilli sauce',
      '1 tsp sriracha, sesame seeds, spring onion',
    ],
    steps: [
      'Toss the tofu with soy sauce, oil and cornflour until evenly coated.',
      'Preheat air fryer to 200°C.',
      'Air fry 14–16 min, shaking twice, until golden and crisp on all sides.',
      'Toss the hot tofu with sweet chilli and sriracha.',
      'Top with sesame seeds and spring onion; serve over rice.',
    ],
    tags: ['vegan', 'vegetarian', 'high-protein', 'crispy'],
  },
  {
    id: 'airfryer-breakfast-sausages',
    title: 'Air Fryer Breakfast Sausages',
    emoji: '🌭',
    color: '#b5651d',
    meals: ['breakfast'],
    appliance: 'airfryer',
    cuisine: 'American',
    time: 15,
    difficulty: 'Easy',
    servings: '3',
    setting: '180°C · 10–12 min',
    ingredients: [
      '6 chicken or pork breakfast sausages',
      'Optional: brush of oil',
    ],
    steps: [
      'Preheat air fryer to 180°C.',
      'Arrange the sausages in a single layer with a little space between them.',
      'Air fry 10–12 min, turning halfway, until browned and cooked through.',
      'Check the thickest sausage is no longer pink inside.',
      'Serve with eggs, toast and grilled tomatoes.',
    ],
    tags: ['high-protein', 'quick', 'kid-friendly'],
  },
  {
    id: 'airfryer-veggie-frittata',
    title: 'Air Fryer Veggie Frittata',
    emoji: '🍳',
    color: '#ffca3a',
    meals: ['breakfast', 'lunch'],
    appliance: 'airfryer',
    cuisine: 'Italian',
    time: 25,
    difficulty: 'Easy',
    servings: '2',
    setting: '160°C · 12–15 min',
    ingredients: [
      '4 eggs',
      '¼ cup milk',
      '½ cup chopped peppers, onion and spinach',
      '¼ cup grated cheese',
      'Salt, pepper, chilli flakes',
    ],
    steps: [
      'Whisk eggs with milk, salt and pepper, then stir in the veg and half the cheese.',
      'Pour into a greased oven-safe dish that fits the basket; top with remaining cheese.',
      'Preheat air fryer to 160°C.',
      'Air fry 12–15 min until just set in the middle.',
      'Cool 2 minutes, slice and serve.',
    ],
    tags: ['vegetarian', 'high-protein', 'low-carb'],
  },
  {
    id: 'steamed-egg-custard',
    title: 'Steamed Savoury Egg Custard',
    emoji: '🥣',
    color: '#fefae0',
    meals: ['breakfast'],
    appliance: 'steamer',
    cuisine: 'Japanese',
    time: 25,
    difficulty: 'Medium',
    servings: '2',
    setting: 'Steam 12–15 min',
    ingredients: [
      '3 eggs',
      '1.5 cups warm dashi or light stock',
      '1 tsp soy sauce + ½ tsp mirin',
      'A few prawns, mushroom slices or peas',
      'Spring onion, to garnish',
    ],
    steps: [
      'Gently whisk the eggs (avoid foam) and stir in the warm stock, soy and mirin.',
      'Strain into 2 heatproof cups and drop in the prawns or vegetables.',
      'Cover each cup loosely with foil and place in the steamer tray.',
      'Steam 12–15 minutes on a gentle setting until just set and silky.',
      'Garnish with spring onion and serve warm.',
    ],
    tags: ['high-protein', 'light', 'low-carb'],
  },

  // ---------------------------- PORK ----------------------------
  {
    id: 'airfryer-honey-garlic-pork-chops',
    title: 'Air Fryer Honey-Garlic Pork Chops',
    emoji: '🥩',
    color: '#bc8a5f',
    meals: ['dinner'],
    appliance: 'airfryer',
    cuisine: 'American',
    time: 30,
    difficulty: 'Easy',
    servings: '2',
    setting: '200°C · 12–14 min',
    ingredients: [
      '2 thick boneless pork chops',
      '2 tbsp honey + 2 tbsp soy sauce',
      '3 garlic cloves, minced',
      '1 tsp paprika + ½ tsp black pepper',
      '1 tbsp oil, salt',
    ],
    steps: [
      'Pat the chops dry and rub with oil, paprika, salt and pepper.',
      'Whisk honey, soy and garlic into a glaze and brush over both sides.',
      'Preheat air fryer to 200°C.',
      'Air fry 12–14 min, flipping and re-glazing halfway, until cooked through (63°C internal, then rest).',
      'Rest 5 minutes — the juices redistribute and stay tender — then serve.',
    ],
    tags: ['high-protein', 'low-carb'],
  },
  {
    id: 'airfryer-crispy-pork-chops',
    title: 'Air Fryer Crispy Breaded Pork Chops',
    emoji: '🍖',
    color: '#c9a66b',
    meals: ['lunch', 'dinner'],
    appliance: 'airfryer',
    cuisine: 'American',
    time: 30,
    difficulty: 'Medium',
    servings: '3',
    setting: '200°C · 12–15 min',
    ingredients: [
      '3 boneless pork chops, pounded slightly thin',
      '1 egg, beaten',
      '1 cup breadcrumbs (panko) + 2 tbsp grated parmesan',
      '½ cup flour',
      '1 tsp garlic powder + 1 tsp paprika, salt, pepper',
      'Oil spray',
    ],
    steps: [
      'Set up seasoned flour, beaten egg, and breadcrumbs mixed with parmesan.',
      'Coat each chop in flour, then egg, then the crumb mix, pressing to stick.',
      'Preheat air fryer to 200°C and spray the chops all over with oil.',
      'Air fry 12–15 min, flipping once, until crisp and cooked through (63°C internal).',
      'Rest briefly, then serve with lemon wedges and a crisp salad.',
    ],
    tags: ['high-protein', 'crispy'],
  },
  {
    id: 'steamed-blackbean-pork-ribs',
    title: 'Steamed Black Bean Pork Ribs',
    emoji: '🍱',
    color: '#9c6644',
    meals: ['lunch', 'dinner'],
    appliance: 'steamer',
    cuisine: 'Chinese',
    time: 45,
    difficulty: 'Medium',
    servings: '3',
    setting: 'Steam 30–35 min',
    ingredients: [
      '500 g pork spare ribs, cut into bite-size pieces',
      '1.5 tbsp fermented black beans, rinsed and mashed',
      '1 tbsp soy sauce + 1 tsp sugar + 1 tsp cornflour',
      '2 garlic cloves + 1 tsp grated ginger',
      '1 tsp sesame oil, spring onion and chilli to garnish',
    ],
    steps: [
      'Marinate the ribs with black beans, soy, sugar, cornflour, garlic, ginger and sesame oil for 20 minutes.',
      'Spread the ribs in a heatproof dish that fits the steamer tray.',
      'Add water to the base and steam 30–35 minutes until tender, topping up water if needed.',
      'Check the meat pulls away easily from the bone.',
      'Garnish with spring onion and fresh chilli; serve with steamed rice.',
    ],
    tags: ['high-protein', 'dim-sum'],
  },

  // ---------------------------- PRAWNS ----------------------------
  {
    id: 'airfryer-coconut-prawns',
    title: 'Air Fryer Coconut Prawns',
    emoji: '🍤',
    color: '#f6bd60',
    meals: ['lunch', 'dinner'],
    appliance: 'airfryer',
    cuisine: 'Global',
    time: 25,
    difficulty: 'Medium',
    servings: '3',
    setting: '200°C · 8–10 min',
    ingredients: [
      '350 g large prawns, peeled with tails on',
      '1 egg, beaten',
      '½ cup flour + 1 tsp paprika, salt',
      '1 cup desiccated coconut + ½ cup panko',
      'Oil spray, sweet chilli sauce to serve',
    ],
    steps: [
      'Pat the prawns dry. Set up seasoned flour, beaten egg, and coconut mixed with panko.',
      'Coat each prawn in flour, then egg, then press into the coconut mix.',
      'Preheat air fryer to 200°C and spray the prawns with oil.',
      'Air fry 8–10 min, flipping once, until golden and the coconut is toasted — do not overcook.',
      'Serve hot with sweet chilli dipping sauce.',
    ],
    tags: ['pescatarian', 'crispy', 'party'],
  },
  {
    id: 'airfryer-tandoori-prawns',
    title: 'Air Fryer Tandoori Prawns',
    emoji: '🦐',
    color: '#e5564f',
    meals: ['lunch', 'dinner'],
    appliance: 'airfryer',
    cuisine: 'Indian',
    time: 25,
    difficulty: 'Easy',
    servings: '2',
    setting: '200°C · 7–9 min',
    ingredients: [
      '300 g large prawns, peeled and deveined',
      '3 tbsp thick yogurt',
      '1 tbsp ginger-garlic paste',
      '1 tsp each: chilli powder, garam masala, cumin',
      '1 tsp besan + 1 tbsp lemon juice, salt',
    ],
    steps: [
      'Whisk yogurt with the spices, besan, ginger-garlic, lemon and salt.',
      'Coat the prawns and marinate 15 minutes (no longer — prawns turn rubbery).',
      'Preheat air fryer to 200°C and lay the prawns in a single layer.',
      'Air fry 7–9 min, turning once, until pink, opaque and charred at the edges.',
      'Finish with chaat masala and lemon.',
    ],
    tags: ['pescatarian', 'high-protein', 'low-carb', 'spicy'],
  },
  {
    id: 'steamed-garlic-chilli-prawns',
    title: 'Steamed Garlic-Chilli Prawns',
    emoji: '🦐',
    color: '#ef6351',
    meals: ['lunch', 'dinner'],
    appliance: 'steamer',
    cuisine: 'Asian',
    time: 20,
    difficulty: 'Easy',
    servings: '2',
    setting: 'Steam 8–10 min',
    ingredients: [
      '300 g large prawns, peeled and butterflied',
      '4 garlic cloves, minced',
      '1 red chilli, finely chopped',
      '1 tbsp soy sauce + 1 tsp sesame oil',
      'Spring onion and coriander, to garnish',
    ],
    steps: [
      'Arrange the prawns in a heatproof dish and scatter over the garlic and chilli.',
      'Spoon over the soy sauce and sesame oil.',
      'Add water to the base and steam 8–10 minutes until pink and just opaque.',
      'Avoid over-steaming, or the prawns toughen.',
      'Garnish with spring onion and coriander; serve over rice or noodles.',
    ],
    tags: ['pescatarian', 'high-protein', 'low-carb', 'light', 'quick'],
  },

  // ==================== STEAMER & BREAKFAST BALANCE ====================
  {
    id: 'steamed-khaman-dhokla',
    title: 'Steamed Khaman Dhokla',
    emoji: '🟡',
    color: '#f6c453',
    meals: ['breakfast', 'snack'],
    appliance: 'steamer',
    cuisine: 'Indian',
    time: 30,
    difficulty: 'Medium',
    servings: '3',
    setting: 'Steam 15–18 min',
    ingredients: [
      '1.5 cups besan (gram flour)',
      '1 tbsp semolina + 1 tsp sugar',
      '1 tsp ginger-green chilli paste',
      '1 tsp eno fruit salt',
      'For tempering: mustard seeds, curry leaves, green chilli, 1 tsp sugar',
      'Salt, oil, coriander',
    ],
    steps: [
      'Whisk besan, semolina, sugar, ginger-chilli paste, salt and water into a smooth batter.',
      'Stir in the eno just before steaming and pour into a greased tray.',
      'Add water to the base and steam 15–18 minutes until a toothpick comes out clean.',
      'Cool, then cut into squares.',
      'Pour over a tempering of mustard seeds, curry leaves and sweet water; garnish with coriander.',
    ],
    tags: ['vegetarian', 'vegan', 'light'],
  },
  {
    id: 'steamed-puttu',
    title: 'Steamed Puttu',
    emoji: '🥥',
    color: '#e9edc9',
    meals: ['breakfast'],
    appliance: 'steamer',
    cuisine: 'Indian',
    time: 25,
    difficulty: 'Medium',
    servings: '2',
    setting: 'Steam 8–10 min',
    ingredients: [
      '2 cups roasted rice flour',
      '½ cup grated coconut',
      'Salt and warm water',
      'Banana and pappadam, to serve',
    ],
    steps: [
      'Mix rice flour with salt and sprinkle in warm water until it holds together when pressed.',
      'Layer the moist flour and grated coconut into the steamer tray or a puttu mould.',
      'Add water to the base and steam 8–10 minutes until cooked through and fluffy.',
      'Loosen gently and turn out.',
      'Serve hot with ripe banana, or with kadala curry.',
    ],
    tags: ['vegetarian', 'vegan', 'gluten-free'],
  },
  {
    id: 'steamed-gyeran-jjim',
    title: 'Korean Steamed Eggs (Gyeran-jjim)',
    emoji: '🍳',
    color: '#ffe5a5',
    meals: ['breakfast'],
    appliance: 'steamer',
    cuisine: 'Korean',
    time: 20,
    difficulty: 'Easy',
    servings: '2',
    setting: 'Steam 12–15 min',
    ingredients: [
      '4 eggs',
      '¾ cup water or stock',
      '1 tsp sesame oil',
      '1 chopped spring onion',
      'Pinch of salt, toasted sesame seeds',
    ],
    steps: [
      'Beat the eggs with the water and salt, then strain into a heatproof bowl.',
      'Place the bowl in the steamer tray and cover loosely with foil.',
      'Add water to the base and steam 12–15 minutes until just set and souffle-like.',
      'Drizzle with sesame oil.',
      'Top with spring onion and sesame seeds; serve straight from the bowl.',
    ],
    tags: ['vegetarian', 'high-protein', 'low-carb', 'light'],
  },
  {
    id: 'steamed-bao-buns',
    title: 'Steamed Veg Bao Buns',
    emoji: '🥟',
    color: '#f0efeb',
    meals: ['lunch', 'snack'],
    appliance: 'steamer',
    cuisine: 'Chinese',
    time: 40,
    difficulty: 'Medium',
    servings: '3',
    setting: 'Steam 10–12 min',
    ingredients: [
      '8 ready bao bun wrappers (or homemade)',
      '2 cups stir-fried mushrooms and cabbage',
      '1 tbsp hoisin + 1 tsp soy sauce',
      'Pickled carrot and cucumber',
      'Spring onion and crushed peanuts',
    ],
    steps: [
      'Line the steamer tray with parchment to stop sticking.',
      'Steam the folded bao buns 10–12 minutes until puffed and glossy.',
      'Toss the warm mushroom filling with hoisin and soy.',
      'Open each bun and fill with the mushrooms, pickles and spring onion.',
      'Finish with crushed peanuts and extra hoisin.',
    ],
    tags: ['vegetarian', 'vegan', 'street-food'],
  },
  {
    id: 'steamed-har-gow',
    title: 'Steamed Prawn Dumplings (Har Gow)',
    emoji: '🥟',
    color: '#ffd6c4',
    meals: ['lunch', 'dinner'],
    appliance: 'steamer',
    cuisine: 'Chinese',
    time: 40,
    difficulty: 'Medium',
    servings: '3',
    setting: 'Steam 8–10 min',
    ingredients: [
      '20 dumpling wrappers',
      '300 g prawns, roughly chopped',
      '2 tbsp chopped bamboo shoot or water chestnut',
      '1 tsp sesame oil + 1 tsp soy sauce',
      '1 tsp grated ginger, pinch of sugar and salt',
    ],
    steps: [
      'Mix prawns with bamboo shoot, sesame oil, soy, ginger, sugar and salt.',
      'Spoon filling into each wrapper and pleat to seal.',
      'Line the steamer tray with parchment and arrange the dumplings apart.',
      'Add water to the base and steam 8–10 minutes until the prawns turn pink and the skins glossy.',
      'Serve with chilli-soy dipping sauce.',
    ],
    tags: ['pescatarian', 'high-protein', 'dim-sum'],
  },
  {
    id: 'steamed-sticky-rice',
    title: 'Thai Steamed Sticky Rice',
    emoji: '🍚',
    color: '#f5f0e1',
    meals: ['lunch', 'dinner'],
    appliance: 'steamer',
    cuisine: 'Thai',
    time: 35,
    difficulty: 'Easy',
    servings: '3',
    setting: 'Steam 25–30 min',
    ingredients: [
      '2 cups glutinous (sticky) rice, soaked 4 hours',
      'Water for the base',
      'Pinch of salt',
    ],
    steps: [
      'Drain the soaked sticky rice well.',
      'Line the steamer tray with a thin cloth or parchment and spread the rice in an even layer.',
      'Add water to the base and steam 25–30 minutes, turning the rice once halfway.',
      'It is done when the grains are translucent and tender but chewy.',
      'Serve with grilled meats, curries, or mango for dessert.',
    ],
    tags: ['vegan', 'vegetarian', 'gluten-free', 'side'],
  },
  {
    id: 'steamed-garlic-broccoli',
    title: 'Steamed Garlic Broccoli',
    emoji: '🥦',
    color: '#90a955',
    meals: ['lunch', 'dinner'],
    appliance: 'steamer',
    cuisine: 'Global',
    time: 15,
    difficulty: 'Easy',
    servings: '2',
    setting: 'Steam 7–8 min',
    ingredients: [
      '1 head broccoli, cut into florets',
      '2 garlic cloves, minced',
      '1 tbsp olive oil or sesame oil',
      '1 tsp soy sauce or lemon juice',
      'Salt, chilli flakes',
    ],
    steps: [
      'Add the broccoli florets to the steamer tray.',
      'Add water to the base and steam 7–8 minutes until bright green and tender-crisp.',
      'Warm the oil with the garlic for 30 seconds.',
      'Toss the broccoli with the garlic oil and soy or lemon.',
      'Season with salt and chilli flakes; serve as a side.',
    ],
    tags: ['vegan', 'vegetarian', 'low-carb', 'side', 'quick'],
  },
  {
    id: 'steamed-sweet-potato',
    title: 'Steamed Sweet Potato',
    emoji: '🍠',
    color: '#d4a373',
    meals: ['snack'],
    appliance: 'steamer',
    cuisine: 'Global',
    time: 30,
    difficulty: 'Easy',
    servings: '2',
    setting: 'Steam 20–25 min',
    ingredients: [
      '2 medium sweet potatoes, halved',
      'Flaky salt',
      'Optional: butter or cinnamon',
    ],
    steps: [
      'Place the sweet potato halves cut-side up in the steamer tray.',
      'Add water to the base and steam 20–25 minutes until a knife slides through easily.',
      'Top up the base water if it runs low.',
      'Mash lightly with a fork at the cut surface.',
      'Finish with flaky salt, or butter and cinnamon for a sweeter snack.',
    ],
    tags: ['vegan', 'vegetarian', 'gluten-free', 'snack'],
  },
  {
    id: 'steamed-asparagus',
    title: 'Steamed Lemon Asparagus',
    emoji: '🌿',
    color: '#a3c48a',
    meals: ['lunch', 'dinner'],
    appliance: 'steamer',
    cuisine: 'Global',
    time: 12,
    difficulty: 'Easy',
    servings: '2',
    setting: 'Steam 6–8 min',
    ingredients: [
      '1 bunch asparagus, woody ends trimmed',
      '1 tbsp olive oil',
      '1 tsp lemon zest + juice',
      'Salt, black pepper, parmesan (optional)',
    ],
    steps: [
      'Lay the asparagus in the steamer tray in a single layer.',
      'Add water to the base and steam 6–8 minutes until just tender.',
      'Toss with olive oil, lemon zest and juice.',
      'Season with salt and pepper.',
      'Shave over parmesan if you like, and serve as a side.',
    ],
    tags: ['vegetarian', 'low-carb', 'side', 'quick'],
  },
  {
    id: 'steamed-jasmine-rice',
    title: 'Steamed Jasmine Rice',
    emoji: '🍚',
    color: '#f4f1de',
    meals: ['lunch', 'dinner'],
    appliance: 'steamer',
    cuisine: 'Asian',
    time: 30,
    difficulty: 'Easy',
    servings: '3',
    setting: 'Steam ~25 min',
    ingredients: [
      '1.5 cups jasmine rice, rinsed',
      '1.5 cups water',
      'Pinch of salt',
    ],
    steps: [
      'Add the rinsed rice and water to the base bowl of the multi cooker.',
      'Add a pinch of salt and stir once.',
      'Steam about 25 minutes until the water is absorbed and the rice is fluffy.',
      'Rest with the lid on for 5 minutes.',
      'Fluff with a fork and serve alongside curries or stir-fries.',
    ],
    tags: ['vegan', 'vegetarian', 'gluten-free', 'side'],
  },

  // ==================== DESSERTS ====================
  {
    id: 'steamed-chocolate-pudding',
    title: 'Steamed Chocolate Pudding',
    emoji: '🍫',
    color: '#6f4518',
    meals: ['dessert'],
    appliance: 'steamer',
    cuisine: 'British',
    time: 50,
    difficulty: 'Medium',
    servings: '3',
    setting: 'Steam 35–40 min',
    ingredients: [
      '100 g butter, softened',
      '100 g sugar',
      '2 eggs',
      '100 g flour + 2 tbsp cocoa',
      '1 tsp baking powder, splash of milk',
    ],
    steps: [
      'Cream the butter and sugar, then beat in the eggs.',
      'Fold in the flour, cocoa and baking powder with enough milk for a soft batter.',
      'Spoon into a greased heatproof bowl and cover with foil.',
      'Add water to the base and steam 35–40 minutes until risen and springy.',
      'Turn out and serve warm with custard or cream.',
    ],
    tags: ['vegetarian', 'comfort'],
  },
  {
    id: 'steamed-banana-cake',
    title: 'Steamed Banana Cake',
    emoji: '🍌',
    color: '#e9c46a',
    meals: ['dessert', 'snack'],
    appliance: 'steamer',
    cuisine: 'Global',
    time: 40,
    difficulty: 'Easy',
    servings: '3',
    setting: 'Steam 28–30 min',
    ingredients: [
      '2 ripe bananas, mashed',
      '120 g flour + 1 tsp baking powder',
      '60 g sugar',
      '1 egg + 3 tbsp oil',
      '½ tsp cinnamon',
    ],
    steps: [
      'Mix the mashed banana with sugar, egg and oil.',
      'Fold in the flour, baking powder and cinnamon until just combined.',
      'Pour into a greased heatproof tin and cover loosely with foil.',
      'Add water to the base and steam 28–30 minutes until a skewer comes out clean.',
      'Cool slightly, then slice and serve.',
    ],
    tags: ['vegetarian', 'kid-friendly'],
  },
  {
    id: 'steamed-modak',
    title: 'Steamed Modak',
    emoji: '🍡',
    color: '#fefae0',
    meals: ['dessert'],
    appliance: 'steamer',
    cuisine: 'Indian',
    time: 45,
    difficulty: 'Medium',
    servings: '3',
    setting: 'Steam 10–12 min',
    ingredients: [
      '1 cup rice flour + 1 cup hot water',
      'For filling: 1 cup grated coconut + ½ cup jaggery',
      '½ tsp cardamom',
      'Ghee, pinch of salt',
    ],
    steps: [
      'Cook the coconut and jaggery with cardamom until thick; cool this filling.',
      'Make a soft dough with rice flour, hot water, salt and a little ghee.',
      'Shape small cups of dough, fill with coconut and pinch into pleated modak.',
      'Line the steamer tray and arrange the modak apart.',
      'Add water to the base and steam 10–12 minutes until glossy; serve warm.',
    ],
    tags: ['vegetarian', 'vegan', 'gluten-free'],
  },
  {
    id: 'airfryer-churros',
    title: 'Air Fryer Churros',
    emoji: '🥖',
    color: '#caa472',
    meals: ['dessert'],
    appliance: 'airfryer',
    cuisine: 'Mexican',
    time: 30,
    difficulty: 'Medium',
    servings: '3',
    setting: '180°C · 9–10 min',
    ingredients: [
      '1 cup water + 2 tbsp butter',
      '1 cup flour',
      '1 egg',
      'Cinnamon sugar, to coat',
      'Chocolate sauce, to serve',
    ],
    steps: [
      'Boil the water and butter, then beat in the flour to a dough; cool slightly and beat in the egg.',
      'Pipe lengths of dough onto parchment using a star nozzle.',
      'Preheat air fryer to 180°C and lay the churros in a single layer.',
      'Air fry 9–10 min until golden and crisp.',
      'Toss in cinnamon sugar and serve with chocolate sauce.',
    ],
    tags: ['vegetarian', 'kid-friendly', 'party'],
  },
  {
    id: 'airfryer-brownies',
    title: 'Air Fryer Fudgy Brownies',
    emoji: '🍫',
    color: '#5a3825',
    meals: ['dessert'],
    appliance: 'airfryer',
    cuisine: 'American',
    time: 30,
    difficulty: 'Easy',
    servings: '4',
    setting: '160°C · 15–18 min',
    ingredients: [
      '100 g dark chocolate + 80 g butter, melted',
      '120 g sugar',
      '2 eggs',
      '70 g flour + 2 tbsp cocoa',
      'Pinch of salt, handful of chocolate chips',
    ],
    steps: [
      'Whisk the melted chocolate and butter with the sugar and eggs.',
      'Fold in the flour, cocoa and salt, then the chocolate chips.',
      'Pour into a greased tin that fits the basket.',
      'Preheat air fryer to 160°C and bake 15–18 min until the top is set but the centre is fudgy.',
      'Cool fully before cutting into squares.',
    ],
    tags: ['vegetarian', 'kid-friendly'],
  },
  {
    id: 'airfryer-choc-chip-cookies',
    title: 'Air Fryer Chocolate Chip Cookies',
    emoji: '🍪',
    color: '#d8a657',
    meals: ['dessert', 'snack'],
    appliance: 'airfryer',
    cuisine: 'American',
    time: 25,
    difficulty: 'Easy',
    servings: '6 cookies',
    setting: '160°C · 8–10 min',
    ingredients: [
      '100 g butter, softened',
      '80 g brown sugar + 40 g white sugar',
      '1 egg',
      '180 g flour + ½ tsp baking soda',
      '100 g chocolate chips',
    ],
    steps: [
      'Cream the butter and sugars, then beat in the egg.',
      'Fold in the flour, baking soda and chocolate chips.',
      'Scoop balls onto parchment in the basket, spaced apart.',
      'Preheat air fryer to 160°C and bake 8–10 min until golden at the edges, soft in the centre.',
      'Let them firm up for 5 minutes before lifting out.',
    ],
    tags: ['vegetarian', 'kid-friendly'],
  },
  {
    id: 'airfryer-apple-hand-pies',
    title: 'Air Fryer Apple Hand Pies',
    emoji: '🥧',
    color: '#e8b04b',
    meals: ['dessert'],
    appliance: 'airfryer',
    cuisine: 'American',
    time: 30,
    difficulty: 'Easy',
    servings: '4',
    setting: '180°C · 10–12 min',
    ingredients: [
      '1 sheet puff or shortcrust pastry',
      '2 apples, diced',
      '2 tbsp sugar + 1 tsp cinnamon',
      '1 tsp cornflour',
      '1 egg, beaten (to glaze)',
    ],
    steps: [
      'Cook the apples with sugar, cinnamon and cornflour for 3 minutes; cool.',
      'Cut pastry squares, spoon in filling, fold and crimp the edges.',
      'Brush with beaten egg and prick a steam hole.',
      'Preheat air fryer to 180°C and air fry 10–12 min until puffed and golden.',
      'Dust with sugar and cool slightly before eating.',
    ],
    tags: ['vegetarian', 'kid-friendly'],
  },
  {
    id: 'airfryer-cinnamon-doughnuts',
    title: 'Air Fryer Cinnamon Doughnuts',
    emoji: '🍩',
    color: '#dda15e',
    meals: ['dessert', 'snack'],
    appliance: 'airfryer',
    cuisine: 'American',
    time: 25,
    difficulty: 'Easy',
    servings: '4',
    setting: '180°C · 6–8 min',
    ingredients: [
      '1 can refrigerated biscuit dough (or homemade)',
      '2 tbsp melted butter',
      '½ cup sugar + 1 tbsp cinnamon',
    ],
    steps: [
      'Cut a small hole in the centre of each dough round to form rings.',
      'Preheat air fryer to 180°C and arrange the rings apart on parchment.',
      'Air fry 6–8 min until golden and puffed.',
      'Brush the warm doughnuts with melted butter.',
      'Toss in cinnamon sugar and serve immediately.',
    ],
    tags: ['vegetarian', 'kid-friendly', 'quick'],
  },
  {
    id: 'steamed-thai-custard',
    title: 'Thai Steamed Coconut Custard',
    emoji: '🥥',
    color: '#f1e3c6',
    meals: ['dessert'],
    appliance: 'steamer',
    cuisine: 'Thai',
    time: 40,
    difficulty: 'Medium',
    servings: '3',
    setting: 'Steam 25–30 min',
    ingredients: [
      '3 eggs',
      '¾ cup coconut milk',
      '½ cup palm sugar or brown sugar',
      'Pinch of salt',
      'Steamed sticky rice, to serve',
    ],
    steps: [
      'Gently whisk the eggs, coconut milk, sugar and salt until the sugar dissolves.',
      'Strain into small heatproof cups.',
      'Place the cups in the steamer tray and cover loosely with foil.',
      'Add water to the base and steam 25–30 minutes on a gentle setting until just set.',
      'Cool and serve with sticky rice.',
    ],
    tags: ['vegetarian', 'gluten-free'],
  },

  // ==================== SNACKS & APPETISERS ====================
  {
    id: 'airfryer-french-fries',
    title: 'Air Fryer French Fries',
    emoji: '🍟',
    color: '#e9c46a',
    meals: ['snack'],
    appliance: 'airfryer',
    cuisine: 'American',
    time: 30,
    difficulty: 'Easy',
    servings: '2',
    setting: '200°C · 18–20 min',
    ingredients: [
      '3 large potatoes, cut into fries',
      '1 tbsp oil',
      '1 tsp salt',
      '½ tsp paprika or garlic powder',
    ],
    steps: [
      'Soak the cut fries in cold water for 20 minutes, then pat very dry.',
      'Toss with oil, salt and paprika.',
      'Preheat air fryer to 200°C.',
      'Air fry 18–20 min, shaking 2–3 times, until deep golden and crisp.',
      'Season again and serve hot with ketchup or mayo.',
    ],
    tags: ['vegan', 'vegetarian', 'crispy', 'side', 'kid-friendly'],
  },
  {
    id: 'airfryer-onion-rings',
    title: 'Air Fryer Onion Rings',
    emoji: '🧅',
    color: '#f3d2a0',
    meals: ['snack'],
    appliance: 'airfryer',
    cuisine: 'American',
    time: 25,
    difficulty: 'Medium',
    servings: '2',
    setting: '190°C · 10–12 min',
    ingredients: [
      '2 large onions, sliced into rings',
      '½ cup flour',
      '1 egg, beaten',
      '1 cup breadcrumbs (panko)',
      '1 tsp paprika, salt, oil spray',
    ],
    steps: [
      'Separate the onion rings. Set up seasoned flour, beaten egg and breadcrumbs.',
      'Coat each ring in flour, then egg, then breadcrumbs.',
      'Preheat air fryer to 190°C and spray the rings with oil.',
      'Air fry 10–12 min, flipping once, until golden and crisp.',
      'Serve with a smoky dipping sauce.',
    ],
    tags: ['vegetarian', 'crispy', 'party'],
  },
  {
    id: 'airfryer-mozzarella-sticks',
    title: 'Air Fryer Mozzarella Sticks',
    emoji: '🧀',
    color: '#ffd166',
    meals: ['snack'],
    appliance: 'airfryer',
    cuisine: 'Italian-American',
    time: 30,
    difficulty: 'Medium',
    servings: '3',
    setting: '190°C · 6–8 min',
    ingredients: [
      '8 mozzarella string cheese sticks',
      '½ cup flour',
      '1 egg, beaten',
      '1 cup breadcrumbs + 1 tsp Italian herbs',
      'Marinara sauce, to serve',
    ],
    steps: [
      'Coat the cheese in flour, egg and herby breadcrumbs, then egg and crumbs again for a double coat.',
      'Freeze the coated sticks for at least 30 minutes (key, or they leak).',
      'Preheat air fryer to 190°C and spray with oil.',
      'Air fry 6–8 min until golden, watching closely so they do not burst.',
      'Serve immediately with warm marinara.',
    ],
    tags: ['vegetarian', 'kid-friendly', 'party'],
  },
  {
    id: 'airfryer-popcorn-chicken',
    title: 'Air Fryer Popcorn Chicken',
    emoji: '🍗',
    color: '#e0a458',
    meals: ['snack'],
    appliance: 'airfryer',
    cuisine: 'American',
    time: 30,
    difficulty: 'Easy',
    servings: '3',
    setting: '200°C · 10–12 min',
    ingredients: [
      '500 g chicken, cut into bite-size pieces',
      '½ cup buttermilk',
      '1 cup seasoned flour',
      '1 tsp paprika + 1 tsp garlic powder',
      'Oil spray, salt',
    ],
    steps: [
      'Soak the chicken in buttermilk for 15 minutes.',
      'Dredge each piece in the seasoned flour, pressing to coat.',
      'Preheat air fryer to 200°C and spray the pieces with oil.',
      'Air fry 10–12 min, shaking once, until golden and cooked through.',
      'Serve with ranch or honey mustard.',
    ],
    tags: ['high-protein', 'kid-friendly', 'crispy'],
  },
  {
    id: 'airfryer-masala-wedges',
    title: 'Air Fryer Masala Potato Wedges',
    emoji: '🥔',
    color: '#e76f51',
    meals: ['snack'],
    appliance: 'airfryer',
    cuisine: 'Indian',
    time: 30,
    difficulty: 'Easy',
    servings: '2',
    setting: '200°C · 18–20 min',
    ingredients: [
      '3 potatoes, cut into wedges',
      '1 tbsp oil',
      '1 tsp chilli powder + 1 tsp chaat masala',
      '½ tsp turmeric + ½ tsp cumin',
      'Salt, coriander',
    ],
    steps: [
      'Parboil the wedges for 4 minutes, then drain and dry.',
      'Toss with oil and all the spices.',
      'Preheat air fryer to 200°C.',
      'Air fry 18–20 min, shaking twice, until crisp outside and fluffy inside.',
      'Finish with chaat masala and coriander.',
    ],
    tags: ['vegan', 'vegetarian', 'crispy', 'side', 'spicy'],
  },
  {
    id: 'airfryer-roasted-chickpeas',
    title: 'Air Fryer Crispy Chickpeas',
    emoji: '🫘',
    color: '#bc8a5f',
    meals: ['snack'],
    appliance: 'airfryer',
    cuisine: 'Mediterranean',
    time: 25,
    difficulty: 'Easy',
    servings: '2',
    setting: '200°C · 12–15 min',
    ingredients: [
      '1 can chickpeas, drained and well dried',
      '1 tbsp olive oil',
      '1 tsp smoked paprika + ½ tsp cumin',
      'Salt, pinch of chilli',
    ],
    steps: [
      'Dry the chickpeas thoroughly on a towel for maximum crunch.',
      'Toss with oil, paprika, cumin and salt.',
      'Preheat air fryer to 200°C.',
      'Air fry 12–15 min, shaking twice, until crunchy.',
      'Cool a few minutes (they crisp further) and snack away.',
    ],
    tags: ['vegan', 'vegetarian', 'high-protein', 'gluten-free'],
  },
  {
    id: 'airfryer-tortilla-chips',
    title: 'Air Fryer Tortilla Chips',
    emoji: '🌽',
    color: '#f6bd60',
    meals: ['snack'],
    appliance: 'airfryer',
    cuisine: 'Mexican',
    time: 15,
    difficulty: 'Easy',
    servings: '2',
    setting: '180°C · 6–8 min',
    ingredients: [
      '6 corn tortillas, cut into triangles',
      '1 tbsp oil',
      'Salt + a squeeze of lime',
    ],
    steps: [
      'Brush the tortilla triangles lightly with oil.',
      'Preheat air fryer to 180°C and lay them in a single layer (cook in batches).',
      'Air fry 6–8 min, shaking once, until crisp and lightly golden.',
      'Season with salt and lime while warm.',
      'Serve with salsa or guacamole.',
    ],
    tags: ['vegan', 'vegetarian', 'gluten-free', 'crispy'],
  },
  {
    id: 'airfryer-plantain-chips',
    title: 'Air Fryer Plantain Chips',
    emoji: '🍌',
    color: '#e9d8a6',
    meals: ['snack'],
    appliance: 'airfryer',
    cuisine: 'Global',
    time: 20,
    difficulty: 'Easy',
    servings: '2',
    setting: '180°C · 10–12 min',
    ingredients: [
      '2 raw green plantains, thinly sliced',
      '1 tbsp oil',
      'Salt + a pinch of chilli or pepper',
    ],
    steps: [
      'Toss the thin plantain slices with oil and salt.',
      'Preheat air fryer to 180°C and arrange in a single layer.',
      'Air fry 10–12 min, shaking once, until crisp and golden.',
      'Watch the last couple of minutes so they do not over-brown.',
      'Season with chilli and serve.',
    ],
    tags: ['vegan', 'vegetarian', 'gluten-free', 'crispy'],
  },

  // ==================== SIDES ====================
  {
    id: 'airfryer-garlic-bread',
    title: 'Air Fryer Garlic Bread',
    emoji: '🥖',
    color: '#e3b23c',
    meals: ['lunch', 'dinner'],
    appliance: 'airfryer',
    cuisine: 'Italian',
    time: 12,
    difficulty: 'Easy',
    servings: '2',
    setting: '180°C · 5–6 min',
    ingredients: [
      '½ baguette, halved lengthwise',
      '3 tbsp soft butter',
      '3 garlic cloves, minced',
      'Chopped parsley + pinch of salt',
      'Grated cheese (optional)',
    ],
    steps: [
      'Mix the butter with garlic, parsley and salt.',
      'Spread thickly over the cut bread and add cheese if using.',
      'Preheat air fryer to 180°C.',
      'Air fry 5–6 min until golden and crisp at the edges.',
      'Slice and serve hot with pasta or soup.',
    ],
    tags: ['vegetarian', 'side', 'quick', 'kid-friendly'],
  },
  {
    id: 'airfryer-brussels-sprouts',
    title: 'Air Fryer Brussels Sprouts',
    emoji: '🥬',
    color: '#588157',
    meals: ['lunch', 'dinner'],
    appliance: 'airfryer',
    cuisine: 'Global',
    time: 20,
    difficulty: 'Easy',
    servings: '2',
    setting: '200°C · 12–15 min',
    ingredients: [
      '400 g Brussels sprouts, halved',
      '1 tbsp olive oil',
      '1 tsp balsamic + 1 tsp honey',
      'Salt, pepper, chilli flakes',
    ],
    steps: [
      'Toss the halved sprouts with oil, salt and pepper.',
      'Preheat air fryer to 200°C.',
      'Air fry 12–15 min, shaking twice, until charred and crisp at the edges.',
      'Drizzle with the balsamic and honey.',
      'Finish with chilli flakes and serve.',
    ],
    tags: ['vegan', 'vegetarian', 'low-carb', 'side'],
  },
  {
    id: 'airfryer-sweet-potato-fries',
    title: 'Air Fryer Sweet Potato Fries',
    emoji: '🍠',
    color: '#e07a5f',
    meals: ['snack'],
    appliance: 'airfryer',
    cuisine: 'American',
    time: 25,
    difficulty: 'Easy',
    servings: '2',
    setting: '200°C · 15–18 min',
    ingredients: [
      '2 sweet potatoes, cut into fries',
      '1 tbsp oil + 1 tbsp cornflour',
      '1 tsp paprika',
      'Salt, pepper',
    ],
    steps: [
      'Toss the fries with cornflour first (for crispness), then oil and spices.',
      'Preheat air fryer to 200°C.',
      'Air fry 15–18 min, shaking 2–3 times, until crisp at the edges.',
      'Spread them out and avoid overcrowding for the best crunch.',
      'Season and serve with chipotle mayo.',
    ],
    tags: ['vegan', 'vegetarian', 'side', 'kid-friendly'],
  },

  // ==================== ITALIAN PACK ====================
  {
    id: 'airfryer-margherita-pizza',
    title: 'Air Fryer Margherita Pizza',
    emoji: '🍕',
    color: '#e63946',
    meals: ['lunch', 'dinner'],
    appliance: 'airfryer',
    cuisine: 'Italian',
    time: 20,
    difficulty: 'Easy',
    servings: '1',
    setting: '180°C · 8–10 min',
    ingredients: [
      '1 small pizza base or flatbread',
      '3 tbsp tomato sauce',
      '½ cup mozzarella',
      'Fresh basil',
      '1 tsp olive oil, pinch of oregano',
    ],
    steps: [
      'Spread the tomato sauce over the base and scatter the mozzarella.',
      'Preheat air fryer to 180°C.',
      'Air fry 8–10 min until the cheese is bubbling and the base is crisp.',
      'Top with fresh basil and a drizzle of olive oil.',
      'Slice and serve straight away.',
    ],
    tags: ['vegetarian', 'kid-friendly', 'quick'],
  },
  {
    id: 'airfryer-arancini',
    title: 'Air Fryer Arancini',
    emoji: '🍙',
    color: '#e9b44c',
    meals: ['snack'],
    appliance: 'airfryer',
    cuisine: 'Italian',
    time: 35,
    difficulty: 'Medium',
    servings: '3',
    setting: '190°C · 10–12 min',
    ingredients: [
      '2 cups cold cooked risotto or rice',
      '½ cup mozzarella cubes',
      '½ cup flour, 1 egg, 1 cup breadcrumbs',
      '2 tbsp parmesan',
      'Oil spray, salt',
    ],
    steps: [
      'Shape the rice around a cube of mozzarella into balls.',
      'Coat in flour, egg, then parmesan breadcrumbs.',
      'Preheat air fryer to 190°C and spray with oil.',
      'Air fry 10–12 min, turning once, until crisp and golden.',
      'Serve with marinara for dipping.',
    ],
    tags: ['vegetarian', 'party'],
  },
  {
    id: 'airfryer-eggplant-parmesan',
    title: 'Air Fryer Eggplant Parmesan',
    emoji: '🍆',
    color: '#7b2cbf',
    meals: ['dinner'],
    appliance: 'airfryer',
    cuisine: 'Italian',
    time: 35,
    difficulty: 'Medium',
    servings: '2',
    setting: '190°C · 12–15 min',
    ingredients: [
      '1 large aubergine, sliced into rounds',
      '½ cup flour, 1 egg, 1 cup herby breadcrumbs',
      '1 cup marinara',
      '1 cup mozzarella + parmesan',
      'Salt, basil',
    ],
    steps: [
      'Salt the aubergine slices for 10 minutes, then pat dry.',
      'Coat in flour, egg and breadcrumbs.',
      'Preheat air fryer to 190°C and air fry the slices 8 min until golden.',
      'Top each with marinara and cheese; air fry 4–6 min more until bubbling.',
      'Finish with basil and serve.',
    ],
    tags: ['vegetarian', 'comfort'],
  },
  {
    id: 'airfryer-spinach-calzone',
    title: 'Air Fryer Spinach Calzone',
    emoji: '🥟',
    color: '#bc6c25',
    meals: ['lunch', 'dinner'],
    appliance: 'airfryer',
    cuisine: 'Italian',
    time: 30,
    difficulty: 'Medium',
    servings: '2',
    setting: '180°C · 10–12 min',
    ingredients: [
      '1 ball pizza dough',
      '1 cup chopped spinach',
      '½ cup ricotta + ½ cup mozzarella',
      '2 tbsp marinara',
      '1 egg (to glaze), salt, pepper',
    ],
    steps: [
      'Mix the spinach, ricotta, mozzarella, marinara, salt and pepper.',
      'Roll the dough into rounds, fill one half and fold over, sealing the edge.',
      'Brush with beaten egg and cut a small steam vent.',
      'Preheat air fryer to 180°C and air fry 10–12 min until golden.',
      'Rest a couple of minutes, then serve with extra marinara.',
    ],
    tags: ['vegetarian', 'comfort'],
  },

  // ==================== KOREAN PACK ====================
  {
    id: 'airfryer-korean-fried-chicken',
    title: 'Air Fryer Korean Fried Chicken',
    emoji: '🍗',
    color: '#bf0603',
    meals: ['dinner'],
    appliance: 'airfryer',
    cuisine: 'Korean',
    time: 40,
    difficulty: 'Medium',
    servings: '3',
    setting: '200°C · 18–20 min',
    ingredients: [
      '700 g chicken wings or boneless thighs',
      '3 tbsp cornflour',
      'For sauce: 2 tbsp gochujang, 2 tbsp honey, 1 tbsp soy, 2 garlic cloves',
      '1 tsp sesame oil',
      'Sesame seeds, spring onion',
    ],
    steps: [
      'Toss the chicken in cornflour for a crisp coating.',
      'Preheat air fryer to 200°C and air fry 18–20 min, turning, until deeply crisp.',
      'Simmer the gochujang, honey, soy, garlic and sesame oil into a glossy sauce.',
      'Toss the hot chicken in the sauce.',
      'Top with sesame seeds and spring onion.',
    ],
    tags: ['high-protein', 'spicy', 'party'],
  },
  {
    id: 'airfryer-gochujang-tofu',
    title: 'Air Fryer Gochujang Tofu',
    emoji: '🧊',
    color: '#d62828',
    meals: ['lunch', 'dinner'],
    appliance: 'airfryer',
    cuisine: 'Korean',
    time: 30,
    difficulty: 'Easy',
    servings: '2',
    setting: '200°C · 14–16 min',
    ingredients: [
      '400 g firm tofu, pressed and cubed',
      '1 tbsp cornflour + 1 tbsp oil',
      'For sauce: 1.5 tbsp gochujang, 1 tbsp maple syrup, 1 tsp soy, 1 garlic clove',
      'Sesame seeds, spring onion',
    ],
    steps: [
      'Toss the tofu with oil and cornflour.',
      'Preheat air fryer to 200°C and air fry 14–16 min, shaking twice, until crisp.',
      'Mix the gochujang, maple syrup, soy and garlic into a sauce.',
      'Toss the hot tofu in the sauce.',
      'Top with sesame seeds and spring onion; serve over rice.',
    ],
    tags: ['vegan', 'vegetarian', 'high-protein', 'spicy'],
  },

  // ==================== MEXICAN PACK ====================
  {
    id: 'airfryer-chicken-taquitos',
    title: 'Air Fryer Chicken Taquitos',
    emoji: '🌯',
    color: '#bb9457',
    meals: ['lunch', 'dinner', 'snack'],
    appliance: 'airfryer',
    cuisine: 'Mexican',
    time: 25,
    difficulty: 'Easy',
    servings: '3',
    setting: '200°C · 8–10 min',
    ingredients: [
      '2 cups shredded cooked chicken',
      '½ cup cream cheese + ½ cup grated cheese',
      '1 tsp cumin + 1 tsp paprika',
      '10 small tortillas',
      'Oil spray, salt',
    ],
    steps: [
      'Mix the chicken with cream cheese, grated cheese and spices.',
      'Spoon filling onto each tortilla and roll up tightly.',
      'Preheat air fryer to 200°C and spray the taquitos with oil, seam-side down.',
      'Air fry 8–10 min until crisp and golden.',
      'Serve with salsa, guacamole and sour cream.',
    ],
    tags: ['high-protein', 'kid-friendly', 'crispy'],
  },
  {
    id: 'airfryer-cheese-quesadilla',
    title: 'Air Fryer Cheese Quesadilla',
    emoji: '🫓',
    color: '#e9c46a',
    meals: ['lunch', 'snack'],
    appliance: 'airfryer',
    cuisine: 'Mexican',
    time: 12,
    difficulty: 'Easy',
    servings: '1',
    setting: '180°C · 6–8 min',
    ingredients: [
      '2 tortillas',
      '1 cup grated cheese',
      '¼ cup corn and beans',
      'Pinch of cumin and chilli',
      'Salsa, to serve',
    ],
    steps: [
      'Scatter cheese, corn and beans over one tortilla and top with the second.',
      'Preheat air fryer to 180°C.',
      'Air fry 6–8 min, flipping halfway, until crisp and the cheese has melted.',
      'Press lightly and cut into wedges.',
      'Serve with salsa and sour cream.',
    ],
    tags: ['vegetarian', 'kid-friendly', 'quick'],
  },
  {
    id: 'airfryer-elote',
    title: 'Air Fryer Elote (Street Corn)',
    emoji: '🌽',
    color: '#ffd60a',
    meals: ['snack'],
    appliance: 'airfryer',
    cuisine: 'Mexican',
    time: 20,
    difficulty: 'Easy',
    servings: '2',
    setting: '200°C · 12–14 min',
    ingredients: [
      '2 corn cobs',
      '2 tbsp mayo + 1 tbsp sour cream',
      '¼ cup crumbled feta or cotija',
      '1 tsp chilli powder + lime',
      'Coriander',
    ],
    steps: [
      'Preheat air fryer to 200°C and air fry the corn 12–14 min, turning, until charred.',
      'Mix the mayo and sour cream.',
      'Slather over the hot corn.',
      'Roll in crumbled cheese and dust with chilli powder.',
      'Finish with lime and coriander.',
    ],
    tags: ['vegetarian', 'side', 'party'],
  },

  // ==================== THAI PACK ====================
  {
    id: 'airfryer-thai-fish-cakes',
    title: 'Air Fryer Thai Fish Cakes',
    emoji: '🐟',
    color: '#e76f51',
    meals: ['snack', 'dinner'],
    appliance: 'airfryer',
    cuisine: 'Thai',
    time: 30,
    difficulty: 'Medium',
    servings: '3',
    setting: '190°C · 10–12 min',
    ingredients: [
      '400 g white fish, minced',
      '1 tbsp red curry paste',
      '1 tsp fish sauce',
      '2 green beans, finely sliced',
      'Kaffir lime leaf, oil spray',
    ],
    steps: [
      'Mix the fish with curry paste, fish sauce, beans and shredded lime leaf.',
      'Shape into small flat cakes.',
      'Preheat air fryer to 190°C and spray with oil.',
      'Air fry 10–12 min, turning once, until golden and springy.',
      'Serve with sweet chilli cucumber dip.',
    ],
    tags: ['pescatarian', 'high-protein', 'spicy'],
  },
  {
    id: 'airfryer-chicken-satay',
    title: 'Air Fryer Chicken Satay',
    emoji: '🍢',
    color: '#cb997e',
    meals: ['lunch', 'dinner'],
    appliance: 'airfryer',
    cuisine: 'Thai',
    time: 35,
    difficulty: 'Easy',
    servings: '3',
    setting: '200°C · 10–12 min',
    ingredients: [
      '500 g chicken thigh strips',
      '½ cup coconut milk + 1 tbsp curry powder',
      '1 tbsp soy + 1 tsp turmeric',
      'For sauce: peanut butter, soy, lime, chilli',
      'Skewers',
    ],
    steps: [
      'Marinate the chicken in coconut milk, curry powder, soy and turmeric for 20 minutes.',
      'Thread onto skewers (or lay flat).',
      'Preheat air fryer to 200°C and air fry 10–12 min, turning once.',
      'Whisk peanut butter with soy, lime and chilli plus water for the dipping sauce.',
      'Serve the satay with peanut sauce.',
    ],
    tags: ['high-protein', 'party'],
  },

  // ==================== MORE REGIONAL INDIAN ====================
  {
    id: 'airfryer-tandoori-aloo',
    title: 'Air Fryer Tandoori Aloo',
    emoji: '🥔',
    color: '#d8572a',
    meals: ['snack'],
    appliance: 'airfryer',
    cuisine: 'Indian',
    time: 30,
    difficulty: 'Easy',
    servings: '2',
    setting: '200°C · 15–18 min',
    ingredients: [
      '4 baby potatoes, parboiled and halved',
      '3 tbsp thick yogurt',
      '1 tbsp tandoori masala + 1 tsp chilli powder',
      '1 tsp ginger-garlic paste',
      '1 tbsp besan, oil, salt',
    ],
    steps: [
      'Whisk yogurt with the spices, besan, ginger-garlic, oil and salt.',
      'Coat the parboiled potatoes and marinate 15 minutes.',
      'Preheat air fryer to 200°C.',
      'Air fry 15–18 min, shaking once, until charred and crisp.',
      'Finish with chaat masala and lemon.',
    ],
    tags: ['vegetarian', 'spicy', 'side'],
  },
  {
    id: 'airfryer-masala-vada',
    title: 'Air Fryer Masala Vada',
    emoji: '🟤',
    color: '#a47148',
    meals: ['snack'],
    appliance: 'airfryer',
    cuisine: 'Indian',
    time: 30,
    difficulty: 'Medium',
    servings: '3',
    setting: '190°C · 12–14 min',
    ingredients: [
      '1 cup chana dal, soaked 2 hours',
      '1 onion + 2 green chillies, chopped',
      'Curry leaves, fennel seeds',
      'Ginger, salt, coriander',
      'Oil spray',
    ],
    steps: [
      'Coarsely grind most of the soaked dal, keeping some whole for texture.',
      'Mix in the onion, chillies, curry leaves, fennel, ginger and salt.',
      'Shape into flat patties.',
      'Preheat air fryer to 190°C and spray with oil; air fry 12–14 min, flipping once, until crisp.',
      'Serve hot with coconut chutney.',
    ],
    tags: ['vegan', 'vegetarian', 'high-protein', 'crispy'],
  },
  {
    id: 'steamed-patra',
    title: 'Steamed Patra (Colocasia Rolls)',
    emoji: '🌯',
    color: '#606c38',
    meals: ['snack'],
    appliance: 'steamer',
    cuisine: 'Indian',
    time: 45,
    difficulty: 'Medium',
    servings: '3',
    setting: 'Steam 20 min',
    ingredients: [
      '8 colocasia (arbi) leaves',
      '1.5 cups besan',
      '2 tbsp tamarind + 1 tbsp jaggery',
      '1 tsp each chilli, turmeric, coriander powder',
      'For tempering: mustard and sesame seeds',
    ],
    steps: [
      'Make a thick spreadable paste with besan, tamarind, jaggery, spices and water.',
      'Spread over each leaf, stack, roll up tightly and slice into rounds.',
      'Line the steamer tray and arrange the rolls apart.',
      'Add water to the base and steam 20 minutes until set.',
      'Temper with mustard and sesame seeds; serve warm.',
    ],
    tags: ['vegetarian', 'vegan', 'street-food'],
  },
  {
    id: 'airfryer-stuffed-mirchi',
    title: 'Air Fryer Stuffed Mirchi Bajji',
    emoji: '🌶️',
    color: '#80b918',
    meals: ['snack'],
    appliance: 'airfryer',
    cuisine: 'Indian',
    time: 25,
    difficulty: 'Easy',
    servings: '2',
    setting: '190°C · 10–12 min',
    ingredients: [
      '6 large mild chillies (bhavnagri), slit',
      '1 cup mashed spiced potato',
      '1 tsp chaat masala + ½ tsp amchur',
      '2 tbsp besan + oil spray',
      'Salt',
    ],
    steps: [
      'Mix the mashed potato with chaat masala, amchur and salt.',
      'Stuff into the slit chillies and dust with besan.',
      'Preheat air fryer to 190°C and spray with oil.',
      'Air fry 10–12 min, turning once, until blistered and tender.',
      'Sprinkle with chaat masala and serve.',
    ],
    tags: ['vegetarian', 'vegan', 'spicy', 'street-food'],
  },

  // ==================== MORE BREAKFAST & DIET-FOCUSED ====================
  {
    id: 'airfryer-egg-muffins',
    title: 'Air Fryer Egg Muffins',
    emoji: '🧁',
    color: '#ffca3a',
    meals: ['breakfast'],
    appliance: 'airfryer',
    cuisine: 'Global',
    time: 20,
    difficulty: 'Easy',
    servings: '2',
    setting: '160°C · 10–12 min',
    ingredients: [
      '4 eggs',
      '¼ cup chopped peppers, spinach, onion',
      '¼ cup grated cheese',
      'Salt, pepper',
      'Silicone muffin cups',
    ],
    steps: [
      'Whisk the eggs with salt and pepper, then stir in the veg and cheese.',
      'Pour into greased silicone muffin cups.',
      'Preheat air fryer to 160°C and place the cups in the basket.',
      'Air fry 10–12 min until set and puffed.',
      'Cool 2 minutes, pop out and serve; great for meal-prep.',
    ],
    tags: ['vegetarian', 'high-protein', 'low-carb', 'keto', 'meal-prep'],
  },
  {
    id: 'airfryer-granola',
    title: 'Air Fryer Granola Clusters',
    emoji: '🥣',
    color: '#cb997e',
    meals: ['breakfast', 'snack'],
    appliance: 'airfryer',
    cuisine: 'Global',
    time: 20,
    difficulty: 'Easy',
    servings: '4',
    setting: '160°C · 10–12 min',
    ingredients: [
      '2 cups rolled oats',
      '½ cup mixed nuts and seeds',
      '3 tbsp maple syrup + 2 tbsp oil',
      '1 tsp cinnamon, pinch of salt',
      'Dried fruit, to finish',
    ],
    steps: [
      'Toss the oats, nuts and seeds with maple syrup, oil, cinnamon and salt.',
      'Line the basket with parchment and press the mix into a flat layer.',
      'Preheat air fryer to 160°C and air fry 10–12 min, stirring once, until golden.',
      'Let it cool completely so it clumps into clusters.',
      'Stir through dried fruit and store in a jar.',
    ],
    tags: ['vegan', 'vegetarian', 'meal-prep'],
  },
  {
    id: 'airfryer-breakfast-potatoes',
    title: 'Air Fryer Breakfast Potatoes',
    emoji: '🥔',
    color: '#e9a23b',
    meals: ['breakfast'],
    appliance: 'airfryer',
    cuisine: 'American',
    time: 25,
    difficulty: 'Easy',
    servings: '2',
    setting: '200°C · 15–18 min',
    ingredients: [
      '3 potatoes, diced',
      '1 tbsp oil',
      '1 tsp paprika + ½ tsp garlic powder',
      '½ onion, diced',
      'Salt, pepper',
    ],
    steps: [
      'Toss the diced potato and onion with oil, paprika, garlic, salt and pepper.',
      'Preheat air fryer to 200°C.',
      'Air fry 15–18 min, shaking twice, until crisp and golden.',
      'Check the potatoes are tender in the middle.',
      'Serve with eggs and toast.',
    ],
    tags: ['vegan', 'vegetarian', 'kid-friendly'],
  },
  {
    id: 'airfryer-banana-bread',
    title: 'Air Fryer Banana Bread',
    emoji: '🍞',
    color: '#dda15e',
    meals: ['breakfast', 'dessert'],
    appliance: 'airfryer',
    cuisine: 'American',
    time: 35,
    difficulty: 'Easy',
    servings: '4',
    setting: '160°C · 22–25 min',
    ingredients: [
      '3 ripe bananas, mashed',
      '150 g flour + 1 tsp baking soda',
      '80 g sugar',
      '1 egg + 4 tbsp oil',
      '½ tsp cinnamon, pinch of salt',
    ],
    steps: [
      'Mix the mashed banana with sugar, egg and oil.',
      'Fold in the flour, baking soda, cinnamon and salt.',
      'Pour into a greased loaf tin that fits the basket.',
      'Preheat air fryer to 160°C and bake 22–25 min until a skewer comes out clean (cover with foil if browning fast).',
      'Cool before slicing.',
    ],
    tags: ['vegetarian', 'kid-friendly'],
  },
  {
    id: 'steamed-chicken-congee',
    title: 'Steamed Chicken Congee',
    emoji: '🥣',
    color: '#edede9',
    meals: ['breakfast'],
    appliance: 'steamer',
    cuisine: 'Chinese',
    time: 50,
    difficulty: 'Easy',
    servings: '2',
    setting: 'Steam ~40 min',
    ingredients: [
      '½ cup rice',
      '4 cups water or stock',
      '1 chicken breast',
      '1 tsp grated ginger',
      'Spring onion, soy sauce, white pepper',
    ],
    steps: [
      'Add the rice, water, ginger and chicken to the base bowl.',
      'Steam about 40 minutes until the rice breaks down into a soft porridge.',
      'Lift out the chicken, shred it, and stir it back in.',
      'Season with soy sauce and white pepper.',
      'Top with spring onion and serve hot.',
    ],
    tags: ['high-protein', 'light', 'comfort'],
  },

  // ==================== VIRAL / MOST-VIEWED (social media) ====================
  {
    id: 'airfryer-bang-bang-salmon',
    title: 'Air Fryer Bang Bang Salmon Bites',
    emoji: '🍣',
    color: '#ef798a',
    meals: ['dinner', 'snack'],
    appliance: 'airfryer',
    cuisine: 'Asian-Fusion',
    time: 20,
    difficulty: 'Easy',
    servings: '2',
    setting: '200°C · 8–10 min',
    ingredients: [
      '400 g salmon, cut into cubes',
      '1 tbsp oil + 1 tsp paprika, salt, pepper',
      'For bang bang sauce: 3 tbsp mayo',
      '2 tbsp sweet chilli sauce',
      '1 tsp sriracha + 1 tsp honey',
    ],
    steps: [
      'Toss the salmon cubes with oil, paprika, salt and pepper.',
      'Preheat air fryer to 200°C.',
      'Air fry 8–10 min, shaking once, until crisp at the edges and just cooked.',
      'Whisk the mayo, sweet chilli, sriracha and honey into the bang bang sauce.',
      'Drizzle over (or toss) the salmon; serve over rice with spring onion.',
    ],
    tags: ['viral', 'pescatarian', 'high-protein', 'spicy'],
  },
  {
    id: 'airfryer-bang-bang-chicken',
    title: 'Air Fryer Bang Bang Chicken Bites',
    emoji: '🍗',
    color: '#e5564f',
    meals: ['dinner', 'snack'],
    appliance: 'airfryer',
    cuisine: 'Asian-Fusion',
    time: 30,
    difficulty: 'Easy',
    servings: '3',
    setting: '200°C · 10–12 min',
    ingredients: [
      '500 g chicken breast, cubed',
      '½ cup cornflour + 1 egg',
      '1 tsp garlic powder + paprika, salt',
      'For sauce: 4 tbsp mayo + 3 tbsp sweet chilli',
      '1–2 tsp sriracha, oil spray',
    ],
    steps: [
      'Dip the chicken in beaten egg, then toss in seasoned cornflour.',
      'Preheat air fryer to 200°C and spray the bites with oil.',
      'Air fry 10–12 min, shaking once, until golden and cooked through.',
      'Whisk the mayo, sweet chilli and sriracha into bang bang sauce.',
      'Toss the hot bites in sauce (or serve on the side) with spring onion.',
    ],
    tags: ['viral', 'high-protein', 'kid-friendly', 'spicy'],
  },
  {
    id: 'airfryer-pasta-chips',
    title: 'Air Fryer Pasta Chips',
    emoji: '🍝',
    color: '#f4a261',
    meals: ['snack'],
    appliance: 'airfryer',
    cuisine: 'Italian-American',
    time: 25,
    difficulty: 'Easy',
    servings: '2',
    setting: '200°C · 10–12 min',
    ingredients: [
      '2 cups cooked penne or bowtie pasta',
      '1 tbsp olive oil',
      '3 tbsp grated parmesan',
      '1 tsp Italian herbs + 1 tsp garlic powder',
      'Salt, marinara to dip',
    ],
    steps: [
      'Toss the cooked pasta with oil, parmesan, herbs, garlic and salt.',
      'Preheat air fryer to 200°C.',
      'Air fry 10–12 min, shaking halfway, until crunchy and golden.',
      'Watch the last couple of minutes so they crisp but do not burn.',
      'Serve hot with marinara for dipping.',
    ],
    tags: ['viral', 'vegetarian', 'crispy', 'party'],
  },
  {
    id: 'airfryer-corn-ribs',
    title: 'Air Fryer Corn Ribs',
    emoji: '🌽',
    color: '#ffd60a',
    meals: ['snack'],
    appliance: 'airfryer',
    cuisine: 'Global',
    time: 25,
    difficulty: 'Medium',
    servings: '2',
    setting: '200°C · 10–12 min',
    ingredients: [
      '2 corn cobs, quartered lengthwise into "ribs"',
      '1 tbsp melted butter or oil',
      '1 tsp paprika + ½ tsp garlic powder',
      'Salt, chilli flakes',
      'Lime and coriander, to finish',
    ],
    steps: [
      'Carefully quarter each cob lengthwise into ribs (a sturdy knife helps).',
      'Brush with butter and toss with paprika, garlic, salt and chilli.',
      'Preheat air fryer to 200°C.',
      'Air fry 10–12 min until they curl up and char at the edges.',
      'Finish with lime and coriander.',
    ],
    tags: ['viral', 'vegetarian', 'side', 'spicy'],
  },
  {
    id: 'airfryer-baked-feta-pasta',
    title: 'Air Fryer Baked Feta Pasta',
    emoji: '🧀',
    color: '#e76f51',
    meals: ['lunch', 'dinner'],
    appliance: 'airfryer',
    cuisine: 'Mediterranean',
    time: 30,
    difficulty: 'Easy',
    servings: '2',
    setting: '180°C · 12–15 min',
    ingredients: [
      '1 block feta',
      '2 cups cherry tomatoes',
      '2 tbsp olive oil + 2 garlic cloves',
      'Salt, pepper, chilli flakes, basil',
      '250 g pasta, cooked',
    ],
    steps: [
      'Put the feta in the middle of an oven-safe dish and surround with tomatoes, oil and garlic.',
      'Preheat air fryer to 180°C.',
      'Air fry 12–15 min until the tomatoes burst and the feta is soft and golden.',
      'Mash and stir into a sauce, then fold through the cooked pasta.',
      'Finish with basil and chilli flakes.',
    ],
    tags: ['viral', 'vegetarian', 'comfort'],
  },
  {
    id: 'airfryer-creme-brulee',
    title: 'Air Fryer Crème Brûlée',
    emoji: '🍮',
    color: '#e9c46a',
    meals: ['dessert'],
    appliance: 'airfryer',
    cuisine: 'French',
    time: 40,
    difficulty: 'Medium',
    servings: '2',
    setting: '160°C · 10–12 min',
    ingredients: [
      '4 egg yolks',
      '1 cup cream',
      '3 tbsp sugar + 1 tsp vanilla',
      'Extra sugar, to caramelise',
    ],
    steps: [
      'Whisk the yolks, sugar and vanilla, then mix in the cream.',
      'Strain into ramekins and place in the air fryer.',
      'Air fry at 160°C for 10–12 min until just set with a slight wobble.',
      'Chill at least 2 hours.',
      'Sprinkle with sugar and caramelise with a torch (or a quick blast in the air fryer).',
    ],
    tags: ['viral', 'vegetarian'],
  },
  {
    id: 'airfryer-nutella-toast-pies',
    title: 'Air Fryer Nutella Toast Pies',
    emoji: '🍫',
    color: '#6f4518',
    meals: ['dessert', 'snack'],
    appliance: 'airfryer',
    cuisine: 'Global',
    time: 12,
    difficulty: 'Easy',
    servings: '2',
    setting: '180°C · 5–6 min',
    ingredients: [
      '4 slices soft bread',
      '4 tbsp Nutella',
      '1 tbsp melted butter',
      'Icing sugar, to dust',
    ],
    steps: [
      'Spread Nutella on two slices and top with the others; press and seal the edges with a fork.',
      'Brush both sides with melted butter.',
      'Preheat air fryer to 180°C.',
      'Air fry 5–6 min, flipping once, until golden and crisp.',
      'Dust with icing sugar and eat warm (the filling is molten).',
    ],
    tags: ['viral', 'vegetarian', 'kid-friendly', 'quick'],
  },
  {
    id: 'airfryer-soy-chicken-thighs',
    title: 'Air Fryer Soy Sauce Chicken Thighs',
    emoji: '🍗',
    color: '#7f4f24',
    meals: ['dinner'],
    appliance: 'airfryer',
    cuisine: 'Asian',
    time: 35,
    difficulty: 'Easy',
    servings: '3',
    setting: '190°C · 18–20 min',
    ingredients: [
      '6 bone-in chicken thighs',
      '3 tbsp soy sauce + 1 tbsp dark soy',
      '3 garlic cloves + 1 tsp five-spice',
      '1 tbsp sugar + ½ tsp white pepper',
      'Spring onion',
    ],
    steps: [
      'Marinate the thighs in soy, dark soy, garlic, five-spice, sugar and pepper for 30 minutes.',
      'Preheat air fryer to 190°C.',
      'Air fry skin-side down 10 min, flip, then 8–10 min more until lacquered and cooked (74°C).',
      'Rest 3 minutes.',
      'Spoon over any juices and top with spring onion; serve with rice.',
    ],
    tags: ['viral', 'high-protein'],
  },
  {
    id: 'airfryer-smashed-potatoes',
    title: 'Air Fryer Crispy Smashed Potatoes',
    emoji: '🥔',
    color: '#e9a23b',
    meals: ['snack'],
    appliance: 'airfryer',
    cuisine: 'Global',
    time: 35,
    difficulty: 'Easy',
    servings: '2',
    setting: '200°C · 15–18 min',
    ingredients: [
      '8 baby potatoes',
      '2 tbsp olive oil',
      '2 garlic cloves, minced',
      'Rosemary or herbs, salt, pepper',
      'Grated parmesan (optional)',
    ],
    steps: [
      'Boil the baby potatoes until fork-tender, then drain.',
      'Press each one flat with the base of a glass.',
      'Brush with garlic oil and season well.',
      'Preheat air fryer to 200°C and air fry 15–18 min until deeply crisp.',
      'Shower with parmesan and herbs; serve as a side or snack.',
    ],
    tags: ['viral', 'vegetarian', 'crispy', 'side'],
  },
  {
    id: 'steamed-soup-dumplings',
    title: 'Steamed Soup Dumplings (Xiao Long Bao)',
    emoji: '🥟',
    color: '#ffd6c4',
    meals: ['lunch', 'dinner'],
    appliance: 'steamer',
    cuisine: 'Chinese',
    time: 45,
    difficulty: 'Medium',
    servings: '3',
    setting: 'Steam 8–10 min',
    ingredients: [
      '24 dumpling wrappers',
      '300 g pork mince',
      '1 cup set jellied stock, diced (the "soup")',
      '1 tbsp soy + 1 tsp sesame oil + 1 tsp ginger',
      'Spring onion, black vinegar to dip',
    ],
    steps: [
      'Mix the pork with soy, sesame oil, ginger and spring onion, then fold in the diced jellied stock.',
      'Spoon filling into each wrapper and pleat into little purses, sealing the top.',
      'Line the steamer tray with parchment and arrange the dumplings apart.',
      'Add water to the base and steam 8–10 minutes until the wrappers are translucent and the centre is soupy.',
      'Lift carefully and serve with ginger-black vinegar dip.',
    ],
    tags: ['viral', 'high-protein', 'dim-sum', 'street-food'],
  },
]

// Build the unique, sorted list of tags for the filter UI.
export const ALL_TAGS = Array.from(
  new Set(recipes.flatMap((r) => r.tags)),
).sort()
